/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// node_modules/mustache/mustache.js
var require_mustache = __commonJS({
  "node_modules/mustache/mustache.js"(exports, module2) {
    (function(global, factory) {
      typeof exports === "object" && typeof module2 !== "undefined" ? module2.exports = factory() : typeof define === "function" && define.amd ? define(factory) : (global = global || self, global.Mustache = factory());
    })(exports, function() {
      "use strict";
      var objectToString = Object.prototype.toString;
      var isArray = Array.isArray || function isArrayPolyfill(object) {
        return objectToString.call(object) === "[object Array]";
      };
      function isFunction(object) {
        return typeof object === "function";
      }
      function typeStr(obj) {
        return isArray(obj) ? "array" : typeof obj;
      }
      function escapeRegExp(string) {
        return string.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g, "\\$&");
      }
      function hasProperty(obj, propName) {
        return obj != null && typeof obj === "object" && propName in obj;
      }
      function primitiveHasOwnProperty(primitive, propName) {
        return primitive != null && typeof primitive !== "object" && primitive.hasOwnProperty && primitive.hasOwnProperty(propName);
      }
      var regExpTest = RegExp.prototype.test;
      function testRegExp(re, string) {
        return regExpTest.call(re, string);
      }
      var nonSpaceRe = /\S/;
      function isWhitespace(string) {
        return !testRegExp(nonSpaceRe, string);
      }
      var entityMap = {
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#39;",
        "/": "&#x2F;",
        "`": "&#x60;",
        "=": "&#x3D;"
      };
      function escapeHtml(string) {
        return String(string).replace(/[&<>"'`=\/]/g, function fromEntityMap(s) {
          return entityMap[s];
        });
      }
      var whiteRe = /\s*/;
      var spaceRe = /\s+/;
      var equalsRe = /\s*=/;
      var curlyRe = /\s*\}/;
      var tagRe = /#|\^|\/|>|\{|&|=|!/;
      function parseTemplate(template, tags) {
        if (!template)
          return [];
        var lineHasNonSpace = false;
        var sections = [];
        var tokens = [];
        var spaces = [];
        var hasTag = false;
        var nonSpace = false;
        var indentation = "";
        var tagIndex = 0;
        function stripSpace() {
          if (hasTag && !nonSpace) {
            while (spaces.length)
              delete tokens[spaces.pop()];
          } else {
            spaces = [];
          }
          hasTag = false;
          nonSpace = false;
        }
        var openingTagRe, closingTagRe, closingCurlyRe;
        function compileTags(tagsToCompile) {
          if (typeof tagsToCompile === "string")
            tagsToCompile = tagsToCompile.split(spaceRe, 2);
          if (!isArray(tagsToCompile) || tagsToCompile.length !== 2)
            throw new Error("Invalid tags: " + tagsToCompile);
          openingTagRe = new RegExp(escapeRegExp(tagsToCompile[0]) + "\\s*");
          closingTagRe = new RegExp("\\s*" + escapeRegExp(tagsToCompile[1]));
          closingCurlyRe = new RegExp("\\s*" + escapeRegExp("}" + tagsToCompile[1]));
        }
        compileTags(tags || mustache.tags);
        var scanner = new Scanner(template);
        var start, type, value, chr, token, openSection;
        while (!scanner.eos()) {
          start = scanner.pos;
          value = scanner.scanUntil(openingTagRe);
          if (value) {
            for (var i = 0, valueLength = value.length; i < valueLength; ++i) {
              chr = value.charAt(i);
              if (isWhitespace(chr)) {
                spaces.push(tokens.length);
                indentation += chr;
              } else {
                nonSpace = true;
                lineHasNonSpace = true;
                indentation += " ";
              }
              tokens.push(["text", chr, start, start + 1]);
              start += 1;
              if (chr === "\n") {
                stripSpace();
                indentation = "";
                tagIndex = 0;
                lineHasNonSpace = false;
              }
            }
          }
          if (!scanner.scan(openingTagRe))
            break;
          hasTag = true;
          type = scanner.scan(tagRe) || "name";
          scanner.scan(whiteRe);
          if (type === "=") {
            value = scanner.scanUntil(equalsRe);
            scanner.scan(equalsRe);
            scanner.scanUntil(closingTagRe);
          } else if (type === "{") {
            value = scanner.scanUntil(closingCurlyRe);
            scanner.scan(curlyRe);
            scanner.scanUntil(closingTagRe);
            type = "&";
          } else {
            value = scanner.scanUntil(closingTagRe);
          }
          if (!scanner.scan(closingTagRe))
            throw new Error("Unclosed tag at " + scanner.pos);
          if (type == ">") {
            token = [type, value, start, scanner.pos, indentation, tagIndex, lineHasNonSpace];
          } else {
            token = [type, value, start, scanner.pos];
          }
          tagIndex++;
          tokens.push(token);
          if (type === "#" || type === "^") {
            sections.push(token);
          } else if (type === "/") {
            openSection = sections.pop();
            if (!openSection)
              throw new Error('Unopened section "' + value + '" at ' + start);
            if (openSection[1] !== value)
              throw new Error('Unclosed section "' + openSection[1] + '" at ' + start);
          } else if (type === "name" || type === "{" || type === "&") {
            nonSpace = true;
          } else if (type === "=") {
            compileTags(value);
          }
        }
        stripSpace();
        openSection = sections.pop();
        if (openSection)
          throw new Error('Unclosed section "' + openSection[1] + '" at ' + scanner.pos);
        return nestTokens(squashTokens(tokens));
      }
      function squashTokens(tokens) {
        var squashedTokens = [];
        var token, lastToken;
        for (var i = 0, numTokens = tokens.length; i < numTokens; ++i) {
          token = tokens[i];
          if (token) {
            if (token[0] === "text" && lastToken && lastToken[0] === "text") {
              lastToken[1] += token[1];
              lastToken[3] = token[3];
            } else {
              squashedTokens.push(token);
              lastToken = token;
            }
          }
        }
        return squashedTokens;
      }
      function nestTokens(tokens) {
        var nestedTokens = [];
        var collector = nestedTokens;
        var sections = [];
        var token, section;
        for (var i = 0, numTokens = tokens.length; i < numTokens; ++i) {
          token = tokens[i];
          switch (token[0]) {
            case "#":
            case "^":
              collector.push(token);
              sections.push(token);
              collector = token[4] = [];
              break;
            case "/":
              section = sections.pop();
              section[5] = token[2];
              collector = sections.length > 0 ? sections[sections.length - 1][4] : nestedTokens;
              break;
            default:
              collector.push(token);
          }
        }
        return nestedTokens;
      }
      function Scanner(string) {
        this.string = string;
        this.tail = string;
        this.pos = 0;
      }
      Scanner.prototype.eos = function eos() {
        return this.tail === "";
      };
      Scanner.prototype.scan = function scan(re) {
        var match = this.tail.match(re);
        if (!match || match.index !== 0)
          return "";
        var string = match[0];
        this.tail = this.tail.substring(string.length);
        this.pos += string.length;
        return string;
      };
      Scanner.prototype.scanUntil = function scanUntil(re) {
        var index = this.tail.search(re), match;
        switch (index) {
          case -1:
            match = this.tail;
            this.tail = "";
            break;
          case 0:
            match = "";
            break;
          default:
            match = this.tail.substring(0, index);
            this.tail = this.tail.substring(index);
        }
        this.pos += match.length;
        return match;
      };
      function Context(view, parentContext) {
        this.view = view;
        this.cache = { ".": this.view };
        this.parent = parentContext;
      }
      Context.prototype.push = function push(view) {
        return new Context(view, this);
      };
      Context.prototype.lookup = function lookup(name) {
        var cache = this.cache;
        var value;
        if (cache.hasOwnProperty(name)) {
          value = cache[name];
        } else {
          var context = this, intermediateValue, names, index, lookupHit = false;
          while (context) {
            if (name.indexOf(".") > 0) {
              intermediateValue = context.view;
              names = name.split(".");
              index = 0;
              while (intermediateValue != null && index < names.length) {
                if (index === names.length - 1)
                  lookupHit = hasProperty(intermediateValue, names[index]) || primitiveHasOwnProperty(intermediateValue, names[index]);
                intermediateValue = intermediateValue[names[index++]];
              }
            } else {
              intermediateValue = context.view[name];
              lookupHit = hasProperty(context.view, name);
            }
            if (lookupHit) {
              value = intermediateValue;
              break;
            }
            context = context.parent;
          }
          cache[name] = value;
        }
        if (isFunction(value))
          value = value.call(this.view);
        return value;
      };
      function Writer() {
        this.templateCache = {
          _cache: {},
          set: function set(key, value) {
            this._cache[key] = value;
          },
          get: function get(key) {
            return this._cache[key];
          },
          clear: function clear() {
            this._cache = {};
          }
        };
      }
      Writer.prototype.clearCache = function clearCache() {
        if (typeof this.templateCache !== "undefined") {
          this.templateCache.clear();
        }
      };
      Writer.prototype.parse = function parse(template, tags) {
        var cache = this.templateCache;
        var cacheKey = template + ":" + (tags || mustache.tags).join(":");
        var isCacheEnabled = typeof cache !== "undefined";
        var tokens = isCacheEnabled ? cache.get(cacheKey) : void 0;
        if (tokens == void 0) {
          tokens = parseTemplate(template, tags);
          isCacheEnabled && cache.set(cacheKey, tokens);
        }
        return tokens;
      };
      Writer.prototype.render = function render(template, view, partials, config) {
        var tags = this.getConfigTags(config);
        var tokens = this.parse(template, tags);
        var context = view instanceof Context ? view : new Context(view, void 0);
        return this.renderTokens(tokens, context, partials, template, config);
      };
      Writer.prototype.renderTokens = function renderTokens(tokens, context, partials, originalTemplate, config) {
        var buffer = "";
        var token, symbol, value;
        for (var i = 0, numTokens = tokens.length; i < numTokens; ++i) {
          value = void 0;
          token = tokens[i];
          symbol = token[0];
          if (symbol === "#")
            value = this.renderSection(token, context, partials, originalTemplate, config);
          else if (symbol === "^")
            value = this.renderInverted(token, context, partials, originalTemplate, config);
          else if (symbol === ">")
            value = this.renderPartial(token, context, partials, config);
          else if (symbol === "&")
            value = this.unescapedValue(token, context);
          else if (symbol === "name")
            value = this.escapedValue(token, context, config);
          else if (symbol === "text")
            value = this.rawValue(token);
          if (value !== void 0)
            buffer += value;
        }
        return buffer;
      };
      Writer.prototype.renderSection = function renderSection(token, context, partials, originalTemplate, config) {
        var self2 = this;
        var buffer = "";
        var value = context.lookup(token[1]);
        function subRender(template) {
          return self2.render(template, context, partials, config);
        }
        if (!value)
          return;
        if (isArray(value)) {
          for (var j = 0, valueLength = value.length; j < valueLength; ++j) {
            buffer += this.renderTokens(token[4], context.push(value[j]), partials, originalTemplate, config);
          }
        } else if (typeof value === "object" || typeof value === "string" || typeof value === "number") {
          buffer += this.renderTokens(token[4], context.push(value), partials, originalTemplate, config);
        } else if (isFunction(value)) {
          if (typeof originalTemplate !== "string")
            throw new Error("Cannot use higher-order sections without the original template");
          value = value.call(context.view, originalTemplate.slice(token[3], token[5]), subRender);
          if (value != null)
            buffer += value;
        } else {
          buffer += this.renderTokens(token[4], context, partials, originalTemplate, config);
        }
        return buffer;
      };
      Writer.prototype.renderInverted = function renderInverted(token, context, partials, originalTemplate, config) {
        var value = context.lookup(token[1]);
        if (!value || isArray(value) && value.length === 0)
          return this.renderTokens(token[4], context, partials, originalTemplate, config);
      };
      Writer.prototype.indentPartial = function indentPartial(partial, indentation, lineHasNonSpace) {
        var filteredIndentation = indentation.replace(/[^ \t]/g, "");
        var partialByNl = partial.split("\n");
        for (var i = 0; i < partialByNl.length; i++) {
          if (partialByNl[i].length && (i > 0 || !lineHasNonSpace)) {
            partialByNl[i] = filteredIndentation + partialByNl[i];
          }
        }
        return partialByNl.join("\n");
      };
      Writer.prototype.renderPartial = function renderPartial(token, context, partials, config) {
        if (!partials)
          return;
        var tags = this.getConfigTags(config);
        var value = isFunction(partials) ? partials(token[1]) : partials[token[1]];
        if (value != null) {
          var lineHasNonSpace = token[6];
          var tagIndex = token[5];
          var indentation = token[4];
          var indentedValue = value;
          if (tagIndex == 0 && indentation) {
            indentedValue = this.indentPartial(value, indentation, lineHasNonSpace);
          }
          var tokens = this.parse(indentedValue, tags);
          return this.renderTokens(tokens, context, partials, indentedValue, config);
        }
      };
      Writer.prototype.unescapedValue = function unescapedValue(token, context) {
        var value = context.lookup(token[1]);
        if (value != null)
          return value;
      };
      Writer.prototype.escapedValue = function escapedValue(token, context, config) {
        var escape = this.getConfigEscape(config) || mustache.escape;
        var value = context.lookup(token[1]);
        if (value != null)
          return typeof value === "number" && escape === mustache.escape ? String(value) : escape(value);
      };
      Writer.prototype.rawValue = function rawValue(token) {
        return token[1];
      };
      Writer.prototype.getConfigTags = function getConfigTags(config) {
        if (isArray(config)) {
          return config;
        } else if (config && typeof config === "object") {
          return config.tags;
        } else {
          return void 0;
        }
      };
      Writer.prototype.getConfigEscape = function getConfigEscape(config) {
        if (config && typeof config === "object" && !isArray(config)) {
          return config.escape;
        } else {
          return void 0;
        }
      };
      var mustache = {
        name: "mustache.js",
        version: "4.2.0",
        tags: ["{{", "}}"],
        clearCache: void 0,
        escape: void 0,
        parse: void 0,
        render: void 0,
        Scanner: void 0,
        Context: void 0,
        Writer: void 0,
        set templateCache(cache) {
          defaultWriter.templateCache = cache;
        },
        get templateCache() {
          return defaultWriter.templateCache;
        }
      };
      var defaultWriter = new Writer();
      mustache.clearCache = function clearCache() {
        return defaultWriter.clearCache();
      };
      mustache.parse = function parse(template, tags) {
        return defaultWriter.parse(template, tags);
      };
      mustache.render = function render(template, view, partials, config) {
        if (typeof template !== "string") {
          throw new TypeError('Invalid template! Template should be a "string" but "' + typeStr(template) + '" was given as the first argument for mustache#render(template, view, partials)');
        }
        return defaultWriter.render(template, view, partials, config);
      };
      mustache.escape = escapeHtml;
      mustache.Scanner = Scanner;
      mustache.Context = Context;
      mustache.Writer = Writer;
      return mustache;
    });
  }
});

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => IMDb
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/csvParser.ts
var import_obsidian = require("obsidian");

// src/model/imdbCsv.ts
var CsvHeader = /* @__PURE__ */ ((CsvHeader2) => {
  CsvHeader2["IMDbId"] = "Const";
  CsvHeader2["Description"] = "Description";
  CsvHeader2["Title"] = "Title";
  CsvHeader2["IMDbURL"] = "URL";
  CsvHeader2["Type"] = "Title Type";
  CsvHeader2["IMDbRating"] = "IMDb Rating";
  CsvHeader2["Runtime"] = "Runtime (mins)";
  CsvHeader2["Year"] = "Year";
  CsvHeader2["Genres"] = "Genres";
  CsvHeader2["Votes"] = "Num Votes";
  CsvHeader2["Release"] = "Release Date";
  CsvHeader2["Directors"] = "Directors";
  CsvHeader2["YourRating"] = "Your Rating";
  return CsvHeader2;
})(CsvHeader || {});
var DEFAULT_IMDB_CSV_ITEM = {
  ["Const" /* IMDbId */]: "",
  ["Description" /* Description */]: "",
  ["Title" /* Title */]: "",
  ["URL" /* IMDbURL */]: "",
  ["Title Type" /* Type */]: "",
  ["IMDb Rating" /* IMDbRating */]: "",
  ["Runtime (mins)" /* Runtime */]: "",
  ["Year" /* Year */]: "",
  ["Genres" /* Genres */]: "",
  ["Num Votes" /* Votes */]: "",
  ["Release Date" /* Release */]: "",
  ["Directors" /* Directors */]: "",
  ["Your Rating" /* YourRating */]: ""
};

// src/csvParser.ts
var getIMDbCsvItems = (csv) => {
  const lines = csv.split("\n").map((l) => l.match(new RegExp('(?:[^",]+|"[^"]*")+|^(?=,)|(?<=,)', "g"))).filter((l) => l);
  const headers = lines.shift();
  const output = lines.map((l) => {
    const obj = {};
    headers.map((h, i) => obj[headers[i]] = l[i]);
    const item = Object.assign({}, DEFAULT_IMDB_CSV_ITEM, obj);
    if (!item) {
      throw Error(`Unable to map csv line item ${l} to headers ${Object.values(CsvHeader)}`);
    }
    return item;
  });
  return output;
};
var retrieveIMDbCsvItems = (exportListUrl) => __async(void 0, null, function* () {
  const res = yield (0, import_obsidian.requestUrl)({
    url: exportListUrl,
    headers: { "Content-Type": "text/csv" },
    method: "GET"
  });
  return getIMDbCsvItems(res.text);
});

// src/MustacheContent.ts
var Mustache = require_mustache();
var MustacheContent = class {
  constructor(currentBody, item) {
    this.currentBody = currentBody;
    this.item = item;
  }
  getBody() {
    return Mustache.render(this.currentBody, this.item);
  }
};

// src/IMDbItem.ts
var import_obsidian2 = require("obsidian");
var trimQuote = (s) => {
  return s.replace(/^"|"$/g, "");
};
var IMDbItem = class {
  constructor(plugin, imdbList, csvItem, omdbJson) {
    this.plugin = plugin;
    this.imdbList = imdbList;
    this.initFrom(csvItem, omdbJson);
  }
  initFrom(csvItem, omdbJson) {
    var _a, _b, _c, _d;
    this.description = (_a = omdbJson == null ? void 0 : omdbJson.Plot) != null ? _a : csvItem["Description" /* Description */];
    this.title = (_b = omdbJson == null ? void 0 : omdbJson.Title) != null ? _b : csvItem["Title" /* Title */];
    this.poster = (_c = omdbJson == null ? void 0 : omdbJson.Poster) != null ? _c : "";
    this.cast = (_d = omdbJson == null ? void 0 : omdbJson.Actors) != null ? _d : "";
    this.writers = omdbJson == null ? void 0 : omdbJson.Writer.split(",").map((w) => w.trim());
    this.id = csvItem["Const" /* IMDbId */];
    this.imdbUrl = csvItem["URL" /* IMDbURL */];
    this.type = csvItem["Title Type" /* Type */];
    this.imdbRating = parseInt(csvItem["IMDb Rating" /* IMDbRating */]) || void 0;
    this.runtimeMin = parseInt(csvItem["Runtime (mins)" /* Runtime */]) || void 0;
    this.year = parseInt(csvItem["Year" /* Year */]) || void 0;
    this.genres = trimQuote(csvItem["Genres" /* Genres */]).split(",").map((g) => g.trim());
    this.votes = parseInt(csvItem["Num Votes" /* Votes */]) || void 0;
    this.releaseDate = csvItem["Release Date" /* Release */];
    this.directors = trimQuote(csvItem["Directors" /* Directors */]).split(",").map((g) => g.trim());
    this.yourRating = parseInt(csvItem["Your Rating" /* YourRating */]) || void 0;
  }
  getContent(template) {
    return this.getMustacheContent(template);
  }
  getMustacheContent(content) {
    return new MustacheContent(content, this).getBody();
  }
  createFile(path) {
    return __async(this, null, function* () {
      const fileName = this.getMustacheContent(this.plugin.settings.fileName);
      const fullName = `${path}${fileName}.md`;
      try {
        const fs = this.plugin.app.vault.adapter;
        const fileAlreadyExists = yield fs.exists(fullName);
        if (fileAlreadyExists && !this.plugin.settings.overwrite) {
          console.log("file already exists");
          return;
        }
        const fileTemplate = this.plugin.settings.fileTemplatePath;
        const template = yield fs.read(fileTemplate);
        const content = this.getContent(template);
        if (content) {
          yield fs.write(fullName, content);
        }
      } catch (error) {
        console.error(`Error writing ${fullName}`, error);
        new import_obsidian2.Notice(`\u26A0\uFE0F Error creating file for imdb item: ${this.title}. See developer console for detail`, 5e3);
      }
    });
  }
};

// src/IMDbList.ts
var import_obsidian3 = require("obsidian");
var OMDB_API_URL = "https://www.omdbapi.com/";
var IMDbList = class {
  constructor(plugin, listUrl, folderpath, listName) {
    this.plugin = plugin;
    this.listName = listName;
    this.items = [];
    this.path = `${folderpath}/`;
    this.exportListDownloadUrl = listUrl.charAt(listUrl.length - 1) == "/" ? `${listUrl}export` : `${listUrl}/export`;
  }
  appendIMDbItem(item) {
    this.items.push(item);
  }
  getItems() {
    return this.items;
  }
  createFolder() {
    return __async(this, null, function* () {
      try {
        yield this.plugin.app.vault.createFolder(this.path);
      } catch (e) {
        if (e.message.includes("already exists"))
          return;
        console.warn(e);
      }
    });
  }
  fetchIMDbItems() {
    return __async(this, null, function* () {
      try {
        const items = yield retrieveIMDbCsvItems(this.exportListDownloadUrl);
        yield Promise.all(items.map((_item) => __async(this, null, function* () {
          const omdbData = yield this.getOmdbData(_item["Const" /* IMDbId */]);
          const imdbItem = new IMDbItem(this.plugin, this, _item, omdbData);
          this.appendIMDbItem(imdbItem);
        })));
      } catch (e) {
        console.warn("Unable to fetch imdb csv. Error:", e);
        new import_obsidian3.Notice("\u26A0\uFE0F Failed to fetch IMDb CSV. See Developer console for more detail");
      }
    });
  }
  createIMDbItemsFiles() {
    return __async(this, null, function* () {
      yield Promise.all([
        this.items.map((_item) => {
          return _item.createFile(this.path);
        })
      ]);
      this.createNotice();
    });
  }
  createNotice() {
    const syncCount = this.items.length;
    if (syncCount === 0) {
      return;
    }
    const firstTitle = this.items[0].title;
    let noticeMsg = "";
    noticeMsg = `\u{1F680} ${this.listName} sync complete! ${this.items.length} items, including ${firstTitle}, are synced from IMDb!`;
    new import_obsidian3.Notice(noticeMsg, 5e3);
  }
  getOmdbData(id) {
    return __async(this, null, function* () {
      try {
        const finalURL = new URL(OMDB_API_URL);
        finalURL.searchParams.append("i", id);
        finalURL.searchParams.append("apikey", this.plugin.settings.omdbApiKey);
        const res = yield (0, import_obsidian3.requestUrl)({
          url: finalURL.toString(),
          headers: {
            "Content-Type": "application/json"
          },
          method: "GET"
        });
        const omdbJson = res.json;
        if (omdbJson.Response !== "True") {
          console.warn(`omdb returned invalid response for id=[${id}]. Response:`, res);
          return void 0;
        }
        return omdbJson;
      } catch (e) {
        console.warn(`Unable to get omdbData for imdbId=[${id}]`);
        return void 0;
      }
    });
  }
};

// src/Settings.ts
var import_obsidian6 = require("obsidian");

// src/FileSuggest.ts
var import_obsidian4 = require("obsidian");
var import_obsidian5 = require("obsidian");
var FileSuggest = class extends import_obsidian4.AbstractInputSuggest {
  constructor(inputEl, onSelectCb, app) {
    super(app, inputEl);
    this.inputEl = inputEl;
    this.onSelectCb = onSelectCb;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const files = [];
    const lowerCaseInputStr = inputStr.toLowerCase();
    abstractFiles.forEach((file) => {
      if (file instanceof import_obsidian5.TFile && file.extension === "md" && file.path.toLowerCase().contains(lowerCaseInputStr)) {
        files.push(file.path);
      }
    });
    return files;
  }
  renderSuggestion(filePath, el) {
    el.setText(filePath);
  }
  selectSuggestion(filePath, evt) {
    this.onSelectCb(filePath);
    this.inputEl.value = filePath;
    this.inputEl.blur();
    this.close();
  }
};
var FolderSuggest = class extends import_obsidian4.AbstractInputSuggest {
  constructor(inputEl, onSelectCb, app) {
    super(app, inputEl);
    this.inputEl = inputEl;
    this.onSelectCb = onSelectCb;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const folders = [];
    const lowerCaseInputStr = inputStr.toLowerCase();
    abstractFiles.forEach((folder) => {
      if (folder instanceof import_obsidian5.TFolder && folder.path.toLowerCase().contains(lowerCaseInputStr)) {
        folders.push(folder.path);
      }
    });
    return folders;
  }
  renderSuggestion(folderPath, el) {
    el.setText(folderPath);
  }
  selectSuggestion(folderPath, evt) {
    this.onSelectCb(folderPath);
    this.inputEl.value = folderPath;
    this.inputEl.blur();
    this.close();
  }
};

// src/Settings.ts
var Settings = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("p", {
      text: "Sync your favorite movies, shows, or games into your obsidian vault from IMDb. The lists you export must be public for this plugin to download and parse"
    });
    new import_obsidian6.Setting(containerEl).setName("omdb Api key").setDesc(createFragment((fragment) => {
      fragment.append("OMDb is queried to fetch additional information such as Posters, Writers, etc. You can create an API key at ", fragment.createEl("a", {
        text: "https://www.omdbapi.com/",
        href: "https://www.omdbapi.com/"
      }), fragment.createEl("br"), "This can be omitted if you only need the information found in IMDb export CSVs");
    })).addText((text) => text.setValue(this.plugin.settings.omdbApiKey).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.omdbApiKey = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian6.Setting(containerEl).setName("Lists").setHeading();
    new import_obsidian6.Setting(containerEl).setName("File name").setDesc("For the IMDb items to be imported").setTooltip("You don't need to add '.md' to the filename").addText((text) => {
      text.setPlaceholder("{{{title}}}");
      text.setValue(this.plugin.settings.fileName);
      text.onChange((value) => __async(this, null, function* () {
        this.plugin.settings.fileName = value;
        yield this.plugin.saveSettings();
      }));
    });
    new import_obsidian6.Setting(containerEl).setName("File template path").setDesc("File template for creating the IMDb items").addSearch((search) => {
      new FileSuggest(search.inputEl, (value) => __async(this, null, function* () {
        this.plugin.settings.fileTemplatePath = value;
        yield this.plugin.saveSettings();
      }), this.app);
      search.setPlaceholder("").setValue(this.plugin.settings.fileTemplatePath);
    });
    new import_obsidian6.Setting(containerEl).setName("Overwrite").setDesc("Whether to overwrite existing notes. Modifications to notes will be lost, but changes from IMDb will now be picked up.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.overwrite);
      toggle.onChange((newValue) => {
        this.plugin.settings.overwrite = newValue;
        this.plugin.saveSettings();
      });
    });
    new import_obsidian6.Setting(containerEl).setName("Export lists").setDesc("Add IMDb list to export").addButton((button) => button.onClick(() => __async(this, null, function* () {
      const currentExportSettings = this.plugin.settings.exportSettings;
      this.plugin.settings.exportSettings = currentExportSettings.concat({
        listName: "",
        targetFolderPath: "",
        imdbListUrl: ""
      });
      yield this.plugin.saveSettings();
      this.display();
    })).setButtonText("Add List"));
    this.displayListContainers(containerEl);
  }
  displayListContainers(containerEl) {
    this.plugin.settings.exportSettings.forEach((setting, i) => {
      const listHeader = containerEl.createEl("div", { cls: "callout" });
      new import_obsidian6.Setting(listHeader).setName("List").setHeading();
      const btn = listHeader.createEl("button", {
        cls: "close-button",
        type: "button"
      });
      btn.createEl("span", { text: "x" });
      btn.addEventListener("click", () => __async(this, null, function* () {
        this.plugin.settings.exportSettings.splice(i, 1);
        yield this.plugin.saveSettings();
        this.display();
      }));
      new import_obsidian6.Setting(containerEl).setName("List name").setDesc("Friendly name of your list").addText((text) => {
        text.setPlaceholder("My Watch List").setValue(setting.listName).onChange((newName) => __async(this, null, function* () {
          this.plugin.settings.exportSettings[i].listName = newName;
          yield this.plugin.saveSettings();
        }));
      });
      new import_obsidian6.Setting(containerEl).setName("Target folder").setDesc("If you leave this empty, the items will be created in the root directory.").addSearch((search) => {
        new FolderSuggest(search.inputEl, (value) => __async(this, null, function* () {
          setting.targetFolderPath = value;
          yield this.plugin.saveSettings();
        }), this.app);
        search.setPlaceholder("").setValue(setting.targetFolderPath);
      });
      new import_obsidian6.Setting(containerEl).setName("IMDb list URL").setDesc("List you'd like to export from").addText((text) => {
        text.setPlaceholder("https://www.imdb.com/list/ls523701947").setValue(setting.imdbListUrl).onChange((newUrl) => __async(this, null, function* () {
          this.plugin.settings.exportSettings[i].imdbListUrl = newUrl;
          yield this.plugin.saveSettings();
        }));
      });
    });
  }
};

// src/model/settings.ts
var DEFAULT_SETTINGS = {
  omdbApiKey: "",
  exportSettings: [],
  fileName: "{{{title}}}",
  fileTemplatePath: "",
  overwrite: false
};

// main.ts
var IMDb = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.scheduleInterval = null;
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.addRibbonIcon("star", "Sync", (evt) => {
        this.updateLibrary();
      });
      this.addCommand({
        id: "sync",
        name: "Sync",
        callback: () => {
          this.updateLibrary();
        }
      });
      this.addSettingTab(new Settings(this.app, this));
    });
  }
  updateLibrary() {
    if (!this.settings.fileTemplatePath) {
      new import_obsidian7.Notice(`\u26A0\uFE0F Please specify file template`, 5e3);
      return;
    }
    this.settings.exportSettings.forEach((exportSetting) => __async(this, null, function* () {
      let { targetFolderPath, imdbListUrl, listName } = exportSetting;
      if (!imdbListUrl) {
        new import_obsidian7.Notice(`\u26A0\uFE0F Please specify list url for list name: ${listName}`, 5e3);
        return;
      }
      const list = new IMDbList(this, imdbListUrl, targetFolderPath, listName);
      new import_obsidian7.Notice(`Beginning sync for ${listName}`, 5e3);
      yield list.createFolder();
      yield list.fetchIMDbItems();
      yield list.createIMDbItemsFiles();
    }));
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
/*!
 * mustache.js - Logic-less {{mustache}} templates with JavaScript
 * http://github.com/janl/mustache.js
 */
