/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FocusTrackerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/FocusTracker.ts
var import_obsidian4 = require("obsidian");

// src/services/FileService.ts
var import_obsidian = require("obsidian");
var import_obsidian2 = require("obsidian");

// src/constants.ts
var DEFAULT_MAPS = {
  ratings: {
    colors1: {
      symbols: ["\u{1F534}", "\u{1F7E0}", "\u{1F7E1}", "\u{1F7E2}", "\u{1F535}"],
      descriptions: ["Poor", "Fair", "Good", "Very Good", "Excellent"]
    },
    digitsOpen: {
      symbols: ["\u2780", "\u2781", "\u2782", "\u2783", "\u2784", "\u2785", "\u2786", "\u2787", "\u2788", "\u2789"],
      descriptions: Array.from({ length: 10 }, (_, i) => `Level ${i + 1}`)
    },
    digitsFilled: {
      symbols: ["\u278A", "\u278B", "\u278C", "\u278D", "\u278E", "\u278F", "\u2790", "\u2791", "\u2792", "\u2793"],
      descriptions: Array.from({ length: 10 }, (_, i) => `Level ${i + 1}`)
    },
    moonPhases: {
      symbols: ["\u{1F311}", "\u{1F312}", "\u{1F313}", "\u{1F314}", "\u{1F315}"],
      descriptions: ["New", "Waxing Crescent", "First Quarter", "Waxing Gibbous", "Full"]
    }
  },
  flags: {
    default: {
      symbols: [
        "\u{1F680}",
        "\u{1F3AF}",
        "\u{1F4C5}",
        "\u23F3",
        "\u{1F3C1}",
        "\u{1F4C8}",
        "\u2705",
        "\u{1F402}",
        "\u{1F4C9}",
        "\u26A0\uFE0F",
        "\u{1F6A7}",
        "\u23E9",
        "\u274E",
        "\u26D4",
        "\u{1F4E6}",
        "\u274C"
      ],
      keys: [
        "goal: aspirational",
        "goal: committed",
        "due",
        "scheduled",
        "start",
        "progress",
        "done",
        "yak-shaving",
        "regress",
        "attention",
        "incomplete",
        "forwarded",
        "canceled",
        "blocked",
        "stowed",
        "unsuccessful"
      ]
    },
    activity: {
      symbols: [
        "\u{1F3EF}",
        "\u{1F52E}",
        "\u{1F4DC}",
        "\u{1F531}",
        "\u{1F6E0}\uFE0F",
        "\u{1F6DE}"
      ],
      keys: [
        "administration",
        "informatics",
        "literature",
        "manuscripting",
        "system",
        "other"
      ]
    },
    academic: {
      symbols: ["\u{1F4DA}", "\u270D\uFE0F", "\u{1F4DD}", "\u{1F52C}", "\u{1F4D6}", "\u2753", "\u{1F4CC}", "\u2B50", "\u{1F393}"],
      keys: [
        "read",
        "write",
        "take notes",
        "research",
        "review",
        "question",
        "important",
        "insight",
        "milestone"
      ]
    },
    project: {
      symbols: ["\u{1F4A1}", "\u{1F4CB}", "\u{1F465}", "\u{1F4CA}", "\u{1F504}", "\u26A1", "\u{1F3A8}", "\u{1F50D}", "\u{1F4AA}"],
      keys: [
        "idea",
        "planning",
        "collaboration",
        "review metrics",
        "in progress",
        "high priority",
        "design needed",
        "needs research",
        "effort required"
      ]
    },
    health: {
      symbols: ["\u{1F3C3}", "\u{1F957}", "\u{1F4AA}", "\u{1F634}", "\u{1F48A}", "\u{1F9D8}", "\u{1F3AF}", "\u2764\uFE0F", "\u{1FA7A}"],
      keys: [
        "exercise",
        "nutrition",
        "strength",
        "sleep",
        "medication",
        "mindfulness",
        "goal",
        "wellbeing",
        "checkup"
      ]
    },
    writing: {
      symbols: ["\u270D\uFE0F", "\u{1F4DD}", "\u{1F50D}", "\u{1F4DA}", "\u2702\uFE0F", "\u{1F3AD}", "\u{1F3A8}", "\u{1F465}", "\u{1F4D6}"],
      keys: [
        "draft",
        "edit",
        "research",
        "reference",
        "cut/revise",
        "character work",
        "creative",
        "feedback",
        "review"
      ]
    },
    coding: {
      symbols: ["\u{1F4A1}", "\u{1F9E9}", "\u{1F4BB}", "\u{1F58B}\uFE0F", "\u{1F41B}", "\u{1F50D}", "\u{1F680}", "\u{1F6E0}\uFE0F", "\u2705"],
      keys: [
        "concept",
        "planning/problem breakdown",
        "coding",
        "documentation",
        "debugging",
        "code review",
        "deploy",
        "maintenance",
        "completed"
      ]
    },
    project_management: {
      symbols: ["\u{1F4A1}", "\u{1F4C5}", "\u{1F91D}", "\u{1F4C8}", "\u2696\uFE0F", "\u{1F6A9}", "\u{1F504}", "\u{1F4CB}", "\u2705"],
      keys: [
        "project initiation",
        "scheduling",
        "team coordination",
        "tracking progress",
        "resource balancing",
        "milestone",
        "project updates",
        "final review",
        "project completion"
      ]
    },
    scientific_project_management: {
      symbols: ["\u{1F4A1}", "\u{1F52C}", "\u{1F9EA}", "\u{1F4CA}", "\u{1F4C8}", "\u{1F504}", "\u{1F4C5}", "\u{1F4C9}", "\u2705"],
      keys: [
        "project concept",
        "experimentation",
        "data collection",
        "data analysis",
        "modeling",
        "status updates",
        "timeline management",
        "reporting",
        "completion"
      ]
    },
    engineering_project_management: {
      symbols: ["\u{1F4A1}", "\u{1F4D0}", "\u2699\uFE0F", "\u{1F4CA}", "\u{1F4CF}", "\u{1F6A7}", "\u{1F50D}", "\u{1F4CB}", "\u2705"],
      keys: [
        "idea",
        "design phase",
        "engineering setup",
        "metrics definition",
        "specifications",
        "construction",
        "inspection",
        "documentation",
        "finished"
      ]
    },
    flight_planning: {
      symbols: ["\u{1F4A1}", "\u{1F5FA}\uFE0F", "\u{1F4CF}", "\u{1F4C6}", "\u{1F4CD}", "\u23F0", "\u{1F6EB}", "\u{1F6EC}", "\u2705"],
      keys: [
        "flight concept",
        "route mapping",
        "distance planning",
        "scheduling",
        "waypoints",
        "time management",
        "takeoff",
        "landing",
        "flight completed"
      ]
    },
    scientific_manuscript_writing: {
      symbols: ["\u{1F4A1}", "\u{1F4DA}", "\u{1F50D}", "\u270D\uFE0F", "\u{1F4C8}", "\u{1F4DD}", "\u2702\uFE0F", "\u{1F4D6}", "\u2705"],
      keys: [
        "idea formulation",
        "literature review",
        "research",
        "writing",
        "data visualization",
        "drafting",
        "revision",
        "peer review",
        "publication"
      ]
    }
  }
};
var DEFAULT_CONFIG = {
  daysPast: 15,
  daysFuture: 7,
  ratingMap: "colors1",
  flagMap: "default"
};
var MIN_DAYS_PAST = 7;
var MIN_DAYS_FUTURE = 7;
var OUT_OF_BOUNDS = "\u2757";
var PLUGIN_NAME = "Focus Tracker";

// src/utils/formatting.ts
function formatFrontmatterValue(value) {
  if (Array.isArray(value)) {
    return value.join(" \u2022 ");
  }
  if (value === null || value === void 0) {
    return "";
  }
  return String(value);
}
function normalizeLogs(source) {
  const result = {};
  Object.keys(source).forEach((date) => {
    const value = source[date];
    if (value === null || value === void 0 || value === "") {
      result[date] = { rating: 0 };
    } else if (typeof value === "object" && "rating" in value) {
      result[date] = value;
    } else if (typeof value === "number") {
      result[date] = { rating: value };
    } else if (typeof value === "string") {
      const numValue = Number(value);
      if (isNaN(numValue)) {
        result[date] = { rating: 0, remarks: value };
      } else {
        result[date] = { rating: numValue };
      }
    }
  });
  return result;
}

// src/utils/strings.ts
function kebabToCamel(s) {
  return s.replace(/(-\w)/g, (m) => m[1].toUpperCase());
}
function pathToId(path) {
  return path.replace(/\//g, "_").replace(/\./g, "__").replace(/ /g, "___");
}
function generateUniqueId() {
  const timestamp = Date.now();
  const randomNum = Math.floor(Math.random() * 1e4);
  return `focustracker-${timestamp}-${randomNum}`;
}
function patternsToRegex(patterns) {
  return patterns.map((pattern) => {
    return new RegExp(".*" + pattern + ".*");
  });
}
function normalizeKeys(dictionary) {
  const normalizedDictionary = {};
  Object.keys(dictionary).forEach((key) => {
    normalizedDictionary[kebabToCamel(key)] = dictionary[key];
  });
  return normalizedDictionary;
}

// src/services/FileService.ts
var FileService = class {
  constructor(app) {
    this.app = app;
  }
  async getFrontmatter(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!file || !(file instanceof import_obsidian.TFile)) {
      new import_obsidian2.Notice(`${PLUGIN_NAME}: No file found for path: ${path}`);
      return {};
    }
    try {
      const content = await this.app.vault.read(file);
      const frontmatter = content.split("---")[1];
      if (!frontmatter) {
        return {};
      }
      return (0, import_obsidian.parseYaml)(frontmatter);
    } catch (error) {
      return {};
    }
  }
  async getFocusTargetLabel(path, titlePropertyNames) {
    var _a;
    let focusTargetLabel = ((_a = path.split("/").pop()) == null ? void 0 : _a.replace(".md", "")) || path;
    if ((titlePropertyNames == null ? void 0 : titlePropertyNames.length) > 0) {
      let frontmatter = await this.getFrontmatter(path) || {};
      titlePropertyNames.slice().reverse().forEach((propertyName) => {
        if (frontmatter[propertyName]) {
          focusTargetLabel = frontmatter[propertyName] || focusTargetLabel;
        }
      });
    }
    return focusTargetLabel;
  }
  async readFocusLogs(path, logPropertyName) {
    const frontmatter = await this.getFrontmatter(path);
    const fmLogs = frontmatter[logPropertyName] || {};
    return normalizeLogs(fmLogs);
  }
  loadFiles(config) {
    let pathPatterns = patternsToRegex(config.paths);
    let tagAnyPatterns = patternsToRegex(config.tags.map((s) => s.replace(/^#/, "")));
    let tagSetPatterns = patternsToRegex(config.tagSet.map((s) => s.replace(/^#/, "")));
    let excludeTagPatterns = patternsToRegex((config.excludeTags || []).map((s) => s.replace(/^#/, "")));
    let excludeTagSetPatterns = patternsToRegex((config.excludeTagSet || []).map((s) => s.replace(/^#/, "")));
    return this.app.vault.getMarkdownFiles().filter((file) => this.fileMatchesFilters(file, {
      pathPatterns,
      tagAnyPatterns,
      tagSetPatterns,
      excludeTagPatterns,
      excludeTagSetPatterns,
      properties: config.properties
    })).sort((a, b) => a.name.localeCompare(b.name));
  }
  fileMatchesFilters(file, filters) {
    let fileMetadata = this.getMetadata(file);
    let frontmatter = (fileMetadata == null ? void 0 : fileMetadata.frontmatter) || {};
    let fileTags = this.extractTags(fileMetadata);
    if (filters.pathPatterns.length > 0 && !filters.pathPatterns.some((rx) => rx.test(file.path))) {
      return false;
    }
    if (filters.tagAnyPatterns.length > 0 && !filters.tagAnyPatterns.some((rx) => fileTags.some((tag) => rx.test(tag)))) {
      return false;
    }
    if (filters.tagSetPatterns.length > 0 && !filters.tagSetPatterns.every((rx) => fileTags.some((tag) => rx.test(tag)))) {
      return false;
    }
    if (filters.excludeTagPatterns.length > 0 && filters.excludeTagPatterns.some((rx) => fileTags.some((tag) => rx.test(tag)))) {
      return false;
    }
    if (filters.excludeTagSetPatterns.length > 0 && filters.excludeTagSetPatterns.every((rx) => fileTags.some((tag) => rx.test(tag)))) {
      return false;
    }
    if (Object.keys(filters.properties).length > 0) {
      if (!frontmatter)
        return false;
      if (!Object.keys(filters.properties).some((key) => frontmatter[key] === filters.properties[key])) {
        return false;
      }
    }
    return true;
  }
  getMetadata(file) {
    return this.app.metadataCache.getFileCache(file) || null;
  }
  extractTags(metadata) {
    var _a;
    if (!metadata)
      return [];
    const tagSet = /* @__PURE__ */ new Set();
    if ((_a = metadata.frontmatter) == null ? void 0 : _a.tags) {
      const fmTags = metadata.frontmatter.tags;
      if (Array.isArray(fmTags)) {
        fmTags.forEach((tag) => {
          tagSet.add(typeof tag === "string" ? tag.replace(/^#/, "") : "");
        });
      } else if (typeof fmTags === "string") {
        fmTags.split(/[,\s]+/).forEach((tag) => {
          tagSet.add(tag.replace(/^#/, ""));
        });
      }
    }
    if (metadata.tags) {
      metadata.tags.forEach((tag) => {
        tagSet.add(tag.tag.replace(/^#/, ""));
      });
    }
    return Array.from(tagSet).filter((tag) => tag !== "");
  }
};

// src/services/SortingService.ts
var SortingService = class {
  constructor(fileService) {
    this.fileService = fileService;
  }
  async sortFiles(files, configuration) {
    let sortColumn = configuration.sortColumn;
    if (!sortColumn) {
      const prefixColumns = Object.values(configuration.prefixColumns);
      sortColumn = prefixColumns.length > 0 ? prefixColumns[0] : "track";
      configuration.sortColumn = sortColumn;
    }
    if (sortColumn === "track") {
      const fileLabels2 = await Promise.all(
        files.map(async (f) => {
          const label = await this.fileService.getFocusTargetLabel(f.path, configuration.titlePropertyNames);
          return [label, f, label.toLowerCase()];
        })
      );
      return this.sortFileLabels(fileLabels2, configuration.sortDescending);
    }
    const fileLabels = await Promise.all(
      files.map(async (f) => {
        const frontmatter = await this.fileService.getFrontmatter(f.path);
        const label = await this.fileService.getFocusTargetLabel(f.path, configuration.titlePropertyNames);
        const value = frontmatter[sortColumn];
        const sortValue = formatFrontmatterValue(value).toLowerCase();
        return [label, f, sortValue];
      })
    );
    return this.sortFileLabels(fileLabels, configuration.sortDescending);
  }
  sortFileLabels(fileLabels, sortDescending) {
    return fileLabels.sort(([labelA, fileA, valueA], [labelB, fileB, valueB]) => {
      const comparison = valueA.localeCompare(valueB);
      return sortDescending ? -comparison : comparison;
    }).map(([label, file]) => [label, file]);
  }
};

// src/utils/dates.ts
function getTodayDate() {
  const today = new Date();
  const year = today.getFullYear();
  const month = String(today.getMonth() + 1).padStart(2, "0");
  const day = String(today.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
function getLocalDateString(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
function getDayOfWeek(date) {
  const daysOfWeek = [
    "sunday",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday"
  ];
  return daysOfWeek[date.getDay()].toLowerCase();
}
function isSameDate(date1, date2) {
  return date1.getFullYear() === date2.getFullYear() && date1.getMonth() === date2.getMonth() && date1.getDate() === date2.getDate();
}

// src/components/FocusTrackerControls.ts
var FocusTrackerControls = class {
  constructor(app, onConfigChange) {
    this.app = app;
    this.onConfigChange = onConfigChange;
  }
  createControlSection(parent, label, initialValue, minValue, defaultValue, onChange) {
    const section = parent.createEl("div", {
      cls: "focus-tracker__control-section"
    });
    section.createEl("span", {
      text: label,
      cls: "focus-tracker__control-label"
    });
    const input = section.createEl("input", {
      type: "number",
      value: initialValue.toString(),
      cls: "focus-tracker__days-input"
    });
    input.setAttribute("min", minValue.toString());
    const decrementBtn = section.createEl("button", {
      text: "-",
      cls: "focus-tracker__btn-decrement"
    });
    const incrementBtn = section.createEl("button", {
      text: "+",
      cls: "focus-tracker__btn-increment"
    });
    input.onchange = () => {
      const newValue = Math.max(minValue, parseInt(input.value));
      input.value = newValue.toString();
      onChange(newValue);
    };
    decrementBtn.onclick = () => {
      if (parseInt(input.value) > minValue) {
        input.value = (parseInt(input.value) - 1).toString();
        onChange(parseInt(input.value));
      }
    };
    incrementBtn.onclick = () => {
      input.value = (parseInt(input.value) + 1).toString();
      onChange(parseInt(input.value));
    };
    return section;
  }
  renderControls(parent, config) {
    this.createControlSection(
      parent,
      "Days Past:",
      config.daysInPast,
      MIN_DAYS_PAST,
      DEFAULT_CONFIG.daysPast,
      (value) => {
        config.daysInPast = value;
        this.onConfigChange();
      }
    );
    const focalDateSection = parent.createEl("div", {
      cls: "focus-tracker__control-section"
    });
    focalDateSection.createEl("span", {
      text: "Focal Date:",
      cls: "focus-tracker__control-label"
    });
    const focalDateInput = focalDateSection.createEl("input", {
      type: "date",
      value: getLocalDateString(config.focalDate),
      cls: "focus-tracker__focal-date"
    });
    const dateControls = focalDateSection.createEl("div", {
      cls: "focus-tracker__date-controls"
    });
    this.createDateControls(dateControls, focalDateInput, config);
    this.createControlSection(
      parent,
      "Days Future:",
      config.daysInFuture,
      MIN_DAYS_FUTURE,
      DEFAULT_CONFIG.daysFuture,
      (value) => {
        config.daysInFuture = value;
        this.onConfigChange();
      }
    );
  }
  createDateControls(container, dateInput, config) {
    const decrementDateBtn = container.createEl("button", {
      text: "\u25C0",
      cls: "focus-tracker__btn-date"
    });
    const todayBtn = container.createEl("button", {
      text: "\u25CF",
      cls: "focus-tracker__btn-today"
    });
    const incrementDateBtn = container.createEl("button", {
      text: "\u25B6",
      cls: "focus-tracker__btn-date"
    });
    decrementDateBtn.onclick = () => {
      config.focalDate.setDate(config.focalDate.getDate() - 1);
      dateInput.value = config.focalDate.toISOString().split("T")[0];
      this.onConfigChange();
    };
    incrementDateBtn.onclick = () => {
      config.focalDate.setDate(config.focalDate.getDate() + 1);
      dateInput.value = config.focalDate.toISOString().split("T")[0];
      this.onConfigChange();
    };
    todayBtn.onclick = () => {
      config.focalDate = new Date();
      dateInput.value = config.focalDate.toISOString().split("T")[0];
      this.onConfigChange();
    };
    dateInput.onchange = () => {
      const [year, month, day] = dateInput.value.split("-").map(Number);
      config.focalDate = new Date(year, month - 1, day);
      this.onConfigChange();
    };
  }
};

// src/components/FocusTrackerHeader.ts
var FocusTrackerHeader = class {
  constructor(config, onSortingChange) {
    this.config = config;
    this.onSortingChange = onSortingChange;
  }
  renderTableHeader(parent) {
    const header = parent.createEl("div", {
      cls: "focus-tracker__header focus-tracker__row"
    });
    Object.entries(this.config.prefixColumns).forEach(([displayName, propertyName]) => {
      const headerCell = header.createEl("div", {
        cls: "focus-tracker__cell focus-tracker__cell--custom focus-tracker__cell--prefix",
        text: displayName
      });
      this.addSortingToHeader(headerCell, propertyName);
      this.addResizeHandle(headerCell);
    });
    const trackHeader = header.createEl("div", {
      cls: "focus-tracker__cell focus-tracker__cell--focus-target-label",
      text: "Track"
    });
    this.addSortingToHeader(trackHeader, "track");
    this.addResizeHandle(trackHeader);
    this.renderDateCells(header);
    Object.entries(this.config.postfixColumns).forEach(([displayName, propertyName]) => {
      const headerCell = header.createEl("div", {
        cls: "focus-tracker__cell focus-tracker__cell--custom focus-tracker__cell--postfix",
        text: displayName
      });
      this.addSortingToHeader(headerCell, propertyName);
      this.addResizeHandle(headerCell);
    });
  }
  renderDateCells(header) {
    const totalDays = this.config.daysInPast + this.config.daysInFuture + 1;
    let currentDate = new Date(this.config.focalDate);
    currentDate.setHours(0, 0, 0, 0);
    currentDate.setDate(currentDate.getDate() - this.config.daysInPast);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const focalDate = new Date(this.config.focalDate);
    focalDate.setHours(0, 0, 0, 0);
    for (let i = 0; i < totalDays; i++) {
      const day = currentDate.getDate().toString();
      const cellEl = header.createEl("div", {
        cls: `focus-tracker__cell focus-tracker__cell--${getDayOfWeek(currentDate)}`,
        text: day
      });
      if (isSameDate(currentDate, today)) {
        cellEl.addClass("focus-tracker__cell--today");
      }
      if (isSameDate(currentDate, focalDate)) {
        cellEl.addClass("focus-tracker__cell--focal-date");
      }
      currentDate.setDate(currentDate.getDate() + 1);
    }
  }
  addResizeHandle(cell) {
    const handle = cell.createEl("div", {
      cls: "focus-tracker__resize-handle"
    });
    let startX;
    let startWidth;
    const startResize = (e) => {
      startX = e.pageX;
      startWidth = cell.offsetWidth;
      document.addEventListener("mousemove", resize);
      document.addEventListener("mouseup", stopResize);
      document.body.style.cursor = "col-resize";
      e.preventDefault();
    };
    const resize = (e) => {
      const width = startWidth + (e.pageX - startX);
      cell.style.width = `${width}px`;
      cell.style.minWidth = `${width}px`;
    };
    const stopResize = () => {
      document.removeEventListener("mousemove", resize);
      document.removeEventListener("mouseup", stopResize);
      document.body.style.cursor = "";
    };
    handle.addEventListener("mousedown", startResize);
  }
  addSortingToHeader(headerCell, columnName) {
    headerCell.addClass("focus-tracker__cell--sortable");
    if (this.config.sortColumn === columnName) {
      headerCell.addClass("focus-tracker__cell--sorted");
      headerCell.addClass(
        this.config.sortDescending ? "focus-tracker__cell--sort-desc" : "focus-tracker__cell--sort-asc"
      );
    }
    headerCell.addEventListener("click", () => {
      if (this.config.sortColumn === columnName) {
        this.config.sortDescending = !this.config.sortDescending;
      } else {
        this.config.sortColumn = columnName;
        this.config.sortDescending = false;
      }
      this.onSortingChange();
    });
  }
};

// src/config/defaults.ts
var DEFAULT_CONFIGURATION = () => ({
  path: "",
  paths: [],
  properties: {},
  tags: [],
  tagSet: [],
  excludeTags: [],
  excludeTagSet: [],
  lastDisplayedDate: getTodayDate(),
  logPropertyName: "focus-logs",
  ratingSymbols: DEFAULT_MAPS.ratings[DEFAULT_CONFIG.ratingMap].symbols,
  flagSymbols: DEFAULT_MAPS.flags[DEFAULT_CONFIG.flagMap].symbols,
  flagKeys: DEFAULT_MAPS.flags[DEFAULT_CONFIG.flagMap].keys,
  titlePropertyNames: ["track-label", "focus-tracker-title", "title"],
  daysInPast: DEFAULT_CONFIG.daysPast,
  daysInFuture: DEFAULT_CONFIG.daysFuture,
  focalDate: new Date(),
  rootElement: void 0,
  focusTracksGoHere: void 0,
  prefixColumns: {},
  postfixColumns: {},
  sortColumn: "",
  sortDescending: false
});

// src/components/RemarksModal.ts
var import_obsidian3 = require("obsidian");
var RemarksModal = class extends import_obsidian3.Modal {
  constructor(app, initialValue, onSubmit) {
    super(app);
    this.result = initialValue;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: "Enter Remarks" });
    this.textArea = new import_obsidian3.TextAreaComponent(contentEl);
    this.textArea.setValue(this.result).onChange((value) => {
      this.result = value;
    });
    this.textArea.inputEl.classList.add("focus-tracker-remarks-input");
    this.textArea.inputEl.focus();
    const buttonContainer = contentEl.createEl("div", {
      cls: "focus-tracker-remarks-buttons"
    });
    buttonContainer.createEl("button", { text: "Cancel" }).onclick = () => {
      this.close();
    };
    const submitButton = buttonContainer.createEl("button", {
      cls: "mod-cta",
      text: "Submit"
    });
    submitButton.onclick = () => {
      this.onSubmit(this.result);
      this.close();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/FocusTracker.ts
var import_obsidian5 = require("obsidian");
var FocusTracker = class {
  constructor(src, el, ctx, app, settings) {
    this.app = app;
    this.settings = settings;
    this.id = generateUniqueId();
    this.fileService = new FileService(app);
    this.sortingService = new SortingService(this.fileService);
    this.configuration = this.loadConfiguration(src);
    this.controls = new FocusTrackerControls(app, () => this.refresh());
    this.header = new FocusTrackerHeader(this.configuration, () => this.refresh());
    this.rootElement = el;
    this.refresh();
  }
  loadConfiguration(configurationString) {
    try {
      const parsedConfig = (0, import_obsidian5.parseYaml)(configurationString) || {};
      const normalizedConfig = normalizeKeys(parsedConfig);
      let prefixColumns = this.processColumnConfig(parsedConfig["prefix-columns"]);
      let postfixColumns = this.processColumnConfig(parsedConfig["postfix-columns"]);
      const ratingMapKey = parsedConfig["rating-map"] || this.settings.defaultRatingMap;
      const flagMapKey = parsedConfig["flag-map"] || this.settings.defaultFlagMap;
      const ratingMap = DEFAULT_MAPS.ratings[ratingMapKey] || DEFAULT_MAPS.ratings[this.settings.defaultRatingMap];
      const flagMap = DEFAULT_MAPS.flags[flagMapKey] || DEFAULT_MAPS.flags[this.settings.defaultFlagMap];
      return {
        ...DEFAULT_CONFIGURATION(),
        ...normalizedConfig,
        prefixColumns,
        postfixColumns,
        ratingSymbols: ratingMap.symbols,
        flagSymbols: flagMap.symbols,
        flagKeys: flagMap.keys,
        daysInPast: Math.max(
          this.settings.minDaysPast,
          parsedConfig["days-past"] || this.settings.defaultDaysPast
        ),
        daysInFuture: Math.max(
          this.settings.minDaysFuture,
          parsedConfig["days-future"] || this.settings.defaultDaysFuture
        )
      };
    } catch (error) {
      new import_obsidian4.Notice(`${PLUGIN_NAME}: Invalid configuration. Using defaults.`);
      return {
        ...DEFAULT_CONFIGURATION(),
        daysInPast: this.settings.defaultDaysPast,
        daysInFuture: this.settings.defaultDaysFuture
      };
    }
  }
  processColumnConfig(config) {
    let columns = {};
    if (Array.isArray(config)) {
      config.forEach((field) => {
        columns[String(field)] = String(field);
      });
    } else if (typeof config === "object" && config !== null) {
      Object.entries(config).forEach(([display, field]) => {
        columns[display] = String(field);
      });
    } else if (typeof config === "string") {
      columns[config] = config;
    }
    return columns;
  }
  async refresh() {
    const files = this.fileService.loadFiles(this.configuration);
    if (files.length === 0) {
      this.renderNoFocussFound();
      return;
    }
    const { controlsContainer, tableElement } = this.createBaseStructure();
    this.configuration.focusTracksGoHere = tableElement;
    this.controls.renderControls(controlsContainer, this.configuration);
    this.header.renderTableHeader(tableElement);
    const sortedFiles = await this.sortingService.sortFiles(files, this.configuration);
    for (const [focusTargetLabel, file] of sortedFiles) {
      const focusLogs = await this.fileService.readFocusLogs(
        file.path,
        this.configuration.logPropertyName
      );
      await this.renderFocusLogs(file.path, focusTargetLabel, focusLogs);
    }
  }
  createBaseStructure() {
    this.rootElement.empty();
    const mainContainer = this.rootElement.createEl("div", {
      cls: "focus-tracker-container"
    });
    const controlsContainer = mainContainer.createEl("div", {
      cls: "focus-tracker__controls"
    });
    const tableContainer = mainContainer.createEl("div", {
      cls: "focus-tracker-table-container"
    });
    const tableElement = tableContainer.createEl("div", {
      cls: "focus-tracker"
    });
    tableElement.setAttribute("id", this.id);
    return { controlsContainer, tableElement };
  }
  renderNoFocussFound() {
    var _a, _b;
    (_a = this.rootElement) == null ? void 0 : _a.empty();
    (_b = this.rootElement) == null ? void 0 : _b.createEl("div", {
      text: `No files found matching criteria`
    });
  }
  get ratingSymbols() {
    if (!this._ratingSymbols) {
      this._ratingSymbols = [...this.configuration.ratingSymbols];
    }
    return this._ratingSymbols;
  }
  get flagSymbols() {
    if (!this._flagSymbols) {
      this._flagSymbols = [...this.configuration.flagSymbols];
    }
    return this._flagSymbols;
  }
  async renderFocusLogs(path, focusTargetLabel, entries) {
    if (!this.configuration.focusTracksGoHere) {
      new import_obsidian4.Notice(`${PLUGIN_NAME}: missing div that holds all focus tracks`);
      return;
    }
    const parent = this.configuration.focusTracksGoHere;
    let rowElement = parent.querySelector(`*[data-id="${pathToId(path)}"]`);
    if (!rowElement) {
      rowElement = parent.createEl("div", {
        cls: "focus-tracker__row"
      });
      rowElement.setAttribute("data-id", pathToId(path));
    } else {
      while (rowElement.firstChild) {
        rowElement.removeChild(rowElement.firstChild);
      }
    }
    const frontmatter = await this.fileService.getFrontmatter(path);
    await this.renderCustomColumns(
      rowElement,
      frontmatter,
      this.configuration.prefixColumns,
      "focus-tracker__cell--prefix"
    );
    await this.renderFocusTitle(rowElement, focusTargetLabel, path);
    await this.renderFocusEntries(rowElement, path, entries);
    await this.renderCustomColumns(
      rowElement,
      frontmatter,
      this.configuration.postfixColumns,
      "focus-tracker__cell--postfix"
    );
  }
  async renderFocusTitle(rowElement, focusTargetLabel, path) {
    const focusTitle = rowElement.createEl("div", {
      cls: "focus-tracker__cell focus-tracker__cell--focus-target-label"
    });
    const focusTitleLink = focusTitle.createEl("a", {
      cls: "internal-link focus-title-link"
    });
    const markdownRenderer = new import_obsidian4.MarkdownRenderChild(focusTitleLink);
    await import_obsidian4.MarkdownRenderer.renderMarkdown(
      focusTargetLabel,
      focusTitleLink,
      "",
      markdownRenderer
    );
    focusTitleLink.setAttribute("href", path);
    focusTitleLink.setAttribute("aria-label", path);
  }
  async renderCustomColumns(row, frontmatter, columns, className) {
    for (const [displayName, propertyName] of Object.entries(columns)) {
      const cell = row.createEl("div", {
        cls: `focus-tracker__cell focus-tracker__cell--custom ${className}`
      });
      const value = frontmatter[propertyName];
      const formattedValue = formatFrontmatterValue(value);
      const markdownRenderer = new import_obsidian4.MarkdownRenderChild(cell);
      await import_obsidian4.MarkdownRenderer.renderMarkdown(
        formattedValue,
        cell,
        "",
        markdownRenderer
      );
      if (cell.scrollWidth > cell.clientWidth) {
        cell.setAttribute("title", formattedValue);
      }
    }
  }
  getDisplayValues(entry) {
    var _a;
    let result = {
      hasValue: false,
      symbol: " ",
      tooltip: "",
      entryScalarValue: 0,
      remarks: void 0
    };
    if (typeof entry === "object" && entry !== null) {
      result.entryScalarValue = entry.rating;
      result.remarks = entry.remarks;
    } else if (typeof entry === "number") {
      result.entryScalarValue = entry;
    } else if (typeof entry === "string") {
      if (entry === "") {
        result.hasValue = false;
      } else {
        result.hasValue = true;
        result.symbol = entry;
        result.tooltip = entry;
      }
      return result;
    }
    if (result.entryScalarValue === 0) {
      result.hasValue = false;
    } else {
      result.hasValue = true;
      if (result.entryScalarValue >= 1) {
        result.symbol = this.getSymbol(this.ratingSymbols, result.entryScalarValue - 1);
        result.tooltip = `Rating: ${result.entryScalarValue}`;
      } else {
        let arrayIndex = -1 * result.entryScalarValue - 1;
        result.symbol = this.getSymbol(this.flagSymbols, arrayIndex);
        let flagKey = (_a = this.configuration.flagKeys) == null ? void 0 : _a[arrayIndex];
        let flagDesc = flagKey ? `: ${flagKey}` : "";
        result.tooltip = `Flag ${-1 * result.entryScalarValue}${flagDesc}`;
      }
    }
    if (result.remarks) {
      result.tooltip = result.hasValue ? `${result.tooltip}
\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
${result.remarks}` : result.remarks;
    }
    return result;
  }
  getSymbol(symbolArray, symbolIndex) {
    return symbolIndex >= symbolArray.length ? OUT_OF_BOUNDS : symbolArray[symbolIndex];
  }
  async stepFocusLogEntry(el, step = 1) {
    const focusTrackerPath = el.getAttribute("focusTrackerPath");
    const date = el.getAttribute("date");
    const currentValue = this.getFocusRatingFromElement(el);
    let newValue = 0;
    if (currentValue === 0) {
      newValue = 1;
    } else {
      newValue = (currentValue < 0 ? 0 - currentValue : currentValue) + 1;
      const maxScaleIndex = currentValue < 0 ? this.flagSymbols.length : this.ratingSymbols.length;
      newValue = newValue > maxScaleIndex ? 0 : newValue;
      newValue = currentValue < 0 ? 0 - newValue : newValue;
    }
    await this.setFocusEntry(focusTrackerPath, date, newValue);
  }
  getFocusRatingFromElement(el) {
    const attrValue = el.getAttribute("focusRating");
    if (!attrValue || attrValue === null || attrValue.trim() === "") {
      return 0;
    }
    const numValue = Number(attrValue);
    return isNaN(numValue) || numValue === 0 ? 0 : numValue;
  }
  showFocusMenu(event, path, dateString, currentRemarks) {
    const menu = new import_obsidian4.Menu();
    menu.addItem(
      (item) => item.setTitle(currentRemarks ? `Edit Remarks: ${currentRemarks}` : "Add Remarks").setIcon("edit").onClick(() => {
        new RemarksModal(
          this.app,
          currentRemarks || "",
          async (result) => {
            await this.setFocusEntry(path, dateString, void 0, result);
          }
        ).open();
      })
    );
    menu.addSeparator();
    this.ratingSymbols.slice().reverse().forEach((symbol, rSymbolIndex) => {
      let symbolIndex = this.configuration.ratingSymbols.length - rSymbolIndex;
      menu.addItem(
        (item) => item.setTitle(`${symbol} (Rating = ${symbolIndex})`).setIcon("check-circle").onClick(async () => {
          await this.setFocusEntry(path, dateString, symbolIndex);
        })
      );
    });
    menu.addSeparator();
    menu.addItem(
      (item) => item.setTitle("Clear Rating").setIcon("x-circle").onClick(async () => {
        await this.setFocusEntry(path, dateString, 0);
      })
    );
    menu.addSeparator();
    this.configuration.flagSymbols.forEach((symbol, symbolIndex) => {
      var _a;
      let newValue = 0 - (symbolIndex + 1);
      let flagKey = (_a = this.configuration.flagKeys) == null ? void 0 : _a[symbolIndex];
      let flagDesc = flagKey ? `: ${flagKey}` : "";
      menu.addItem(
        (item) => item.setTitle(`${symbol} (Flag ${-1 * newValue}${flagDesc})`).setIcon("flag").onClick(async () => {
          await this.setFocusEntry(path, dateString, newValue);
        })
      );
    });
    menu.showAtMouseEvent(event);
  }
  async setFocusEntry(focusTrackerPath, date, newRating, remarks) {
    if (!focusTrackerPath || !date) {
      new import_obsidian4.Notice(`${PLUGIN_NAME}: Missing data attributes for focus tracking.`);
      return;
    }
    const file = this.app.vault.getAbstractFileByPath(focusTrackerPath);
    if (!file || !(file instanceof import_obsidian4.TFile)) {
      new import_obsidian4.Notice(`${PLUGIN_NAME}: File missing while trying to change focus rating.`);
      return;
    }
    await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      let entries = frontmatter[this.configuration.logPropertyName] || {};
      const currentEntry = entries[date];
      let newEntry;
      if (typeof currentEntry === "object" && currentEntry !== null) {
        newEntry = { ...currentEntry };
      } else if (typeof currentEntry === "number") {
        newEntry = { rating: currentEntry };
      } else {
        newEntry = { rating: 0 };
      }
      if (newRating !== void 0) {
        newEntry.rating = newRating;
      }
      if (remarks !== void 0) {
        if (remarks.trim() === "") {
          delete newEntry.remarks;
        } else {
          newEntry.remarks = remarks.trim();
        }
      }
      entries[date] = newEntry;
      const sortedEntriesArray = Object.entries(entries).sort(([date1], [date2]) => new Date(date1).getTime() - new Date(date2).getTime());
      frontmatter[this.configuration.logPropertyName] = Object.fromEntries(sortedEntriesArray);
      new import_obsidian4.Notice(`Updated focus entry for ${date}`, 600);
    });
    await this.renderFocusLogs(
      focusTrackerPath,
      await this.fileService.getFocusTargetLabel(
        focusTrackerPath,
        this.configuration.titlePropertyNames
      ),
      await this.fileService.readFocusLogs(
        focusTrackerPath,
        this.configuration.logPropertyName
      )
    );
  }
  async renderFocusEntries(rowElement, path, entries) {
    const totalDays = this.configuration.daysInPast + this.configuration.daysInFuture + 1;
    let currentDate = new Date(this.configuration.focalDate);
    currentDate.setDate(currentDate.getDate() - this.configuration.daysInPast);
    currentDate.setHours(0, 0, 0, 0);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    for (let i = 0; i < totalDays; i++) {
      const dateString = this.getDateId(currentDate);
      const entry = entries[dateString];
      const {
        hasValue,
        symbol,
        tooltip,
        entryScalarValue,
        remarks
      } = this.getDisplayValues(entry);
      const focusCell = rowElement.createEl("div", {
        cls: `focus-tracker__cell focus-tick focus-tick-entry focus-tick--${hasValue} focus-tracker__cell--${this.getDayOfWeek(currentDate)}`,
        title: tooltip
      });
      this.setupFocusCell(focusCell, {
        hasValue,
        dateString,
        path,
        entryScalarValue,
        remarks,
        symbol,
        currentDate,
        today
      });
      currentDate.setDate(currentDate.getDate() + 1);
    }
  }
  setupFocusCell(focusCell, config) {
    var _a;
    focusCell.setAttribute("ticked", config.hasValue.toString());
    focusCell.setAttribute("date", config.dateString);
    focusCell.setAttribute("focusTrackerPath", config.path);
    focusCell.setAttribute("focusRating", ((_a = config.entryScalarValue) == null ? void 0 : _a.toString()) || "");
    if (config.remarks) {
      focusCell.setAttribute("focusRemarks", config.remarks);
    }
    focusCell.setText(config.symbol);
    focusCell.addEventListener("click", (e) => {
      if (e.altKey) {
        this.stepFocusLogEntry(focusCell, -1);
      } else {
        this.stepFocusLogEntry(focusCell, 1);
      }
    });
    focusCell.addEventListener("contextmenu", (event) => {
      event.preventDefault();
      this.showFocusMenu(event, config.path, config.dateString, config.remarks);
    });
    if (isSameDate(config.currentDate, this.configuration.focalDate)) {
      focusCell.addClass("focus-tracker__cell--focal-date");
    }
    if (isSameDate(config.currentDate, config.today)) {
      focusCell.addClass("focus-tracker__cell--today");
    } else if (config.currentDate > config.today) {
      focusCell.addClass("focus-tracker__cell--future");
    } else if (config.currentDate < config.today) {
      focusCell.addClass("focus-tracker__cell--past");
    }
  }
  getDayOfWeek(date) {
    const daysOfWeek = [
      "sunday",
      "monday",
      "tuesday",
      "wednesday",
      "thursday",
      "friday",
      "saturday"
    ];
    return daysOfWeek[date.getDay()].toLowerCase();
  }
  getDateId(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  }
};

// src/FocusTrackerSettingsTab.ts
var import_obsidian6 = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultRatingMap: DEFAULT_CONFIG.ratingMap,
  defaultFlagMap: DEFAULT_CONFIG.flagMap,
  minDaysPast: 1,
  minDaysFuture: 1,
  defaultDaysPast: DEFAULT_CONFIG.daysPast,
  defaultDaysFuture: DEFAULT_CONFIG.daysFuture
};
var FocusTrackerSettingsTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Focus Tracker Settings" });
    new import_obsidian6.Setting(containerEl).setName("Default Rating Map").setDesc("Choose the default rating map for new focus trackers").addDropdown((dropdown) => dropdown.addOptions(Object.fromEntries(
      Object.keys(DEFAULT_MAPS.ratings).map((key) => [key, key])
    )).setValue(this.plugin.settings.defaultRatingMap).onChange(async (value) => {
      this.plugin.settings.defaultRatingMap = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian6.Setting(containerEl).setName("Default Flag Map").setDesc("Choose the default flag map for new focus trackers").addDropdown((dropdown) => dropdown.addOptions(Object.fromEntries(
      Object.keys(DEFAULT_MAPS.flags).map((key) => [key, key])
    )).setValue(this.plugin.settings.defaultFlagMap).onChange(async (value) => {
      this.plugin.settings.defaultFlagMap = value;
      await this.plugin.saveSettings();
    }));
    this.createDualInputSetting(
      containerEl,
      "Minimum Days Past",
      "Minimum number of past days that can be displayed",
      "minDaysPast",
      1,
      30
    );
    this.createDualInputSetting(
      containerEl,
      "Default Days Past",
      "Default number of past days to display",
      "defaultDaysPast",
      this.plugin.settings.minDaysPast,
      30
    );
    this.createDualInputSetting(
      containerEl,
      "Minimum Days Future",
      "Minimum number of future days that can be displayed",
      "minDaysFuture",
      1,
      30
    );
    this.createDualInputSetting(
      containerEl,
      "Default Days Future",
      "Default number of future days to display",
      "defaultDaysFuture",
      this.plugin.settings.minDaysFuture,
      30
    );
  }
  createDualInputSetting(containerEl, name, desc, settingKey, min, max) {
    const setting = new import_obsidian6.Setting(containerEl).setName(name).setDesc(desc);
    let sliderComponent;
    setting.addText((text) => {
      const textComponent = text.setPlaceholder(min.toString()).setValue(this.plugin.settings[settingKey].toString()).onChange(async (value) => {
        const numValue = parseInt(value);
        if (!isNaN(numValue) && numValue >= min && numValue <= max) {
          this.plugin.settings[settingKey] = numValue;
          await this.plugin.saveSettings();
          if (sliderComponent) {
            sliderComponent.setValue(numValue);
          }
        }
      });
      textComponent.inputEl.type = "number";
      textComponent.inputEl.setAttr("min", min.toString());
      textComponent.inputEl.setAttr("max", max.toString());
      return textComponent;
    });
    setting.addSlider((slider) => {
      sliderComponent = slider;
      return slider.setLimits(min, max, 1).setValue(this.plugin.settings[settingKey]).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings[settingKey] = value;
        await this.plugin.saveSettings();
        const textInputs = setting.controlEl.querySelectorAll('input[type="number"]');
        if (textInputs.length > 0) {
          textInputs[0].value = value.toString();
        }
      });
    });
    setting.controlEl.createSpan({
      text: `Current: ${this.plugin.settings[settingKey]}`,
      cls: "setting-item-value"
    });
  }
};

// src/main.ts
var FocusTrackerPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.focusTrackers = [];
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new FocusTrackerSettingsTab(this.app, this));
    this.registerMarkdownCodeBlockProcessor(
      "focustracker",
      async (src, el, ctx) => {
        let ft = new FocusTracker(src, el, ctx, this.app, this.settings);
        this.focusTrackers.push(ft);
      }
    );
    this.addCommand({
      id: "refresh-focus-trackers",
      name: "Refresh focus trackers",
      callback: () => {
        this.focusTrackers.forEach((ft) => ft.refresh());
      }
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.focusTrackers.forEach((ft) => ft.refresh());
  }
};

/* nosourcemap */