/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/migration/tagReplacer.ts
function replaceTagsOutsideCode(content, from, to) {
  const lines = content.split("\n");
  let inFencedBlock = false;
  let fenceChar = "";
  let inHtmlComment = false;
  let prevLineBlank = true;
  let inIndentedCode = false;
  const escapedFrom = from.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trimStart();
    const indent = line.length - trimmed.length;
    const isBlank = trimmed.length === 0;
    if (inHtmlComment) {
      const endIdx = line.indexOf("-->");
      if (endIdx === -1) {
        prevLineBlank = isBlank;
        continue;
      }
      inHtmlComment = false;
      const afterComment = line.substring(endIdx + 3);
      const processed = replaceInNormalText(afterComment, escapedFrom, to);
      lines[i] = line.substring(0, endIdx + 3) + processed.text;
      inHtmlComment = processed.endsInComment;
      prevLineBlank = false;
      continue;
    }
    const fenceMatch = trimmed.match(/^(`{3,}|~{3,})/);
    if (fenceMatch) {
      if (!inFencedBlock) {
        inFencedBlock = true;
        fenceChar = fenceMatch[1].charAt(0);
        inIndentedCode = false;
        prevLineBlank = false;
        continue;
      }
      if (trimmed.charAt(0) === fenceChar) {
        inFencedBlock = false;
        prevLineBlank = false;
        continue;
      }
    }
    if (inFencedBlock) {
      prevLineBlank = false;
      continue;
    }
    const isIndented = !isBlank && (indent >= 4 || line.charAt(0) === "	");
    if (inIndentedCode) {
      if (isIndented || isBlank) {
        prevLineBlank = isBlank;
        continue;
      }
      inIndentedCode = false;
    } else if (isIndented && prevLineBlank) {
      inIndentedCode = true;
      prevLineBlank = false;
      continue;
    }
    if (!isBlank) {
      const processed = replaceInNormalText(line, escapedFrom, to);
      lines[i] = processed.text;
      inHtmlComment = processed.endsInComment;
    }
    prevLineBlank = isBlank;
  }
  return lines.join("\n");
}
function replaceInNormalText(text, escapedFrom, to) {
  let endsInComment = false;
  const regex = new RegExp(
    `(\`{2,})([\\s\\S]*?)\\1|\`[^\`]+\`|<!--[\\s\\S]*?-->|<!--.*$|((?<![\\p{L}\\p{N}_\\-/#])${escapedFrom}(?![\\p{L}\\p{N}_\\-/]))`,
    "gu"
  );
  const result = text.replace(
    regex,
    (match, _multiTick, _multiContent, tag) => {
      if (match.startsWith("<!--") && !match.includes("-->")) {
        endsInComment = true;
        return match;
      }
      if (tag !== void 0) {
        return to;
      }
      return match;
    }
  );
  return { text: result, endsInComment };
}
var init_tagReplacer = __esm({
  "src/migration/tagReplacer.ts"() {
  }
});

// src/core/frontmatterTags.ts
function normalizeFrontmatterTags(value) {
  if (typeof value === "string") {
    return [value];
  }
  if (!Array.isArray(value)) {
    return [];
  }
  return value.filter((item) => typeof item === "string");
}
function toHashPrefixedTag(tag) {
  return tag.startsWith("#") ? tag : `#${tag}`;
}
function frontmatterTagMatches(frontmatterTag, tag) {
  return toHashPrefixedTag(frontmatterTag).toLowerCase() === tag.toLowerCase();
}
var init_frontmatterTags = __esm({
  "src/core/frontmatterTags.ts"() {
  }
});

// src/migration/BatchMigration.ts
var BatchMigration_exports = {};
__export(BatchMigration_exports, {
  BatchMigration: () => BatchMigration
});
var import_obsidian, BatchMigration, MigrationPreviewModal;
var init_BatchMigration = __esm({
  "src/migration/BatchMigration.ts"() {
    import_obsidian = require("obsidian");
    init_tagReplacer();
    init_frontmatterTags();
    BatchMigration = class {
      constructor(app, aliasManager) {
        this.app = app;
        this.aliasManager = aliasManager;
      }
      /**
       * Entry point: scan the vault, show preview, and execute if confirmed.
       */
      async run() {
        const groups = this.aliasManager.getGroups();
        if (groups.length === 0) {
          new import_obsidian.Notice("No alias groups defined. Create alias groups first.");
          return;
        }
        new import_obsidian.Notice("Scanning vault for alias tags...");
        const plan = this.scan();
        if (plan.totalReplacements === 0) {
          new import_obsidian.Notice("No alias tags found in vault. Everything is already normalized.");
          return;
        }
        const confirmed = await this.showPreview(plan);
        if (!confirmed) {
          new import_obsidian.Notice("Migration cancelled.");
          return;
        }
        await this.execute(plan);
      }
      /**
       * Scan all markdown files and build a migration plan.
       */
      scan() {
        var _a;
        const changes = [];
        let totalReplacements = 0;
        const files = this.app.vault.getMarkdownFiles();
        for (const file of files) {
          const cache = this.app.metadataCache.getFileCache(file);
          if (!cache)
            continue;
          const tags = (0, import_obsidian.getAllTags)(cache) || [];
          const replacements = [];
          for (const tag of tags) {
            if (this.aliasManager.isAlias(tag)) {
              const primaryTag = this.aliasManager.getPrimaryTag(tag);
              const isInFrontmatter = this.isTagInFrontmatter(tag, cache);
              const isInline = (_a = cache.tags) == null ? void 0 : _a.some(
                (t) => t.tag.toLowerCase() === tag.toLowerCase()
              );
              if (isInFrontmatter) {
                replacements.push({
                  from: tag,
                  to: primaryTag,
                  location: "frontmatter"
                });
              }
              if (isInline) {
                replacements.push({
                  from: tag,
                  to: primaryTag,
                  location: "inline"
                });
              }
            }
          }
          const uniqueReplacements = this.deduplicateReplacements(replacements);
          if (uniqueReplacements.length > 0) {
            changes.push({
              filePath: file.path,
              replacements: uniqueReplacements
            });
            totalReplacements += uniqueReplacements.length;
          }
        }
        return { changes, totalReplacements };
      }
      /**
       * Check if a tag exists in the file's YAML frontmatter.
       */
      isTagInFrontmatter(tag, cache) {
        var _a;
        const fmTags = normalizeFrontmatterTags((_a = cache.frontmatter) == null ? void 0 : _a["tags"]);
        return fmTags.some((t) => frontmatterTagMatches(t, tag));
      }
      /**
       * Remove duplicate replacements (same from/to/location).
       */
      deduplicateReplacements(replacements) {
        const seen = /* @__PURE__ */ new Set();
        return replacements.filter((r) => {
          const key = `${r.from.toLowerCase()}|${r.to.toLowerCase()}|${r.location}`;
          if (seen.has(key))
            return false;
          seen.add(key);
          return true;
        });
      }
      /**
       * Show a preview modal listing all planned changes.
       * Returns true if user confirms, false if cancelled.
       */
      showPreview(plan) {
        return new Promise((resolve) => {
          const modal = new MigrationPreviewModal(this.app, plan, resolve);
          modal.open();
        });
      }
      /**
       * Execute the migration plan: replace alias tags in all affected files.
       */
      async execute(plan) {
        let successCount = 0;
        let errorCount = 0;
        for (const change of plan.changes) {
          try {
            const file = this.app.vault.getAbstractFileByPath(change.filePath);
            if (!(file instanceof import_obsidian.TFile)) {
              console.warn("[TagAliases] File not found:", change.filePath);
              errorCount++;
              continue;
            }
            const inlineReplacements = change.replacements.filter((r) => r.location === "inline");
            const fmReplacements = change.replacements.filter((r) => r.location === "frontmatter");
            if (inlineReplacements.length > 0) {
              let content = await this.app.vault.read(file);
              for (const { from, to } of inlineReplacements) {
                content = replaceTagsOutsideCode(content, from, to);
              }
              await this.app.vault.modify(file, content);
            }
            if (fmReplacements.length > 0) {
              await this.app.fileManager.processFrontMatter(file, (frontmatterData) => {
                const frontmatter = frontmatterData;
                const tags = normalizeFrontmatterTags(frontmatter["tags"]);
                if (tags.length === 0)
                  return;
                for (let i = 0; i < tags.length; i++) {
                  const tagWithHash = toHashPrefixedTag(tags[i]);
                  const replacement = fmReplacements.find(
                    (r) => r.from.toLowerCase() === tagWithHash.toLowerCase()
                  );
                  if (replacement) {
                    tags[i] = replacement.to.replace(/^#/, "");
                  }
                }
                frontmatter["tags"] = tags;
              });
            }
            successCount++;
          } catch (err) {
            console.error("[TagAliases] Migration error for file:", change.filePath, err);
            errorCount++;
          }
        }
        const message = errorCount === 0 ? `Migration complete: ${successCount} file(s) updated successfully.` : `Migration complete: ${successCount} file(s) updated, ${errorCount} error(s).`;
        new import_obsidian.Notice(message);
      }
      // Replacement logic delegated to replaceTagsOutsideCode() in tagReplacer.ts
    };
    MigrationPreviewModal = class extends import_obsidian.Modal {
      constructor(app, plan, onResult) {
        super(app);
        /** Guard to prevent double-resolving the promise */
        this.resolved = false;
        this.plan = plan;
        this.onResult = onResult;
      }
      onOpen() {
        const { contentEl } = this;
        contentEl.empty();
        contentEl.createEl("h2", { text: "Migration preview" });
        contentEl.createEl("p", {
          text: `Found ${this.plan.totalReplacements} alias tag(s) in ${this.plan.changes.length} file(s) to replace:`
        });
        const listContainer = contentEl.createDiv({
          cls: "tag-aliases-migration-list"
        });
        for (const change of this.plan.changes) {
          const fileItem = listContainer.createDiv({
            cls: "tag-aliases-migration-file"
          });
          fileItem.createEl("strong", { text: change.filePath });
          const ul = fileItem.createEl("ul");
          for (const r of change.replacements) {
            ul.createEl("li", {
              text: `${r.from} \u2192 ${r.to} (${r.location})`
            });
          }
        }
        const buttonRow = contentEl.createDiv({
          cls: "tag-aliases-button-row"
        });
        const cancelBtn = buttonRow.createEl("button", { text: "Cancel" });
        cancelBtn.addEventListener("click", () => {
          this.resolved = true;
          this.onResult(false);
          this.close();
        });
        const confirmBtn = buttonRow.createEl("button", {
          text: `Replace ${this.plan.totalReplacements} tag(s)`,
          cls: "mod-warning"
        });
        confirmBtn.addEventListener("click", () => {
          this.resolved = true;
          this.onResult(true);
          this.close();
        });
      }
      onClose() {
        this.contentEl.empty();
        if (!this.resolved) {
          this.resolved = true;
          this.onResult(false);
        }
      }
    };
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TagAliasesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/constants.ts
var DEFAULT_SETTINGS = {
  aliasGroups: [],
  autoReplace: true
};
var EXPORT_FILE_NAME = "tag-aliases-backup.json";
var VIEW_TYPE_TAG_ALIASES = "tag-aliases-sidebar";

// src/core/AliasManager.ts
var AliasManager = class {
  constructor() {
    /** Primary tag (normalized) -> AliasGroup */
    this.primaryIndex = /* @__PURE__ */ new Map();
    /** Alias tag (normalized) -> AliasGroup */
    this.aliasIndex = /* @__PURE__ */ new Map();
    /** All groups, kept in sync with settings */
    this.groups = [];
  }
  /**
   * Build indexes from a list of alias groups.
   * Called on plugin load and after any CRUD operation.
   */
  buildIndex(groups) {
    this.groups = [...groups];
    this.primaryIndex.clear();
    this.aliasIndex.clear();
    for (const group of this.groups) {
      const normalizedPrimary = this.normalize(group.primaryTag);
      this.primaryIndex.set(normalizedPrimary, group);
      for (const alias of group.aliases) {
        const normalizedAlias = this.normalize(alias);
        this.aliasIndex.set(normalizedAlias, group);
      }
    }
  }
  /**
   * Find the alias group that a tag belongs to (as primary or alias).
   * Returns null if the tag is not part of any group.
   */
  findGroup(tag) {
    var _a, _b;
    const normalized = this.normalize(tag);
    return (_b = (_a = this.primaryIndex.get(normalized)) != null ? _a : this.aliasIndex.get(normalized)) != null ? _b : null;
  }
  /**
   * Check whether a tag is registered as an alias (not a primary tag).
   */
  isAlias(tag) {
    const normalized = this.normalize(tag);
    return this.aliasIndex.has(normalized) && !this.primaryIndex.has(normalized);
  }
  /**
   * Get the primary tag for a given tag.
   * If the tag is an alias, returns the group's primary tag.
   * If the tag is already a primary tag or not in any group, returns itself.
   */
  getPrimaryTag(tag) {
    const group = this.findGroup(tag);
    if (group) {
      return group.primaryTag;
    }
    return tag;
  }
  /**
   * Search for tags matching a query prefix.
   * Matches against both primary tags and aliases.
   * Returns TagSuggestionItems sorted by relevance:
   *   1. Primary tag name matches (matchSource = 'primary')
   *   2. Alias matches (matchSource = 'alias')
   *
   * @param query - The search prefix (without '#'), e.g. "js"
   */
  search(query) {
    const normalizedQuery = query.toLowerCase();
    const results = [];
    const seenGroupIds = /* @__PURE__ */ new Set();
    for (const group of this.groups) {
      const primaryName = this.normalize(group.primaryTag);
      if (primaryName.startsWith(normalizedQuery)) {
        seenGroupIds.add(group.id);
        results.push({
          insertText: group.primaryTag,
          displayText: group.primaryTag,
          matchSource: "primary",
          group
        });
      }
    }
    for (const group of this.groups) {
      if (seenGroupIds.has(group.id)) {
        continue;
      }
      for (const alias of group.aliases) {
        const aliasName = this.normalize(alias);
        if (aliasName.startsWith(normalizedQuery)) {
          seenGroupIds.add(group.id);
          results.push({
            insertText: group.primaryTag,
            displayText: group.primaryTag,
            matchSource: "alias",
            matchedAlias: alias,
            group
          });
          break;
        }
      }
    }
    return results;
  }
  /**
   * Add a new alias group.
   * Returns the updated groups array (caller should persist to settings).
   */
  addGroup(group) {
    this.groups.push(group);
    this.buildIndex(this.groups);
    return [...this.groups];
  }
  /**
   * Update an existing alias group by ID.
   * Returns the updated groups array, or null if the ID was not found.
   */
  updateGroup(id, updates) {
    const index = this.groups.findIndex((g) => g.id === id);
    if (index === -1) {
      console.warn("[TagAliases] Cannot update: group not found, id =", id);
      return null;
    }
    this.groups[index] = { ...this.groups[index], ...updates };
    this.buildIndex(this.groups);
    return [...this.groups];
  }
  /**
   * Remove an alias group by ID.
   * Returns the updated groups array, or null if the ID was not found.
   */
  removeGroup(id) {
    const index = this.groups.findIndex((g) => g.id === id);
    if (index === -1) {
      console.warn("[TagAliases] Cannot remove: group not found, id =", id);
      return null;
    }
    this.groups.splice(index, 1);
    this.buildIndex(this.groups);
    return [...this.groups];
  }
  /** Get all alias groups. */
  getGroups() {
    return [...this.groups];
  }
  /**
   * Validate a new or updated alias group for conflicts.
   * Returns an error message string if invalid, or null if valid.
   *
   * @param group - The group to validate
   * @param excludeId - If editing, exclude this group's own ID from conflict checks
   */
  validate(group, excludeId) {
    const primaryNorm = this.normalize(group.primaryTag);
    if (!primaryNorm) {
      return "Primary tag cannot be empty.";
    }
    if (!this.isValidTagFormat(primaryNorm)) {
      return `Invalid primary tag format: "${group.primaryTag}". Tags may only contain letters, numbers, underscores, hyphens, and slashes.`;
    }
    if (group.aliases.length === 0) {
      return "At least one alias is required.";
    }
    for (const alias of group.aliases) {
      const aliasNorm = this.normalize(alias);
      if (!aliasNorm) {
        return "Alias tags cannot be empty.";
      }
      if (!this.isValidTagFormat(aliasNorm)) {
        return `Invalid alias format: "${alias}". Tags may only contain letters, numbers, underscores, hyphens, and slashes.`;
      }
    }
    const aliasSet = /* @__PURE__ */ new Set();
    for (const alias of group.aliases) {
      const norm = this.normalize(alias);
      if (norm === primaryNorm) {
        return `Alias "${alias}" is the same as the primary tag.`;
      }
      if (aliasSet.has(norm)) {
        return `Duplicate alias: "${alias}".`;
      }
      aliasSet.add(norm);
    }
    for (const existing of this.groups) {
      if (excludeId && existing.id === excludeId) {
        continue;
      }
      const existingPrimary = this.normalize(existing.primaryTag);
      if (primaryNorm === existingPrimary) {
        return `Primary tag "${group.primaryTag}" conflicts with existing group "${existing.primaryTag}".`;
      }
      if (existing.aliases.some((a) => this.normalize(a) === primaryNorm)) {
        return `Primary tag "${group.primaryTag}" is already used as an alias in group "${existing.primaryTag}".`;
      }
      for (const alias of group.aliases) {
        const aliasNorm = this.normalize(alias);
        if (aliasNorm === existingPrimary) {
          return `Alias "${alias}" conflicts with primary tag of group "${existing.primaryTag}".`;
        }
        if (existing.aliases.some((a) => this.normalize(a) === aliasNorm)) {
          return `Alias "${alias}" is already used in group "${existing.primaryTag}".`;
        }
      }
    }
    return null;
  }
  /**
   * Generate a unique ID for a new alias group.
   */
  generateId() {
    return Date.now().toString(36) + Math.random().toString(36).substring(2, 7);
  }
  /**
   * Normalize a tag string for index lookup:
   * strip '#' prefix and convert to lowercase.
   */
  normalize(tag) {
    return tag.replace(/^#/, "").toLowerCase();
  }
  /**
   * Validate that a tag name (without '#') contains only allowed characters:
   * letters (any script), digits, underscores, hyphens, and slashes.
   */
  isValidTagFormat(normalizedTag) {
    return /^[\p{L}\p{N}_\-/]+$/u.test(normalizedTag) && !normalizedTag.startsWith("/") && !normalizedTag.endsWith("/");
  }
};

// src/ui/SettingTab.ts
var import_obsidian2 = require("obsidian");
init_BatchMigration();
var TagAliasesSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /**
   * Render the settings panel content.
   * Called each time the user navigates to the plugin settings.
   */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    this.renderAliasGroupSection(containerEl);
    this.renderBehaviorSection(containerEl);
    this.renderMigrationSection(containerEl);
    this.renderBackupSection(containerEl);
  }
  /**
   * Render alias group summary with a button to open the sidebar.
   * CRUD operations are handled in the sidebar panel.
   */
  renderAliasGroupSection(container) {
    new import_obsidian2.Setting(container).setName("Alias groups").setHeading();
    const groups = this.plugin.aliasManager.getGroups();
    const count = groups.length;
    new import_obsidian2.Setting(container).setName(`${count} alias group${count !== 1 ? "s" : ""} configured`).setDesc("Use the sidebar panel to create, edit, and delete alias groups.").addButton((btn) => {
      btn.setButtonText("Open sidebar").setCta().onClick(() => {
        void this.plugin.activateSidebarView();
      });
    });
  }
  /**
   * Render the behavior settings section.
   */
  renderBehaviorSection(container) {
    new import_obsidian2.Setting(container).setName("Behavior").setHeading();
    new import_obsidian2.Setting(container).setName("Auto-replace alias tags").setDesc(
      "When enabled, alias tags that bypass the suggestion popup will be automatically replaced with the primary tag."
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.autoReplace).onChange(async (value) => {
        this.plugin.settings.autoReplace = value;
        await this.plugin.saveSettings();
      });
    });
  }
  /**
   * Render the data migration section.
   */
  renderMigrationSection(container) {
    new import_obsidian2.Setting(container).setName("Migration").setHeading();
    new import_obsidian2.Setting(container).setName("Scan & replace alias tags in vault").setDesc(
      "Scan all markdown files and replace existing alias tags with their primary tags. A preview will be shown before any changes are made."
    ).addButton((btn) => {
      btn.setButtonText("Scan & replace").setWarning().onClick(() => {
        const migration = new BatchMigration(
          this.app,
          this.plugin.aliasManager
        );
        void migration.run();
      });
    });
  }
  /**
   * Render the backup & restore section.
   */
  renderBackupSection(container) {
    new import_obsidian2.Setting(container).setName("Backup & restore").setHeading();
    new import_obsidian2.Setting(container).setName("Export alias configuration").setDesc(
      "Save all alias groups as a JSON file in your vault. Recommended before uninstalling the plugin."
    ).addButton((btn) => {
      btn.setButtonText("Export").onClick(() => {
        void this.handleExport();
      });
    });
    new import_obsidian2.Setting(container).setName("Import alias configuration").setDesc(
      "Restore alias groups from a previously exported JSON file."
    ).addButton((btn) => {
      btn.setButtonText("Import").onClick(() => {
        this.handleImport();
      });
    });
  }
  /**
   * Export alias groups to a JSON file in the vault root.
   */
  async handleExport() {
    const groups = this.plugin.aliasManager.getGroups();
    if (groups.length === 0) {
      new import_obsidian2.Notice("No alias groups to export.");
      return;
    }
    const exportData = {
      pluginId: "tag-aliases",
      version: "1.0",
      exportedAt: new Date().toISOString(),
      aliasGroups: groups
    };
    const json = JSON.stringify(exportData, null, 2);
    try {
      let fileName = EXPORT_FILE_NAME;
      const existingFile = this.app.vault.getAbstractFileByPath(fileName);
      if (existingFile) {
        const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
        fileName = `tag-aliases-backup-${timestamp}.json`;
      }
      await this.app.vault.create(fileName, json);
      new import_obsidian2.Notice(`Exported ${groups.length} alias group(s) to "${fileName}".`);
    } catch (err) {
      console.error("[TagAliases] Export failed:", err);
      new import_obsidian2.Notice("Export failed. Check the console for details.");
    }
  }
  /**
   * Import alias groups from a JSON file selected via file input.
   */
  handleImport() {
    const input = this.containerEl.createEl("input", {
      cls: "tag-aliases-hidden-file-input",
      attr: { type: "file", accept: ".json" }
    });
    input.addEventListener("change", () => {
      var _a;
      const file = (_a = input.files) == null ? void 0 : _a[0];
      if (!file)
        return;
      void file.text().then(async (text) => {
        try {
          const data = JSON.parse(text);
          if (!data.aliasGroups || !Array.isArray(data.aliasGroups)) {
            new import_obsidian2.Notice('invalid file format: missing "aliasGroups" array.');
            return;
          }
          const importedGroups = data.aliasGroups;
          for (const g of importedGroups) {
            if (!g.primaryTag || !Array.isArray(g.aliases)) {
              new import_obsidian2.Notice('invalid file format: each group must have "primaryTag" and "aliases".');
              return;
            }
            if (!g.id) {
              g.id = this.plugin.aliasManager.generateId();
            }
          }
          const tempManager = new AliasManager();
          for (const g of importedGroups) {
            const error = tempManager.validate(g);
            if (error) {
              new import_obsidian2.Notice(`Import failed \u2014 group "${g.primaryTag}": ${error}`);
              console.warn("[TagAliases] Import validation error:", error, g);
              return;
            }
            tempManager.addGroup(g);
          }
          this.plugin.settings.aliasGroups = importedGroups;
          this.plugin.aliasManager.buildIndex(importedGroups);
          await this.plugin.saveSettings();
          new import_obsidian2.Notice(`Imported ${importedGroups.length} alias group(s) successfully.`);
          this.display();
        } catch (err) {
          console.error("[TagAliases] Import failed:", err);
          new import_obsidian2.Notice("Import failed. Ensure the file is valid JSON.");
        } finally {
          input.remove();
        }
      });
    });
    input.click();
  }
};

// src/suggest/TagAliasSuggest.ts
var import_obsidian3 = require("obsidian");
init_frontmatterTags();
var TagAliasSuggest = class extends import_obsidian3.EditorSuggest {
  constructor(app, aliasManager) {
    super(app);
    this.aliasManager = aliasManager;
  }
  /**
   * Detect whether the cursor is in a tag-typing context.
   * Looks backwards from the cursor for a '#' character that starts a tag.
   * Returns trigger info if found, null otherwise.
   *
   * When this returns non-null, this suggest "claims" the input and
   * should prevent other suggests (including built-in tag suggest) from showing.
   */
  onTrigger(cursor, editor, _file) {
    const line = editor.getLine(cursor.line);
    const textBeforeCursor = line.substring(0, cursor.ch);
    const match = textBeforeCursor.match(/(?:^|[\s])#([\p{L}\p{N}_\-/]*)$/u);
    if (!match) {
      return null;
    }
    const matchStart = match.index + (match[0].length - match[1].length - 1);
    return {
      start: { line: cursor.line, ch: matchStart },
      end: cursor,
      query: match[1]
      // The text after '#', e.g. "js" from "#js"
    };
  }
  /**
   * Generate the suggestion list based on the user's input.
   * Combines alias-aware matches with all vault tags.
   */
  getSuggestions(context) {
    const query = context.query;
    const aliasResults = this.aliasManager.search(query);
    const vaultTags = this.getVaultTags();
    const coveredPrimaryTags = new Set(
      aliasResults.map((r) => r.insertText.toLowerCase())
    );
    const normalizedQuery = query.toLowerCase();
    const vaultResults = [];
    for (const [tag, count] of Object.entries(vaultTags)) {
      const tagLower = tag.toLowerCase();
      const tagName = tagLower.replace(/^#/, "");
      if (coveredPrimaryTags.has(tagLower)) {
        const existing = aliasResults.find(
          (r) => r.insertText.toLowerCase() === tagLower
        );
        if (existing) {
          existing.count = count;
        }
        continue;
      }
      if (tagName.startsWith(normalizedQuery)) {
        vaultResults.push({
          insertText: tag,
          displayText: tag,
          matchSource: "none",
          count
        });
      }
    }
    for (const item of vaultResults) {
      const group = this.aliasManager.findGroup(item.insertText);
      if (group) {
        const originalTag = item.insertText;
        item.insertText = group.primaryTag;
        item.displayText = group.primaryTag;
        item.matchSource = "alias";
        item.matchedAlias = originalTag;
        item.group = group;
      }
    }
    const merged = [
      ...aliasResults.sort((a, b) => {
        var _a, _b;
        return ((_a = b.count) != null ? _a : 0) - ((_b = a.count) != null ? _b : 0);
      }),
      ...vaultResults.sort((a, b) => {
        var _a, _b;
        return ((_a = b.count) != null ? _a : 0) - ((_b = a.count) != null ? _b : 0);
      })
    ];
    const seen = /* @__PURE__ */ new Set();
    const deduped = [];
    for (const item of merged) {
      const key = item.insertText.toLowerCase();
      if (!seen.has(key)) {
        seen.add(key);
        deduped.push(item);
      }
    }
    return deduped;
  }
  /**
   * Render a single suggestion item in the popup.
   * Shows the tag name, alias hint (if matched via alias), and usage count.
   */
  renderSuggestion(item, el) {
    const container = el.createDiv("tag-aliases-suggest-item");
    const topRow = container.createDiv({
      cls: "tag-aliases-suggest-top-row"
    });
    topRow.createSpan({
      text: item.displayText,
      cls: "tag-aliases-suggest-primary"
    });
    if (item.count !== void 0 && item.count > 0) {
      topRow.createSpan({
        text: `\xD7${item.count}`,
        // ×N
        cls: "tag-aliases-suggest-count"
      });
    }
    if (item.matchSource === "alias" && item.matchedAlias) {
      container.createDiv({
        text: `\u21A9 alias: ${item.matchedAlias.replace(/^#/, "")}`,
        // ↩ alias: js
        cls: "tag-aliases-suggest-alias-hint"
      });
    }
    if (item.matchSource === "primary" && item.group && item.group.aliases.length > 0) {
      const aliasNames = item.group.aliases.map((a) => a.replace(/^#/, "")).join(", ");
      container.createDiv({
        text: `aliases: ${aliasNames}`,
        cls: "tag-aliases-suggest-alias-hint"
      });
    }
  }
  /**
   * Handle selection of a suggestion item.
   * Replaces the trigger text with the primary tag.
   */
  selectSuggestion(item, _evt) {
    if (!this.context)
      return;
    const editor = this.context.editor;
    const start = this.context.start;
    const end = this.context.end;
    editor.replaceRange(
      item.insertText + " ",
      start,
      end
    );
    const newCh = start.ch + item.insertText.length + 1;
    editor.setCursor({ line: start.line, ch: newCh });
  }
  /**
   * Get all tags in the vault with their usage counts.
   * Uses the undocumented MetadataCache.getTags() API which returns
   * Record<string, number>. Falls back to manual enumeration if unavailable.
   */
  getVaultTags() {
    var _a, _b, _c;
    const metadataCache = this.app.metadataCache;
    if (typeof metadataCache.getTags === "function") {
      return metadataCache.getTags();
    }
    console.warn("[TagAliases] MetadataCache.getTags() not available, using fallback.");
    const tags = {};
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      const cache = this.app.metadataCache.getFileCache(file);
      if (!cache)
        continue;
      if (cache.tags) {
        for (const tagCache of cache.tags) {
          const tag = tagCache.tag;
          tags[tag] = ((_a = tags[tag]) != null ? _a : 0) + 1;
        }
      }
      const fmTags = normalizeFrontmatterTags((_b = cache.frontmatter) == null ? void 0 : _b["tags"]);
      if (fmTags.length > 0) {
        for (const t of fmTags) {
          const tag = toHashPrefixedTag(t);
          tags[tag] = ((_c = tags[tag]) != null ? _c : 0) + 1;
        }
      }
    }
    return tags;
  }
};

// src/ui/TagSidebarView.ts
var import_obsidian4 = require("obsidian");

// src/core/ConflictChecker.ts
function checkConflicts(groups, vaultTags) {
  const conflicts = [];
  const normalize = (t) => t.replace(/^#/, "").toLowerCase();
  const tagOwners = /* @__PURE__ */ new Map();
  for (const group of groups) {
    const pNorm = normalize(group.primaryTag);
    if (!tagOwners.has(pNorm))
      tagOwners.set(pNorm, []);
    tagOwners.get(pNorm).push({ groupId: group.id, tag: group.primaryTag, role: "primary" });
    for (const alias of group.aliases) {
      const aNorm = normalize(alias);
      if (!tagOwners.has(aNorm))
        tagOwners.set(aNorm, []);
      tagOwners.get(aNorm).push({ groupId: group.id, tag: alias, role: "alias" });
    }
  }
  for (const [, owners] of tagOwners) {
    if (owners.length <= 1)
      continue;
    const groupIds = [...new Set(owners.map((o) => o.groupId))];
    if (groupIds.length <= 1)
      continue;
    const primaryCount = owners.filter((o) => o.role === "primary").length;
    const hasPrimary = owners.some((o) => o.role === "primary");
    const hasAlias = owners.some((o) => o.role === "alias");
    const tag = owners[0].tag;
    if (primaryCount >= 2) {
      conflicts.push({
        type: "duplicate-primary",
        description: `"${tag}" is used as primary tag in multiple groups.`,
        tag,
        groupIds
      });
    } else if (hasPrimary && hasAlias) {
      conflicts.push({
        type: "primary-as-alias",
        description: `"${tag}" is a primary tag in one group and an alias in another.`,
        tag,
        groupIds
      });
    } else {
      conflicts.push({
        type: "duplicate-alias",
        description: `"${tag}" is used as an alias in multiple groups.`,
        tag,
        groupIds
      });
    }
  }
  if (vaultTags) {
    const aliasToGroup = /* @__PURE__ */ new Map();
    for (const group of groups) {
      for (const alias of group.aliases) {
        aliasToGroup.set(normalize(alias), group);
      }
    }
    const allNorms = Object.keys(vaultTags).map((t) => normalize(t));
    for (const vaultTag of Object.keys(vaultTags)) {
      const norm = normalize(vaultTag);
      const group = aliasToGroup.get(norm);
      if (!group)
        continue;
      const isParentOnly = allNorms.some(
        (other) => other.startsWith(norm + "/")
      );
      if (isParentOnly)
        continue;
      conflicts.push({
        type: "unmigrated-alias",
        description: `"${vaultTag}" is used in vault but is an alias of "${group.primaryTag}". Run batch migration to fix.`,
        tag: vaultTag,
        groupIds: [group.id]
      });
    }
  }
  return conflicts;
}

// src/ui/TagSidebarView.ts
var TagSidebarView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    /** Current search filter text. */
    this.searchQuery = "";
    /** Current sort mode key. */
    this.sortMode = "name-asc";
    /** Tag string of the currently expanded item (null = all collapsed). */
    this.expandedTag = null;
    /** DOM reference to the scrollable tag list container. */
    this.listContainer = null;
    /** DOM reference to the conflict banner area. */
    this.bannerContainer = null;
    /** Whether a metadata refresh was deferred while an alias input had focus. */
    this.pendingListRefresh = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_TAG_ALIASES;
  }
  getDisplayText() {
    return "Tag aliases";
  }
  getIcon() {
    return "tags";
  }
  /**
   * Called when the sidebar view is opened.
   * Builds the full sidebar UI: toolbar, conflict banner, and tag list.
   */
  async onOpen() {
    await super.onOpen();
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("tag-aliases-sidebar");
    this.renderToolbar(container);
    this.bannerContainer = container.createDiv("tag-aliases-conflict-banner-wrapper");
    this.listContainer = container.createDiv("tag-aliases-sidebar-list");
    const debouncedRefresh = (0, import_obsidian4.debounce)(() => this.refreshFromMetadata(), 500, true);
    this.registerEvent(
      this.app.metadataCache.on("resolved", debouncedRefresh)
    );
    this.refresh();
  }
  async onClose() {
    await super.onClose();
    this.containerEl.empty();
  }
  /**
   * Full re-render: rebuild display list, update conflict banner, re-render tag list.
   * Called after any data mutation (add/remove alias, delete group, etc.).
   */
  refresh() {
    this.pendingListRefresh = false;
    const displayList = this.buildDisplayList();
    const vaultTags = this.getVaultTags();
    const conflicts = checkConflicts(this.plugin.aliasManager.getGroups(), vaultTags);
    this.renderConflictBanner(conflicts);
    this.renderTagList(displayList);
  }
  /**
   * Refresh the sidebar after metadata changes without destroying active alias input.
   * Metadata updates are frequent, so list rendering is deferred while the user is
   * typing a new alias and replayed once that input loses focus.
   */
  refreshFromMetadata() {
    const vaultTags = this.getVaultTags();
    const conflicts = checkConflicts(this.plugin.aliasManager.getGroups(), vaultTags);
    this.renderConflictBanner(conflicts);
    if (this.isAliasInputFocused()) {
      this.pendingListRefresh = true;
      console.debug("[TagAliases] Deferred sidebar list refresh while alias input is focused.");
      return;
    }
    this.pendingListRefresh = false;
    const displayList = this.buildDisplayList();
    this.renderTagList(displayList);
  }
  /**
   * Check whether the active element is one of the add-alias inputs.
   */
  isAliasInputFocused() {
    const activeElement = this.containerEl.doc.activeElement;
    if (!(activeElement == null ? void 0 : activeElement.instanceOf(HTMLInputElement))) {
      return false;
    }
    return this.containerEl.contains(activeElement) && activeElement.closest(".tag-aliases-sidebar-add-row") !== null;
  }
  /**
   * Register shared behavior for add-alias inputs.
   */
  registerAliasInputHandlers(addInput) {
    addInput.addEventListener("click", (e) => e.stopPropagation());
    addInput.addEventListener("blur", () => {
      if (!this.pendingListRefresh) {
        return;
      }
      addInput.win.setTimeout(() => {
        if (!this.isAliasInputFocused() && this.pendingListRefresh) {
          this.refresh();
        }
      }, 0);
    });
  }
  // ──────────────────────────────────────────────
  //  Toolbar: Search & Sort
  // ──────────────────────────────────────────────
  /**
   * Render the search input and sort dropdown into the toolbar area.
   */
  renderToolbar(parent) {
    const toolbar = parent.createDiv("tag-aliases-sidebar-toolbar");
    const searchInput = toolbar.createEl("input", {
      cls: "tag-aliases-sidebar-search",
      attr: { type: "text", placeholder: "Search tags..." }
    });
    const debouncedSearch = (0, import_obsidian4.debounce)((value) => {
      this.searchQuery = value;
      this.refresh();
    }, 150, true);
    searchInput.addEventListener("input", () => {
      debouncedSearch(searchInput.value);
    });
    const sortSelect = toolbar.createEl("select", {
      cls: "tag-aliases-sidebar-sort"
    });
    const sortOptions = [
      { value: "name-asc", label: "Name A \u2192 Z" },
      { value: "name-desc", label: "Name Z \u2192 A" },
      { value: "count-desc", label: "Most used" },
      { value: "alias-desc", label: "Most aliases" }
    ];
    for (const opt of sortOptions) {
      const optEl = sortSelect.createEl("option", { text: opt.label, attr: { value: opt.value } });
      if (opt.value === this.sortMode) {
        optEl.selected = true;
      }
    }
    sortSelect.addEventListener("change", () => {
      this.sortMode = sortSelect.value;
      this.refresh();
    });
  }
  // ──────────────────────────────────────────────
  //  Conflict Banner
  // ──────────────────────────────────────────────
  /**
   * Render or clear the conflict warning banner.
   *
   * Separates conflicts into two categories:
   * - Unmigrated aliases: fixable via batch migration (shows a "Run Migration" button)
   * - Structural conflicts: require manual editing (duplicate alias, primary-as-alias, etc.)
   */
  renderConflictBanner(conflicts) {
    if (!this.bannerContainer)
      return;
    this.bannerContainer.empty();
    if (conflicts.length === 0)
      return;
    const unmigrated = conflicts.filter((c) => c.type === "unmigrated-alias");
    const structural = conflicts.filter((c) => c.type !== "unmigrated-alias");
    if (structural.length > 0) {
      const banner = this.bannerContainer.createDiv("tag-aliases-conflict-banner");
      banner.createEl("strong", { text: "Conflicts detected" });
      banner.createEl("p", {
        text: "Edit the highlighted groups below to resolve:",
        cls: "tag-aliases-conflict-hint"
      });
      const list = banner.createEl("ul");
      for (const c of structural) {
        list.createEl("li", { text: c.description });
      }
    }
    if (unmigrated.length > 0) {
      const banner = this.bannerContainer.createDiv("tag-aliases-conflict-banner");
      banner.createEl("strong", { text: `\u26A0 ${unmigrated.length} unmigrated alias(es)` });
      const list = banner.createEl("ul");
      for (const c of unmigrated) {
        const alias = c.tag.replace(/^#/, "");
        const primary = c.groupIds[0] ? this.plugin.aliasManager.getPrimaryTag(c.tag).replace(/^#/, "") : "?";
        list.createEl("li", { text: `${alias} \u2192 ${primary}` });
      }
      const migrateBtn = banner.createEl("button", {
        cls: "tag-aliases-conflict-migrate-btn",
        text: "Run migration"
      });
      migrateBtn.addEventListener("click", () => {
        void Promise.resolve().then(() => (init_BatchMigration(), BatchMigration_exports)).then(({ BatchMigration: BatchMigration2 }) => {
          const migration = new BatchMigration2(this.app, this.plugin.aliasManager);
          return migration.run();
        }).then(() => {
          this.refresh();
        });
      });
    }
  }
  // ──────────────────────────────────────────────
  //  Display List Construction
  // ──────────────────────────────────────────────
  /**
   * Build the merged display list from vault tags and alias groups.
   *
   * Steps:
   * 1. Get vault tags (tag -> count) from MetadataCache
   * 2. Get alias groups from AliasManager
   * 3. Build a set of all known aliases (to exclude from top-level)
   * 4. Run conflict detection to mark conflicting groups
   * 5. For each vault tag: skip aliases, attach group if primary
   * 6. Add alias groups whose primaryTag has no vault usage (count=0)
   * 7. Apply search filter and sort
   */
  /**
   * Get all vault tags with usage counts from MetadataCache.
   */
  getVaultTags() {
    const metadataCache = this.app.metadataCache;
    return typeof metadataCache.getTags === "function" ? metadataCache.getTags() : {};
  }
  buildDisplayList() {
    const vaultTags = this.getVaultTags();
    const groups = this.plugin.aliasManager.getGroups();
    const aliasSet = /* @__PURE__ */ new Set();
    for (const group of groups) {
      for (const alias of group.aliases) {
        aliasSet.add(alias.replace(/^#/, "").toLowerCase());
      }
    }
    const conflicts = checkConflicts(groups);
    const conflictGroupIds = /* @__PURE__ */ new Set();
    for (const c of conflicts) {
      for (const id of c.groupIds) {
        conflictGroupIds.add(id);
      }
    }
    const result = [];
    const addedPrimaries = /* @__PURE__ */ new Set();
    for (const [tag, count] of Object.entries(vaultTags)) {
      const normalized = tag.replace(/^#/, "").toLowerCase();
      if (aliasSet.has(normalized)) {
        continue;
      }
      const group = this.plugin.aliasManager.findGroup(tag);
      let attachedGroup = null;
      if (group && group.primaryTag.replace(/^#/, "").toLowerCase() === normalized) {
        attachedGroup = group;
        addedPrimaries.add(normalized);
      }
      const hasConflict = attachedGroup ? conflictGroupIds.has(attachedGroup.id) : false;
      result.push({
        tag,
        count,
        group: attachedGroup,
        hasConflict
      });
    }
    for (const group of groups) {
      const normalized = group.primaryTag.replace(/^#/, "").toLowerCase();
      if (!addedPrimaries.has(normalized)) {
        result.push({
          tag: group.primaryTag,
          count: 0,
          group,
          hasConflict: conflictGroupIds.has(group.id)
        });
      }
    }
    const filtered = this.filterBySearch(result);
    filtered.sort((a, b) => this.compareTags(a, b));
    return filtered;
  }
  /**
   * Filter the display list by the current search query.
   * Matches against tag name (without '#', case-insensitive, substring)
   * and alias names in the group.
   */
  filterBySearch(list) {
    if (!this.searchQuery.trim()) {
      return list;
    }
    const query = this.searchQuery.trim().toLowerCase();
    return list.filter((item) => {
      const tagName = item.tag.replace(/^#/, "").toLowerCase();
      if (tagName.includes(query)) {
        return true;
      }
      if (item.group) {
        for (const alias of item.group.aliases) {
          const aliasName = alias.replace(/^#/, "").toLowerCase();
          if (aliasName.includes(query)) {
            return true;
          }
        }
      }
      return false;
    });
  }
  /**
   * Compare two DisplayTag items for sorting based on the current sort mode.
   */
  compareTags(a, b) {
    var _a, _b, _c, _d;
    switch (this.sortMode) {
      case "name-desc":
        return b.tag.localeCompare(a.tag);
      case "count-desc":
        return b.count - a.count;
      case "alias-desc":
        return ((_b = (_a = b.group) == null ? void 0 : _a.aliases.length) != null ? _b : 0) - ((_d = (_c = a.group) == null ? void 0 : _c.aliases.length) != null ? _d : 0);
      default:
        return a.tag.localeCompare(b.tag);
    }
  }
  // ──────────────────────────────────────────────
  //  Tag List Rendering
  // ──────────────────────────────────────────────
  /**
   * Render the full tag list into the scrollable container.
   * Each item shows tag name, count badge, alias preview, and expand/collapse.
   */
  renderTagList(displayList) {
    if (!this.listContainer)
      return;
    this.listContainer.empty();
    if (displayList.length === 0) {
      this.listContainer.createDiv({
        cls: "tag-aliases-sidebar-empty",
        text: this.searchQuery ? "No tags match your search." : "No tags found in vault."
      });
      return;
    }
    for (const item of displayList) {
      this.renderTagItem(item);
    }
  }
  /**
   * Render a single tag item row (collapsed or expanded).
   */
  renderTagItem(item) {
    if (!this.listContainer)
      return;
    const isExpanded = this.expandedTag === item.tag;
    const hasGroup = item.group !== null;
    const itemEl = this.listContainer.createDiv({
      cls: "tag-aliases-sidebar-item"
    });
    if (hasGroup)
      itemEl.addClass("is-group");
    if (isExpanded)
      itemEl.addClass("is-expanded");
    if (item.hasConflict)
      itemEl.addClass("tag-aliases-sidebar-item-conflict");
    itemEl.addEventListener("click", () => {
      this.expandedTag = isExpanded ? null : item.tag;
      this.refresh();
    });
    const topRow = itemEl.createDiv("tag-aliases-sidebar-item-top");
    const indicator = hasGroup ? isExpanded ? "\u25BE" : "\u25B8" : "\xB7";
    topRow.createSpan({ cls: "tag-aliases-sidebar-indicator", text: indicator });
    topRow.createSpan({ cls: "tag-aliases-sidebar-tag-name", text: item.tag.replace(/^#/, "") });
    if (item.count > 0) {
      topRow.createSpan({ cls: "tag-aliases-sidebar-count", text: `\xD7${item.count}` });
    }
    if (hasGroup && !isExpanded && item.group) {
      const aliasNames = item.group.aliases.map((a) => a.replace(/^#/, ""));
      if (aliasNames.length > 0) {
        itemEl.createDiv({
          cls: "tag-aliases-sidebar-aliases-preview",
          text: aliasNames.join(", ")
        });
      }
    }
    if (isExpanded) {
      if (item.group) {
        this.renderEditPanel(itemEl, item.group, item.tag);
      } else {
        this.renderCreatePanel(itemEl, item.tag);
      }
    }
  }
  // ──────────────────────────────────────────────
  //  Expanded: Edit Existing Group
  // ──────────────────────────────────────────────
  /**
   * Render the expanded edit panel for an existing alias group.
   * Shows alias rows with delete buttons, an add-alias input, and a delete group button.
   */
  renderEditPanel(parent, group, _tag) {
    const panel = parent.createDiv("tag-aliases-sidebar-edit-panel");
    for (const alias of group.aliases) {
      const aliasRow = panel.createDiv("tag-aliases-sidebar-alias-row");
      aliasRow.createSpan({ text: alias.replace(/^#/, "") });
      const deleteBtn = aliasRow.createEl("button", {
        cls: "tag-aliases-sidebar-alias-delete",
        text: "\u2715",
        attr: { "aria-label": `Remove alias ${alias}` }
      });
      deleteBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        void this.handleDeleteAlias(group, alias);
      });
    }
    const addRow = panel.createDiv("tag-aliases-sidebar-add-row");
    const addInput = addRow.createEl("input", {
      attr: { type: "text", placeholder: "Add alias..." }
    });
    const addBtn = addRow.createEl("button", {
      text: "\uFF0B",
      attr: { "aria-label": "Add alias" }
    });
    const errorEl = panel.createDiv("tag-aliases-sidebar-error");
    const doAdd = async () => {
      const rawValue = addInput.value.trim();
      if (!rawValue)
        return;
      const newAlias = rawValue.startsWith("#") ? rawValue : "#" + rawValue;
      const error = await this.handleAddAlias(group, newAlias, errorEl);
      if (!error) {
        addInput.value = "";
      }
    };
    addBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      void doAdd();
    });
    addInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.stopPropagation();
        void doAdd();
      }
    });
    this.registerAliasInputHandlers(addInput);
    const deleteGroupBtn = panel.createEl("button", {
      cls: "tag-aliases-sidebar-delete-group",
      text: "Delete group"
    });
    deleteGroupBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      void this.handleDeleteGroup(group);
    });
  }
  // ──────────────────────────────────────────────
  //  Expanded: Create New Group
  // ──────────────────────────────────────────────
  /**
   * Render the expanded panel for a standalone tag (no group yet).
   * Allows creating a new alias group by adding the first alias.
   */
  renderCreatePanel(parent, tag) {
    const panel = parent.createDiv("tag-aliases-sidebar-edit-panel");
    panel.createDiv({
      cls: "tag-aliases-sidebar-no-aliases",
      text: "No aliases yet"
    });
    const addRow = panel.createDiv("tag-aliases-sidebar-add-row");
    const addInput = addRow.createEl("input", {
      attr: { type: "text", placeholder: "Add alias..." }
    });
    const addBtn = addRow.createEl("button", {
      text: "\uFF0B",
      attr: { "aria-label": "Add alias" }
    });
    const errorEl = panel.createDiv("tag-aliases-sidebar-error");
    const doCreate = async () => {
      const rawValue = addInput.value.trim();
      if (!rawValue)
        return;
      const newAlias = rawValue.startsWith("#") ? rawValue : "#" + rawValue;
      const primaryTag = tag.startsWith("#") ? tag : "#" + tag;
      const error = await this.handleCreateGroup(primaryTag, newAlias, errorEl);
      if (!error) {
        addInput.value = "";
      }
    };
    addBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      void doCreate();
    });
    addInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.stopPropagation();
        void doCreate();
      }
    });
    this.registerAliasInputHandlers(addInput);
    const cancelBtn = panel.createEl("button", {
      cls: "tag-aliases-sidebar-cancel",
      text: "Cancel"
    });
    cancelBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.expandedTag = null;
      this.refresh();
    });
  }
  // ──────────────────────────────────────────────
  //  Data Mutation Handlers
  // ──────────────────────────────────────────────
  /**
   * Handle deleting a single alias from a group.
   * If the alias is the last one, the entire group is removed.
   */
  async handleDeleteAlias(group, alias) {
    const newAliases = group.aliases.filter((a) => a !== alias);
    let updatedGroups;
    if (newAliases.length === 0) {
      updatedGroups = this.plugin.aliasManager.removeGroup(group.id);
    } else {
      updatedGroups = this.plugin.aliasManager.updateGroup(group.id, { aliases: newAliases });
    }
    if (updatedGroups) {
      this.plugin.settings.aliasGroups = updatedGroups;
      await this.plugin.saveSettings();
    }
    this.refresh();
  }
  /**
   * Handle adding a new alias to an existing group.
   * Validates the alias before adding. Returns true if an error occurred.
   */
  async handleAddAlias(group, newAlias, errorEl) {
    errorEl.textContent = "";
    const tempGroup = {
      ...group,
      aliases: [...group.aliases, newAlias]
    };
    const validationError = this.plugin.aliasManager.validate(tempGroup, group.id);
    if (validationError) {
      errorEl.textContent = validationError;
      return true;
    }
    const updatedGroups = this.plugin.aliasManager.updateGroup(group.id, {
      aliases: tempGroup.aliases
    });
    if (updatedGroups) {
      this.plugin.settings.aliasGroups = updatedGroups;
      await this.plugin.saveSettings();
    }
    this.refresh();
    return false;
  }
  /**
   * Handle creating a new alias group for a standalone tag.
   * Validates the group before creating. Returns true if an error occurred.
   */
  async handleCreateGroup(primaryTag, firstAlias, errorEl) {
    errorEl.textContent = "";
    const newGroup = {
      id: this.plugin.aliasManager.generateId(),
      primaryTag,
      aliases: [firstAlias]
    };
    const validationError = this.plugin.aliasManager.validate(newGroup);
    if (validationError) {
      errorEl.textContent = validationError;
      return true;
    }
    const updatedGroups = this.plugin.aliasManager.addGroup(newGroup);
    this.plugin.settings.aliasGroups = updatedGroups;
    await this.plugin.saveSettings();
    this.refresh();
    return false;
  }
  /**
   * Handle deleting an entire alias group.
   * Shows a confirmation dialog before proceeding.
   */
  async handleDeleteGroup(group) {
    const tagName = group.primaryTag.replace(/^#/, "");
    const confirmed = await showConfirmModal(
      this.app,
      "Delete alias group",
      `Delete alias group "${tagName}"? This will remove all ${group.aliases.length} alias(es). The primary tag will remain as a standalone tag.`
    );
    if (!confirmed)
      return;
    const updatedGroups = this.plugin.aliasManager.removeGroup(group.id);
    if (updatedGroups) {
      this.plugin.settings.aliasGroups = updatedGroups;
      await this.plugin.saveSettings();
    }
    this.expandedTag = null;
    this.refresh();
  }
};
function showConfirmModal(app, title, message) {
  return new Promise((resolve) => {
    let resolved = false;
    const modal = new class extends import_obsidian4.Modal {
      onOpen() {
        const { contentEl } = this;
        contentEl.createEl("h3", { text: title });
        contentEl.createEl("p", { text: message });
        const btnRow = contentEl.createDiv({ cls: "tag-aliases-button-row" });
        const cancelBtn = btnRow.createEl("button", { text: "Cancel" });
        cancelBtn.addEventListener("click", () => {
          resolved = true;
          resolve(false);
          this.close();
        });
        const confirmBtn = btnRow.createEl("button", {
          text: "Delete",
          cls: "mod-warning"
        });
        confirmBtn.addEventListener("click", () => {
          resolved = true;
          resolve(true);
          this.close();
        });
      }
      onClose() {
        this.contentEl.empty();
        if (!resolved) {
          resolved = true;
          resolve(false);
        }
      }
    }(app);
    modal.open();
  });
}

// src/main.ts
init_BatchMigration();
function isAliasGroup(value) {
  if (!value || typeof value !== "object")
    return false;
  const group = value;
  return typeof group.id === "string" && typeof group.primaryTag === "string" && Array.isArray(group.aliases) && group.aliases.every((alias) => typeof alias === "string") && (group.description === void 0 || typeof group.description === "string");
}
function normalizeSettings(data) {
  const defaults = {
    aliasGroups: [...DEFAULT_SETTINGS.aliasGroups],
    autoReplace: DEFAULT_SETTINGS.autoReplace
  };
  if (!data || typeof data !== "object") {
    return defaults;
  }
  const record = data;
  return {
    aliasGroups: Array.isArray(record.aliasGroups) ? record.aliasGroups.filter(isAliasGroup) : defaults.aliasGroups,
    autoReplace: typeof record.autoReplace === "boolean" ? record.autoReplace : defaults.autoReplace
  };
}
var TagAliasesPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    /** Current plugin settings. */
    this.settings = DEFAULT_SETTINGS;
    /** Core alias management: indexing, lookup, CRUD. */
    this.aliasManager = new AliasManager();
    /** Guard flag to prevent recursive auto-replace triggers. */
    this.isReplacing = false;
    /** Reference to our EditorSuggest instance. */
    this.tagAliasSuggest = null;
    /** Saved built-in tag suggest, restored on unload. */
    this.removedBuiltInSuggest = null;
    /** Index of the removed built-in suggest, for restoring at the same position. */
    this.removedBuiltInSuggestIndex = -1;
  }
  /**
   * Plugin lifecycle: called when the plugin is loaded.
   * Registers settings, commands, editor suggest, and event listeners.
   */
  async onload() {
    await this.loadSettings();
    this.aliasManager.buildIndex(this.settings.aliasGroups);
    this.addSettingTab(new TagAliasesSettingTab(this.app, this));
    this.tagAliasSuggest = new TagAliasSuggest(this.app, this.aliasManager);
    this.registerEditorSuggest(this.tagAliasSuggest);
    this.app.workspace.onLayoutReady(() => {
      this.overrideBuiltInTagSuggest();
    });
    this.registerAutoReplace();
    this.registerView(VIEW_TYPE_TAG_ALIASES, (leaf) => new TagSidebarView(leaf, this));
    this.addRibbonIcon("tags", "Open sidebar", () => {
      void this.activateSidebarView();
    });
    this.addCommand({
      id: "open-sidebar",
      name: "Open sidebar",
      callback: () => {
        void this.activateSidebarView();
      }
    });
    this.addCommand({
      id: "migrate-tags",
      name: "Scan & replace alias tags",
      callback: async () => {
        const migration = new BatchMigration(this.app, this.aliasManager);
        await migration.run();
      }
    });
  }
  /**
   * Plugin lifecycle: called when the plugin is unloaded.
   * Restores the built-in tag suggest if it was removed.
   */
  onunload() {
    this.restoreBuiltInTagSuggest();
  }
  /**
   * Load settings from disk, merging with defaults for any missing fields.
   */
  async loadSettings() {
    const data = await this.loadData();
    this.settings = normalizeSettings(data);
  }
  /**
   * Persist current settings to disk.
   */
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Open or reveal the Tag Aliases sidebar panel.
   * Creates a new leaf in the right sidebar if none exists.
   */
  async activateSidebarView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_TAG_ALIASES)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (!rightLeaf)
        return;
      await rightLeaf.setViewState({ type: VIEW_TYPE_TAG_ALIASES, active: true });
      leaf = rightLeaf;
    }
    await workspace.revealLeaf(leaf);
  }
  /**
   * Override the built-in tag suggest by:
   * 1. Finding and removing the built-in tag suggest from the internal suggests array
   * 2. Ensuring our suggest is checked first (moved to front of array)
   *
   * This uses Obsidian's internal API (editorSuggest.suggests).
   * The built-in suggest is restored on plugin unload.
   */
  overrideBuiltInTagSuggest() {
    var _a;
    try {
      const workspace = this.app.workspace;
      const editorSuggest = workspace.editorSuggest;
      if (!(editorSuggest == null ? void 0 : editorSuggest.suggests)) {
        console.warn("[TagAliases] Cannot access editorSuggest.suggests");
        return;
      }
      const suggests = editorSuggest.suggests;
      for (let i = 0; i < suggests.length; i++) {
        const s = suggests[i];
        if (s === this.tagAliasSuggest)
          continue;
        const name = ((_a = s.constructor) == null ? void 0 : _a.name) || "";
        if (this.looksLikeTagSuggest(name)) {
          this.removedBuiltInSuggest = suggests.splice(i, 1)[0];
          this.removedBuiltInSuggestIndex = i;
          break;
        }
      }
      const ourIndex = suggests.findIndex(
        (s) => s === this.tagAliasSuggest
      );
      if (ourIndex > 0) {
        const [ours] = suggests.splice(ourIndex, 1);
        suggests.unshift(ours);
      }
    } catch (err) {
      console.error("[TagAliases] Failed to override built-in tag suggest:", err);
    }
  }
  /**
   * Heuristic to identify the built-in tag suggest.
   * Checks constructor name and internal properties.
   */
  looksLikeTagSuggest(constructorName) {
    const nameLower = constructorName.toLowerCase();
    return nameLower.includes("tag") && !nameLower.includes("tagalias");
  }
  /**
   * Restore the built-in tag suggest on plugin unload.
   */
  restoreBuiltInTagSuggest() {
    if (!this.removedBuiltInSuggest)
      return;
    try {
      const workspace = this.app.workspace;
      const editorSuggest = workspace.editorSuggest;
      if (!(editorSuggest == null ? void 0 : editorSuggest.suggests))
        return;
      const suggests = editorSuggest.suggests;
      const insertAt = Math.min(this.removedBuiltInSuggestIndex, suggests.length);
      suggests.splice(insertAt, 0, this.removedBuiltInSuggest);
      this.removedBuiltInSuggest = null;
      this.removedBuiltInSuggestIndex = -1;
    } catch (err) {
      console.error("[TagAliases] Failed to restore built-in tag suggest:", err);
    }
  }
  /**
   * Register the auto-replace mechanism.
   *
   * Only replaces the tag the user JUST finished typing (near the cursor),
   * not all alias tags in the file. Old alias tags elsewhere in the file
   * are left untouched — use batch migration for those.
   *
   * Uses the Editor API for replacement, which supports Ctrl+Z undo.
   */
  registerAutoReplace() {
    let lastChangedFile = null;
    const debouncedReplace = (0, import_obsidian5.debounce)(
      () => {
        if (lastChangedFile) {
          this.processAutoReplace(lastChangedFile);
        }
        lastChangedFile = null;
      },
      100,
      true
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        if (!this.settings.autoReplace || this.isReplacing) {
          return;
        }
        lastChangedFile = file;
        debouncedReplace();
      })
    );
  }
  /**
   * Check the tag the user just finished typing (near cursor).
   * If it's an alias, replace it with the primary tag via Editor API.
   *
   * A tag is considered "just finished" when the text before the cursor
   * matches: #tagname + whitespace (space, tab, newline equivalent).
   */
  processAutoReplace(changedFile) {
    try {
      const workspace = this.app.workspace;
      const activeEditor = workspace.activeEditor;
      const editor = activeEditor == null ? void 0 : activeEditor.editor;
      if (!editor)
        return;
      const activeFile = activeEditor == null ? void 0 : activeEditor.file;
      if (!activeFile || activeFile.path !== changedFile.path) {
        return;
      }
      const cursor = editor.getCursor();
      const line = editor.getLine(cursor.line);
      const textBeforeCursor = line.substring(0, cursor.ch);
      const match = textBeforeCursor.match(
        /(?:^|\s)(#[\p{L}\p{N}_\-/]+)\s+$/u
      );
      if (!match || match.index === void 0)
        return;
      const tag = match[1];
      if (!this.aliasManager.isAlias(tag))
        return;
      const primaryTag = this.aliasManager.getPrimaryTag(tag);
      const fullMatchStart = match.index;
      const tagStartInMatch = match[0].indexOf("#");
      const tagStartCh = fullMatchStart + tagStartInMatch;
      const tagEndCh = tagStartCh + tag.length;
      this.isReplacing = true;
      editor.replaceRange(
        primaryTag,
        { line: cursor.line, ch: tagStartCh },
        { line: cursor.line, ch: tagEndCh }
      );
      activeWindow.setTimeout(() => {
        this.isReplacing = false;
      }, 500);
    } catch (err) {
      console.error("[TagAliases] Auto-replace error:", err);
      this.isReplacing = false;
    }
  }
};

/* nosourcemap */