/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CanvasLinkToGroupPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var CanvasLinkToGroupPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.addCopyToClipboardMenuItem = (menu, node) => {
      var _a;
      if (((_a = node.unknownData) == null ? void 0 : _a.type) !== "group") {
        return;
      }
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.ItemView);
      if (!activeView || activeView.getViewType() !== "canvas")
        return;
      const canvasFile = activeView.file;
      if (!canvasFile)
        return;
      menu.addItem((item) => {
        item.setTitle("Copy link to group").setIcon("link").onClick(() => {
          const canvasPath = canvasFile.name;
          const groupName = node.label;
          const linkText = `[[${canvasPath}#${groupName}]]`;
          void navigator.clipboard.writeText(linkText);
          new import_obsidian.Notice(`Copied link to group "${groupName}"`);
        });
      });
    };
  }
  onload() {
    this.registerDomEvent(activeDocument, "mousedown", (evt) => {
      var _a;
      if (evt.button !== 0 && evt.button !== 1)
        return;
      const target = evt.target;
      const linkEl = target.closest(".cm-hmd-internal-link, .internal-link, a[data-href]");
      if (!linkEl)
        return;
      const linkText = linkEl.getAttribute("data-href") || linkEl.textContent;
      if (!linkText)
        return;
      const isAliasedLink = linkEl.classList.contains("cm-link-alias") || ((_a = linkEl.parentElement) == null ? void 0 : _a.classList.contains("cm-link-alias"));
      if (isAliasedLink) {
        const currentFile = this.app.workspace.getActiveFile();
        if (!currentFile)
          return;
        const fileCache = this.app.metadataCache.getFileCache(currentFile);
        const links = (fileCache == null ? void 0 : fileCache.links) || [];
        for (const linkCache of links) {
          const displayText = linkCache.displayText || linkCache.link;
          if (displayText === linkText && linkCache.link.includes(".canvas#")) {
            evt.preventDefault();
            evt.stopImmediatePropagation();
            const sourcePath = this.getSourcePath(target);
            const openInNewTab = evt.button === 1 || evt.ctrlKey || evt.metaKey;
            void this.handleCanvasLink(linkCache.link, sourcePath, openInNewTab);
            break;
          }
        }
      } else if (linkText.includes(".canvas#")) {
        evt.preventDefault();
        evt.stopImmediatePropagation();
        const sourcePath = this.getSourcePath(target);
        const openInNewTab = evt.button === 1 || evt.ctrlKey || evt.metaKey;
        void this.handleCanvasLink(linkText, sourcePath, openInNewTab);
      }
    }, { capture: true });
    const workspace = this.app.workspace;
    this.registerEvent(
      workspace.on("canvas:node-menu", this.addCopyToClipboardMenuItem)
    );
    this.addCommand({
      id: "copy-canvas-group-link",
      name: "Copy link to selected group",
      checkCallback: (checking) => {
        var _a, _b;
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.ItemView);
        if ((activeView == null ? void 0 : activeView.getViewType()) !== "canvas") {
          return false;
        }
        if (checking) {
          return true;
        }
        const canvasView = activeView;
        const selection = (_a = canvasView.canvas) == null ? void 0 : _a.selection;
        if (!selection || selection.size !== 1) {
          new import_obsidian.Notice("Please select a single group to copy its link.");
          return;
        }
        const selectedNode = selection.values().next().value;
        if (((_b = selectedNode == null ? void 0 : selectedNode.unknownData) == null ? void 0 : _b.type) !== "group") {
          new import_obsidian.Notice("The selected item is not a group.");
          return;
        }
        const canvasPath = canvasView.file.name;
        const groupName = selectedNode.label;
        const linkText = `[[${canvasPath}#${groupName}]]`;
        void navigator.clipboard.writeText(linkText);
        new import_obsidian.Notice(`Copied link to group "${groupName}"`);
      }
    });
    this.registerEditorSuggest(new GroupSuggest(this.app));
  }
  getSourcePath(target) {
    const sourceElement = target.closest("[data-source-path]");
    if (sourceElement) {
      return sourceElement.getAttribute("data-source-path") || "";
    }
    const activeFile = this.app.workspace.getActiveFile();
    return activeFile ? activeFile.path : "";
  }
  async handleCanvasLink(linkText, sourcePath, newLeaf) {
    const parts = linkText.split("#");
    if (parts.length < 2) {
      return;
    }
    const [canvasPath, groupName] = parts;
    await this.app.workspace.openLinkText(canvasPath, sourcePath, newLeaf);
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.ItemView);
    if (activeView) {
      this.jumpToGroup(groupName, activeView.leaf);
    }
  }
  jumpToGroup(groupName, leaf) {
    const canvasView = leaf.view;
    let retries = 50;
    const intervalId = window.setInterval(() => {
      retries--;
      const canvas = canvasView.canvas;
      if (!canvas || !canvas.nodes || retries <= 0) {
        window.clearInterval(intervalId);
        return;
      }
      const groupNodes = Array.from(canvas.nodes.values()).filter(
        (node) => {
          var _a;
          return ((_a = node.unknownData) == null ? void 0 : _a.type) === "group" && node.label === groupName;
        }
      );
      if (groupNodes.length > 0) {
        window.clearInterval(intervalId);
        if (groupNodes.length > 1) {
          new import_obsidian.Notice(`Found ${groupNodes.length} groups named "${groupName}". Jumping to the first one.`);
        }
        const groupNode = groupNodes[0];
        canvas.selectOnly(groupNode);
        canvas.zoomToSelection();
      }
    }, 100);
    this.registerInterval(intervalId);
  }
};
var GroupSuggest = class extends import_obsidian.EditorSuggest {
  constructor(app) {
    super(app);
    this.app = app;
  }
  onTrigger(cursor, editor, _file) {
    const line = editor.getLine(cursor.line);
    const sub = line.substring(0, cursor.ch);
    const match = sub.match(/\[\[([^\]]+\.canvas)#([\w\s]*)$/);
    if (match) {
      return {
        end: cursor,
        start: {
          line: cursor.line,
          ch: sub.lastIndexOf(match[2])
        },
        query: match[2]
      };
    }
    return null;
  }
  async getSuggestions(context) {
    var _a;
    const fileLinkMatch = context.editor.getLine(context.start.line).substring(0, context.start.ch).match(/\[\[([^\]]+\.canvas)#$/);
    if (!fileLinkMatch)
      return [];
    const canvasPath = fileLinkMatch[1];
    const sourcePath = ((_a = context.file) == null ? void 0 : _a.path) || "";
    const canvasFile = this.app.metadataCache.getFirstLinkpathDest(canvasPath, sourcePath);
    if (!canvasFile)
      return [];
    try {
      const fileContent = await this.app.vault.cachedRead(canvasFile);
      const canvasData = JSON.parse(fileContent);
      if (!canvasData.nodes || !Array.isArray(canvasData.nodes))
        return [];
      return canvasData.nodes.filter((node) => node.type === "group" && node.label).map((node) => node.label).filter(
        (label) => label.toLowerCase().includes(context.query.toLowerCase())
      );
    } catch (e) {
      console.error("Canvas Link to Group: Error reading or parsing canvas file for suggestions.", e);
      return [];
    }
  }
  renderSuggestion(suggestion, el) {
    el.setText(suggestion);
  }
  selectSuggestion(suggestion, _evt) {
    if (!this.context)
      return;
    const activeEditor = this.context.editor;
    activeEditor.replaceRange(suggestion, this.context.start, this.context.end);
  }
};

/* nosourcemap */