var g=Object.defineProperty;var A=Object.getOwnPropertyDescriptor;var T=Object.getOwnPropertyNames;var S=Object.prototype.hasOwnProperty;var v=(s,n)=>{for(var t in n)g(s,t,{get:n[t],enumerable:!0})},b=(s,n,t,e)=>{if(n&&typeof n=="object"||typeof n=="function")for(let i of T(n))!S.call(s,i)&&i!==t&&g(s,i,{get:()=>n[i],enumerable:!(e=A(n,i))||e.enumerable});return s};var f=s=>b(g({},"__esModule",{value:!0}),s);var $={};v($,{default:()=>l});module.exports=f($);var a=require("obsidian"),h=require("child_process"),m={terminalApp:"terminal",agentCommand:"claude"},l=class extends a.Plugin{constructor(){super(...arguments);this.settings=m}async onload(){if(process.platform!=="darwin"){new a.Notice("Agents plugin requires macOS.");return}await this.loadSettings(),this.registerEvent(this.app.workspace.on("file-menu",(t,e)=>{t.addItem(i=>{i.setTitle("Open with AI Agent").setIcon("terminal").onClick(()=>this.launchAgent(e))})})),this.addSettingTab(new o(this.app,this))}getVaultBasePath(){var e;return(e=this.app.vault.adapter.basePath)!=null?e:null}launchAgent(t){let e=this.getVaultBasePath();if(!e){new a.Notice("Could not determine vault path");return}let i,p;if(t instanceof a.TFile){let r=t.parent?t.parent.path:"";i=r?`${e}/${r}`:e;let w=t.path;p=` ${JSON.stringify(`We are going to work on ${w}. Please prompt me for the next instruction.`)}`}else if(t instanceof a.TFolder)i=t.path==="/"?e:`${e}/${t.path}`,p="";else return;let u=this.settings.agentCommand,d=`cd ${this.shellQuote(i)} && ${u}${p}`,c;this.settings.terminalApp==="iterm2"?c=this.buildITermScript(d):c=this.buildTerminalScript(d),(0,h.execFile)("osascript",["-e",c],r=>{r&&new a.Notice(`Failed to launch terminal: ${r.message}`)})}shellQuote(t){return JSON.stringify(t)}buildTerminalScript(t){return`tell application "Terminal"
  activate
  do script "${t.replace(/\\/g,"\\\\").replace(/"/g,'\\"')}"
end tell`}buildITermScript(t){return`tell application "iTerm2"
  create window with default profile
  tell current session of current window
    write text "${t.replace(/\\/g,"\\\\").replace(/"/g,'\\"')}"
  end tell
end tell`}async loadSettings(){this.settings=Object.assign({},m,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}},o=class extends a.PluginSettingTab{constructor(n,t){super(n,t),this.plugin=t}display(){let{containerEl:n}=this;n.empty(),new a.Setting(n).setName("Terminal application").setDesc("Which terminal to open the AI agent in").addDropdown(t=>t.addOption("terminal","Terminal.app").addOption("iterm2","iTerm2").setValue(this.plugin.settings.terminalApp).onChange(async e=>{this.plugin.settings.terminalApp=e,await this.plugin.saveSettings()})),new a.Setting(n).setName("Agent command").setDesc("Command to launch the AI agent (e.g., claude, codex)").addText(t=>t.setPlaceholder("claude").setValue(this.plugin.settings.agentCommand).onChange(async e=>{this.plugin.settings.agentCommand=e||"claude",await this.plugin.saveSettings()}))}};

/* nosourcemap */