/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FolderBasesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_BASE_TEMPLATE = `filters:
  and:
    - file.inFolder("{{folder_path}}")
    - file.ext == "md"
views:
  - type: table
    name: Table
`;
var DEFAULT_SETTINGS = {
  baseNameTemplate: "{{folder_name}}.base",
  clickTrigger: "click",
  modifierKey: "ctrl",
  createOnModifierClick: true,
  collapseOnOpen: false,
  defaultBaseTemplate: DEFAULT_BASE_TEMPLATE,
  folderFilterMode: "all",
  folderPatterns: "",
  matchSubfolders: true,
  openLocation: "tab",
  indicatorStyle: "italic"
};
function paneArgForOpenLocation(loc) {
  switch (loc) {
    case "new-tab":
      return "tab";
    case "split":
      return "split";
    case "tab":
    case "reuse":
    default:
      return false;
  }
}
function renderTemplate(template, folderName, folderPath) {
  return template.replace(/\{\{\s*folder_name\s*\}\}/g, folderName).replace(/\{\{\s*folder_path\s*\}\}/g, folderPath);
}
function basePathFor(folderName, folderPath, template) {
  const rendered = renderTemplate(template, folderName, folderPath);
  const joined = folderPath ? `${folderPath}/${rendered}` : rendered;
  return (0, import_obsidian.normalizePath)(joined);
}
function globToRegExp(pattern) {
  const escaped = pattern.replace(/[.+?^${}()|[\]\\]/g, "\\$&");
  const source = escaped.replace(
    /\*\*|\*/g,
    (match) => match === "**" ? ".*" : "[^/]*"
  );
  return new RegExp(`^${source}$`);
}
function ancestorChain(folderPath) {
  const chain = [];
  let current = folderPath;
  while (current) {
    chain.push(current);
    const slash = current.lastIndexOf("/");
    if (slash < 0)
      break;
    current = current.slice(0, slash);
  }
  return chain;
}
function parsePatterns(patternsText) {
  return patternsText.split("\n").map((line) => line.trim()).filter((line) => line.length > 0).map((line) => (0, import_obsidian.normalizePath)(line));
}
function folderMatchesPatterns(folderPath, patternsText, matchSubfolders) {
  const patterns = parsePatterns(patternsText);
  if (patterns.length === 0)
    return false;
  const candidates = matchSubfolders ? ancestorChain(folderPath) : [folderPath];
  return patterns.some((pattern) => {
    const re = globToRegExp(pattern);
    return candidates.some((candidate) => re.test(candidate));
  });
}
function isFolderEnabled(folderPath, settings) {
  if (settings.folderFilterMode === "all")
    return true;
  if (parsePatterns(settings.folderPatterns).length === 0)
    return true;
  const matched = folderMatchesPatterns(
    folderPath,
    settings.folderPatterns,
    settings.matchSubfolders
  );
  return settings.folderFilterMode === "exclude" ? !matched : matched;
}
var FolderBasesSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Base filename template").setDesc(
      "Path of a folder's base, relative to the folder. Tokens: {{folder_name}}, {{folder_path}}."
    ).addText(
      (text) => text.setPlaceholder("{{folder_name}}.base").setValue(this.plugin.settings.baseNameTemplate).onChange(async (value) => {
        this.plugin.settings.baseNameTemplate = value.trim() || DEFAULT_SETTINGS.baseNameTemplate;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Click trigger").setDesc(
      "How a folder opens its base. 'Plain click' opens on a normal click; 'Modifier + click' requires holding the modifier key."
    ).addDropdown(
      (dd) => dd.addOption("click", "Plain click").addOption("modifier", "Modifier + click").setValue(this.plugin.settings.clickTrigger).onChange(async (value) => {
        this.plugin.settings.clickTrigger = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Modifier key").setDesc(
      "Modifier used for the 'Modifier + click' trigger and for creating a base on click."
    ).addDropdown(
      (dd) => dd.addOption("ctrl", "Ctrl / Cmd").addOption("alt", "Alt / Option").setValue(this.plugin.settings.modifierKey).onChange(async (value) => {
        this.plugin.settings.modifierKey = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Create base on modifier + click").setDesc(
      "When a folder has no base, a modifier + click creates one from the default template and opens it."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.createOnModifierClick).onChange(async (value) => {
        this.plugin.settings.createOnModifierClick = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Toggle folder when opening").setDesc(
      "When a plain click opens a base, also expand/collapse the folder as usual. If off, the folder stays put."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.collapseOnOpen).onChange(async (value) => {
        this.plugin.settings.collapseOnOpen = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Open base in").setDesc(
      "Where a base opens when triggered. 'Reuse existing tab' focuses an already-open tab if there is one. Middle-clicking a folder always opens in a new tab."
    ).addDropdown(
      (dd) => dd.addOption("tab", "Current tab").addOption("new-tab", "New tab").addOption("split", "Split right").addOption("reuse", "Reuse existing tab").setValue(this.plugin.settings.openLocation).onChange(async (value) => {
        this.plugin.settings.openLocation = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Folder base indicator").setDesc(
      "How folders that have a base are marked in the file explorer."
    ).addDropdown(
      (dd) => dd.addOption("none", "None").addOption("italic", "Italic").addOption("bold", "Bold").addOption("accent", "Accent color").addOption("dot", "Dot").addOption("icon", "Icon").setValue(this.plugin.settings.indicatorStyle).onChange(async (value) => {
        this.plugin.settings.indicatorStyle = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default base content").setDesc(
      "YAML written into newly created .base files. Tokens: {{folder_name}}, {{folder_path}}."
    ).addTextArea((area) => {
      area.setValue(this.plugin.settings.defaultBaseTemplate).onChange(async (value) => {
        this.plugin.settings.defaultBaseTemplate = value || DEFAULT_SETTINGS.defaultBaseTemplate;
        await this.plugin.saveSettings();
      });
      area.inputEl.rows = 8;
      area.inputEl.addClass("folder-bases-template-input");
    });
    new import_obsidian.Setting(containerEl).setName("Folder filter").setDesc(
      "Which folders respond to clicks. Pattern matching is case-sensitive."
    ).addDropdown(
      (dd) => dd.addOption("all", "All folders").addOption("exclude", "Exclude these folders").addOption("include", "Only these folders").setValue(this.plugin.settings.folderFilterMode).onChange(async (value) => {
        this.plugin.settings.folderFilterMode = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.folderFilterMode !== "all") {
      new import_obsidian.Setting(containerEl).setName("Folder patterns").setDesc(
        "One folder path per line. Use * as a wildcard, e.g. */drafts. Example: Archive, Templates."
      ).addTextArea((area) => {
        area.setValue(this.plugin.settings.folderPatterns).onChange(async (value) => {
          this.plugin.settings.folderPatterns = value;
          await this.plugin.saveSettings();
        });
        area.inputEl.rows = 5;
        area.inputEl.addClass("folder-bases-template-input");
      });
      new import_obsidian.Setting(containerEl).setName("Match subfolders").setDesc(
        "A pattern also matches folders nested inside it (e.g. Archive covers Archive/2024)."
      ).addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.matchSubfolders).onChange(async (value) => {
          this.plugin.settings.matchSubfolders = value;
          await this.plugin.saveSettings();
        })
      );
    }
  }
};

// src/main.ts
var FILE_EXPLORER_VIEW_TYPE = "file-explorer";
var HAS_BASE_CLASS = "has-folder-base";
var INDICATOR_CLASS_PREFIX = "folder-bases-indicator-";
var INDICATOR_CLASSES = ["italic", "bold", "accent", "dot", "icon"].map(
  (style) => INDICATOR_CLASS_PREFIX + style
);
var FolderBasesPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    /** Folder paths that should be marked (enabled folder whose base exists). */
    this.markedFolders = /* @__PURE__ */ new Set();
    /** Watches the explorer DOM so indicators survive collapse/expand/scroll. */
    this.explorerObserver = null;
    this.onClick = (evt) => {
      const hit = this.folderFromTitleClick(evt.target);
      if (!hit)
        return;
      const { folder } = hit;
      const modifierHeld = this.isModifierHeld(evt);
      const triggered = this.settings.clickTrigger === "click" ? true : modifierHeld;
      if (!triggered)
        return;
      const basePath = this.basePathForFolder(folder);
      const base = this.app.vault.getAbstractFileByPath(basePath);
      if (base instanceof import_obsidian2.TFile) {
        if (!this.settings.collapseOnOpen) {
          evt.preventDefault();
          evt.stopPropagation();
        }
        void this.openBase(base);
        return;
      }
      if (modifierHeld && this.settings.createOnModifierClick) {
        evt.preventDefault();
        evt.stopPropagation();
        void this.createAndOpenBase(folder);
      }
    };
    this.onAuxClick = (evt) => {
      if (evt.button !== 1)
        return;
      const hit = this.folderFromTitleClick(evt.target);
      if (!hit)
        return;
      const basePath = this.basePathForFolder(hit.folder);
      const base = this.app.vault.getAbstractFileByPath(basePath);
      if (!(base instanceof import_obsidian2.TFile))
        return;
      evt.preventDefault();
      evt.stopPropagation();
      void this.openBase(base, "new-tab");
    };
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new FolderBasesSettingTab(this.app, this));
    this.refreshIndicators = (0, import_obsidian2.debounce)(() => {
      this.rebuildMarkedFolders();
      this.applyIndicators();
    }, 150);
    this.reapplyIndicators = (0, import_obsidian2.debounce)(() => this.applyIndicators(), 50);
    this.app.workspace.onLayoutReady(() => this.installIndicators());
    this.register(() => this.teardownIndicators());
    this.registerDomEvent(document, "click", this.onClick, { capture: true });
    this.registerDomEvent(document, "auxclick", this.onAuxClick, {
      capture: true
    });
    this.registerCommands();
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian2.TFolder))
          return;
        if (!isFolderEnabled(file.path, this.settings))
          return;
        const basePath = this.basePathForFolder(file);
        const existing = this.app.vault.getAbstractFileByPath(basePath);
        if (existing instanceof import_obsidian2.TFile) {
          menu.addItem(
            (item) => item.setTitle("Open folder base").setIcon("layout-grid").onClick(() => void this.openBase(existing))
          );
        } else {
          menu.addItem(
            (item) => item.setTitle("Create folder base").setIcon("layout-grid").onClick(() => void this.createAndOpenBase(file))
          );
        }
      })
    );
  }
  /**
   * Resolve the enabled folder for a click on a `.nav-folder-title`, or null
   * when the target isn't an actionable folder title (chevron, non-folder, or
   * a folder excluded by the filter).
   */
  folderFromTitleClick(target) {
    if (!(target instanceof HTMLElement))
      return null;
    if (target.closest(".nav-folder-collapse-indicator"))
      return null;
    const titleEl = target.closest(".nav-folder-title");
    if (!(titleEl instanceof HTMLElement))
      return null;
    const folderPath = titleEl.getAttribute("data-path");
    if (folderPath === null)
      return null;
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!(folder instanceof import_obsidian2.TFolder))
      return null;
    if (!isFolderEnabled(folder.path, this.settings))
      return null;
    return { titleEl, folder };
  }
  isModifierHeld(evt) {
    if (this.settings.modifierKey === "alt")
      return evt.altKey;
    return evt.ctrlKey || evt.metaKey;
  }
  /** Vault-relative path of the base file for a folder. */
  basePathForFolder(folder) {
    return basePathFor(
      folder.name || folder.path,
      folder.path,
      this.settings.baseNameTemplate
    );
  }
  // --- Persistent "has a base" indicator -------------------------------
  /** Wire up the indicator: initial scan + the listeners that keep it fresh. */
  installIndicators() {
    this.rebuildMarkedFolders();
    this.applyIndicators();
    this.observeExplorers();
    this.registerEvent(this.app.vault.on("create", this.refreshIndicators));
    this.registerEvent(this.app.vault.on("delete", this.refreshIndicators));
    this.registerEvent(this.app.vault.on("rename", this.refreshIndicators));
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.observeExplorers();
        this.reapplyIndicators();
      })
    );
  }
  /** Strip our classes and stop observing (runs on unload). */
  teardownIndicators() {
    var _a;
    (_a = this.explorerObserver) == null ? void 0 : _a.disconnect();
    this.explorerObserver = null;
    for (const container of this.explorerContainers()) {
      container.removeClasses(INDICATOR_CLASSES);
      for (const titleEl of this.folderTitlesIn(container)) {
        titleEl.removeClass(HAS_BASE_CLASS);
      }
    }
  }
  /** Every open file-explorer view container. */
  explorerContainers() {
    return this.app.workspace.getLeavesOfType(FILE_EXPLORER_VIEW_TYPE).map((leaf) => leaf.view.containerEl);
  }
  /** The folder-title elements (with a `data-path`) inside a container. */
  folderTitlesIn(container) {
    return Array.from(
      container.querySelectorAll(
        ".nav-folder-title[data-path]"
      )
    );
  }
  /** Recompute which folders should be marked (enabled + their base exists). */
  rebuildMarkedFolders() {
    this.markedFolders.clear();
    for (const file of this.app.vault.getAllLoadedFiles()) {
      if (!(file instanceof import_obsidian2.TFolder))
        continue;
      if (!isFolderEnabled(file.path, this.settings))
        continue;
      const base = this.app.vault.getAbstractFileByPath(
        this.basePathForFolder(file)
      );
      if (base instanceof import_obsidian2.TFile)
        this.markedFolders.add(file.path);
    }
  }
  /** Reflect the current set + chosen style onto the explorer DOM. */
  applyIndicators() {
    const style = this.settings.indicatorStyle;
    for (const container of this.explorerContainers()) {
      container.removeClasses(INDICATOR_CLASSES);
      if (style !== "none") {
        container.addClass(INDICATOR_CLASS_PREFIX + style);
      }
      for (const titleEl of this.folderTitlesIn(container)) {
        const path = titleEl.getAttribute("data-path");
        const marked = style !== "none" && path !== null && this.markedFolders.has(path);
        titleEl.toggleClass(HAS_BASE_CLASS, marked);
      }
    }
  }
  /**
   * Observe explorer containers for child changes (collapse/expand/scroll) so
   * re-rendered folder titles get re-marked. Observes `childList`/`subtree`
   * only — not attributes — so our own class toggles can't feed back in.
   */
  observeExplorers() {
    if (!this.explorerObserver) {
      this.explorerObserver = new MutationObserver(
        () => this.reapplyIndicators()
      );
    }
    this.explorerObserver.disconnect();
    for (const container of this.explorerContainers()) {
      this.explorerObserver.observe(container, {
        childList: true,
        subtree: true
      });
    }
  }
  async openBase(file, location) {
    const loc = location != null ? location : this.settings.openLocation;
    if (loc === "reuse") {
      const existing = this.findLeafShowingFile(file);
      if (existing) {
        this.app.workspace.setActiveLeaf(existing, { focus: true });
        await this.app.workspace.revealLeaf(existing);
        return;
      }
      await this.app.workspace.getLeaf("tab").openFile(file);
      return;
    }
    await this.app.workspace.getLeaf(paneArgForOpenLocation(loc)).openFile(file);
  }
  /** The first open leaf already showing `file`, or null. */
  findLeafShowingFile(file) {
    let found = null;
    this.app.workspace.iterateAllLeaves((leaf) => {
      var _a;
      if (found)
        return;
      if (((_a = leaf.getViewState().state) == null ? void 0 : _a.file) === file.path)
        found = leaf;
    });
    return found;
  }
  /**
   * Best-effort "active folder": the file explorer's focused item when the
   * explorer is focused, otherwise the active note's parent, else the vault
   * root.
   */
  resolveActiveFolder() {
    var _a, _b;
    const leaf = this.app.workspace.activeLeaf;
    if (leaf && leaf.view.getViewType() === FILE_EXPLORER_VIEW_TYPE) {
      const item = (_b = (_a = leaf.view.tree) == null ? void 0 : _a.focusedItem) == null ? void 0 : _b.file;
      if (item instanceof import_obsidian2.TFolder)
        return item;
      if (item instanceof import_obsidian2.TFile && item.parent instanceof import_obsidian2.TFolder) {
        return item.parent;
      }
    }
    const active = this.app.workspace.getActiveFile();
    if ((active == null ? void 0 : active.parent) instanceof import_obsidian2.TFolder)
      return active.parent;
    return this.app.vault.getRoot();
  }
  /** Reveal a file in the core file-explorer nav pane. */
  revealInExplorer(file) {
    const leaf = this.app.workspace.getLeavesOfType(
      FILE_EXPLORER_VIEW_TYPE
    )[0];
    const view = leaf == null ? void 0 : leaf.view;
    if (view == null ? void 0 : view.revealInFolder) {
      view.revealInFolder(file);
    } else {
      new import_obsidian2.Notice("Folder Bases: file explorer is not available");
    }
  }
  /** The existing base file for the active folder, or null. */
  activeFolderBase() {
    const folder = this.resolveActiveFolder();
    if (!isFolderEnabled(folder.path, this.settings))
      return null;
    const base = this.app.vault.getAbstractFileByPath(
      this.basePathForFolder(folder)
    );
    return base instanceof import_obsidian2.TFile ? base : null;
  }
  registerCommands() {
    this.addCommand({
      id: "open-active-folder-base",
      name: "Open base for the active folder",
      checkCallback: (checking) => {
        const base = this.activeFolderBase();
        if (!base)
          return false;
        if (!checking)
          void this.openBase(base);
        return true;
      }
    });
    this.addCommand({
      id: "create-active-folder-base",
      name: "Create base for the active folder",
      checkCallback: (checking) => {
        const folder = this.resolveActiveFolder();
        if (!isFolderEnabled(folder.path, this.settings))
          return false;
        if (!checking)
          void this.createAndOpenBase(folder);
        return true;
      }
    });
    this.addCommand({
      id: "reveal-active-folder-base",
      name: "Reveal base file in file explorer",
      checkCallback: (checking) => {
        const base = this.activeFolderBase();
        if (!base)
          return false;
        if (!checking)
          this.revealInExplorer(base);
        return true;
      }
    });
    if (import_obsidian2.Platform.isDesktopApp) {
      this.addCommand({
        id: "open-active-folder-base-default-app",
        name: "Open base file in default app",
        checkCallback: (checking) => {
          const base = this.activeFolderBase();
          if (!base)
            return false;
          if (!checking)
            this.app.openWithDefaultApp(base.path);
          return true;
        }
      });
      this.addCommand({
        id: "show-active-folder-base-in-system",
        name: "Show base file in system explorer",
        checkCallback: (checking) => {
          const base = this.activeFolderBase();
          if (!base)
            return false;
          if (!checking)
            this.app.showInFolder(base.path);
          return true;
        }
      });
    }
  }
  async createAndOpenBase(folder) {
    const basePath = this.basePathForFolder(folder);
    const existing = this.app.vault.getAbstractFileByPath(basePath);
    if (existing instanceof import_obsidian2.TFile) {
      await this.openBase(existing);
      return;
    }
    const content = renderTemplate(
      this.settings.defaultBaseTemplate,
      folder.name || folder.path,
      folder.path
    );
    try {
      const created = await this.app.vault.create(basePath, content);
      if (created instanceof import_obsidian2.TFile) {
        new import_obsidian2.Notice(`Created base: ${basePath}`);
        await this.openBase(created);
      }
    } catch (err) {
      new import_obsidian2.Notice(`Folder Bases: could not create ${basePath}`);
      console.error("Folder Bases: failed to create base", basePath, err);
    }
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshIndicators();
  }
};

/* nosourcemap */