/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TimelineCanvasPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var canvasData = {
  nodes: [],
  edges: []
};
var DEFAULT_SETTINGS = {
  mySetting: "default"
};
var TimelineCanvasPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "create-timeline-canvas",
      name: "Create timeline canvas",
      callback: () => {
        new CreateTimelineModal(this.app, (startYear, endYear, interval) => {
          for (let year = startYear; year <= endYear; year += interval) {
          }
          let x = 0;
          const y = 0;
          const spacing = 100;
          for (let year = startYear; year <= endYear; year += interval) {
            const node = {
              id: crypto.randomUUID(),
              // Generates a unique ID for each node
              type: "text",
              text: year.toString(),
              x,
              y,
              width: 100,
              height: 50
            };
            canvasData.nodes.push(node);
            x += spacing;
          }
          ;
          const fileName = `New Canvas ${Date.now()}.canvas`;
          const filePath = fileName;
          this.app.vault.create(filePath, JSON.stringify(canvasData, null, 2));
          const fileContent = JSON.stringify(canvasData, null, 2);
          this.app.vault.create(filePath, fileContent).then((file) => {
            this.app.workspace.getLeaf(true).openFile(file);
          }).catch((error) => {
            console.error("Failed to create canvas file:", error);
          });
        }).open();
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var CreateTimelineModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.setTitle("Create a timeline canvas");
    let startYear = "";
    let endYear = "";
    let interval = "";
    new import_obsidian.Setting(this.contentEl).setName("Start year").addText((text) => text.onChange((value) => {
      startYear = value;
    }));
    new import_obsidian.Setting(this.contentEl).setName("End year").addText((text) => text.onChange((value) => {
      endYear = value;
    }));
    new import_obsidian.Setting(this.contentEl).setName("Interval").addText((text) => text.onChange((value) => {
      interval = value;
    }));
    new import_obsidian.Setting(this.contentEl).addButton((btn) => btn.setButtonText("Submit").setCta().onClick(() => {
      const numberStartYear = Number(startYear.trim());
      const numberEndYear = Number(endYear.trim());
      const numberInterval = Number(interval.trim());
      if (isNaN(numberStartYear) || isNaN(numberEndYear) || isNaN(numberInterval)) {
        new import_obsidian.Notice("One or more of the fields are not valid numbers");
      } else if (numberEndYear <= numberStartYear) {
        new import_obsidian.Notice("End year is less than or the same as start year");
      } else if (numberInterval <= 0) {
        new import_obsidian.Notice("Interval needs to be greater than 0");
      } else if ((numberEndYear - numberStartYear) / numberInterval > 1e3) {
        new import_obsidian.Notice("Length of timeline cannot be more than 1000 cards long");
      } else {
        this.close();
        onSubmit(numberStartYear, numberEndYear, numberInterval);
      }
    }));
  }
  onOpen() {
  }
  onClose() {
  }
};


/* nosourcemap */