/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PriorityMatrixPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/view.ts
var import_obsidian = require("obsidian");

// src/types.ts
var QUADRANT_META = {
  ["q1" /* Q1 */]: {
    id: "q1" /* Q1 */,
    label: "Urgent & Important",
    action: "Do",
    description: "Do these tasks immediately",
    colorClass: "pm-quadrant-q1"
  },
  ["q2" /* Q2 */]: {
    id: "q2" /* Q2 */,
    label: "Not Urgent & Important",
    action: "Schedule",
    description: "Schedule time for these tasks",
    colorClass: "pm-quadrant-q2"
  },
  ["q3" /* Q3 */]: {
    id: "q3" /* Q3 */,
    label: "Urgent & Not Important",
    action: "Delegate",
    description: "Delegate these tasks if possible",
    colorClass: "pm-quadrant-q3"
  },
  ["q4" /* Q4 */]: {
    id: "q4" /* Q4 */,
    label: "Not Urgent & Not Important",
    action: "Eliminate",
    description: "Consider eliminating these tasks",
    colorClass: "pm-quadrant-q4"
  }
};
var QUADRANT_COLORS = {
  ["q1" /* Q1 */]: "#ef4444",
  ["q2" /* Q2 */]: "#3b82f6",
  ["q3" /* Q3 */]: "#f59e0b",
  ["q4" /* Q4 */]: "#6b7280"
};
var DEFAULT_DATA = {
  tasks: [],
  version: 1
};
var VIEW_TYPE_PRIORITY = "priority-matrix-view";

// src/view.ts
var PriorityMatrixView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.draggedTaskId = null;
    this.touchClone = null;
    this.touchTimeout = null;
    this.draggedEl = null;
    this.completedSectionExpanded = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_PRIORITY;
  }
  getDisplayText() {
    return "Task priority matrix";
  }
  getIcon() {
    return "layout-grid";
  }
  onOpen() {
    this.renderMatrix();
    if (import_obsidian.Platform.isMobile && !this.plugin.data.hasSeenDragHint) {
      new import_obsidian.Notice("Long-press a task to drag it between quadrants", 5e3);
      this.plugin.data.hasSeenDragHint = true;
      void this.plugin.savePluginData();
    }
    return Promise.resolve();
  }
  onClose() {
    this.cleanupTouchDrag();
    return Promise.resolve();
  }
  // ==================== RENDERING ====================
  renderMatrix() {
    const container = this.contentEl;
    container.empty();
    container.addClass("pm-container");
    const matrixWrapper = container.createDiv({ cls: "pm-matrix-wrapper" });
    const urgencyLabel = matrixWrapper.createDiv({ cls: "pm-axis-label pm-axis-urgency" });
    urgencyLabel.createSpan({ text: "URGENT", cls: "pm-axis-left" });
    urgencyLabel.createSpan({ text: "NOT URGENT", cls: "pm-axis-right" });
    const importanceLabel = matrixWrapper.createDiv({ cls: "pm-axis-label pm-axis-importance" });
    importanceLabel.createSpan({ text: "NOT IMPORTANT", cls: "pm-axis-bottom" });
    importanceLabel.createSpan({ text: "IMPORTANT", cls: "pm-axis-top" });
    const grid = matrixWrapper.createDiv({ cls: "pm-grid" });
    const quadrantOrder = ["q1" /* Q1 */, "q2" /* Q2 */, "q3" /* Q3 */, "q4" /* Q4 */];
    for (const q of quadrantOrder) {
      this.renderQuadrant(grid, QUADRANT_META[q]);
    }
    const completedTasks = this.plugin.getCompletedTasks();
    if (completedTasks.length > 0) {
      this.renderCompletedSection(container, completedTasks);
    }
    requestAnimationFrame(() => this.updateOverflowIndicators());
  }
  updateOverflowIndicators() {
    this.contentEl.querySelectorAll(".pm-task-list").forEach((el) => {
      const list = el;
      list.toggleClass("pm-has-overflow", list.scrollHeight > list.clientHeight);
    });
  }
  renderQuadrant(gridEl, meta) {
    const quadrantEl = gridEl.createDiv({
      cls: `pm-quadrant ${meta.colorClass}`,
      attr: { "data-quadrant": meta.id }
    });
    const tasks = this.plugin.getTasksForQuadrant(meta.id);
    const headerEl = quadrantEl.createDiv({ cls: "pm-quadrant-header" });
    const titleGroup = headerEl.createDiv({ cls: "pm-quadrant-title-group" });
    const h3 = titleGroup.createEl("h3", { text: meta.action, cls: "pm-quadrant-action" });
    if (tasks.length > 0) {
      h3.createSpan({ text: ` ${tasks.length}`, cls: "pm-task-count" });
    }
    const addBtn = headerEl.createEl("button", {
      cls: "pm-add-btn",
      attr: { "aria-label": `Add task to ${meta.action}` }
    });
    (0, import_obsidian.setIcon)(addBtn, "plus");
    const listEl = quadrantEl.createDiv({ cls: "pm-task-list" });
    if (tasks.length === 0) {
      quadrantEl.addClass("pm-quadrant-empty");
      this.renderEmptyState(listEl);
    } else {
      for (const task of tasks) {
        this.renderTask(listEl, task);
      }
    }
    const formEl = quadrantEl.createDiv({ cls: "pm-add-form pm-hidden" });
    this.renderAddTaskForm(formEl, meta.id);
    addBtn.addEventListener("click", () => {
      const isHidden = formEl.hasClass("pm-hidden");
      formEl.toggleClass("pm-hidden", !isHidden);
      if (isHidden) {
        const input = formEl.querySelector(".pm-task-input");
        input == null ? void 0 : input.focus();
        setTimeout(() => {
          formEl.scrollIntoView({ behavior: "smooth", block: "nearest" });
        }, 300);
      }
    });
    this.setupQuadrantDropZone(quadrantEl, meta.id);
  }
  renderTask(listEl, task) {
    const taskEl = listEl.createDiv({
      cls: "pm-task",
      attr: {
        "data-task-id": task.id,
        draggable: "true"
      }
    });
    const dragHandle = taskEl.createDiv({ cls: "pm-task-drag-handle" });
    dragHandle.textContent = "\u2630";
    const checkbox = taskEl.createDiv({ cls: "pm-task-checkbox" });
    checkbox.addEventListener("click", (e) => {
      e.stopPropagation();
      void this.handleCompleteTask(task.id);
    });
    const contentEl = taskEl.createDiv({ cls: "pm-task-content" });
    contentEl.createDiv({ cls: "pm-task-title", text: task.title });
    if (task.dueDate) {
      const dueDateEl = contentEl.createDiv({ cls: "pm-task-due" });
      if (isDueDatePast(task.dueDate)) {
        dueDateEl.addClass("pm-overdue");
      }
      dueDateEl.setText(formatDueDate(task.dueDate));
    }
    contentEl.addEventListener("click", (e) => {
      e.stopPropagation();
      this.renderEditForm(taskEl, task);
    });
    const deleteBtn = taskEl.createEl("button", {
      cls: "pm-task-delete",
      attr: { "aria-label": "Delete task" }
    });
    deleteBtn.textContent = "\xD7";
    deleteBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      void this.handleDeleteTask(task.id);
    });
    this.setupDesktopDrag(taskEl, task.id);
    this.setupTouchDrag(taskEl, task.id);
  }
  renderAddTaskForm(formEl, quadrant) {
    const inputEl = formEl.createEl("input", {
      cls: "pm-task-input",
      attr: {
        type: "text",
        placeholder: "Task title..."
      }
    });
    const dateRow = formEl.createDiv({ cls: "pm-form-date-row" });
    dateRow.createEl("label", { text: "Due:", cls: "pm-date-label" });
    const dateInput = dateRow.createEl("input", {
      cls: "pm-date-input",
      attr: { type: "date" }
    });
    const btnRow = formEl.createDiv({ cls: "pm-form-btn-row" });
    const submitBtn = btnRow.createEl("button", {
      text: "Add",
      cls: "pm-form-submit"
    });
    const cancelBtn = btnRow.createEl("button", {
      text: "Cancel",
      cls: "pm-form-cancel"
    });
    const submit = () => {
      const title = inputEl.value.trim();
      if (!title) {
        inputEl.addClass("pm-input-error");
        return;
      }
      const dueDate = dateInput.value || null;
      void this.handleAddTask(quadrant, title, dueDate);
      inputEl.value = "";
      dateInput.value = "";
      inputEl.removeClass("pm-input-error");
      formEl.addClass("pm-hidden");
    };
    submitBtn.addEventListener("click", submit);
    inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        submit();
      } else if (e.key === "Escape") {
        formEl.addClass("pm-hidden");
      }
    });
    inputEl.addEventListener("input", () => {
      inputEl.removeClass("pm-input-error");
    });
    inputEl.addEventListener("focus", () => {
      setTimeout(() => {
        formEl.scrollIntoView({ behavior: "smooth", block: "nearest" });
      }, 300);
    });
    cancelBtn.addEventListener("click", () => {
      inputEl.value = "";
      dateInput.value = "";
      inputEl.removeClass("pm-input-error");
      formEl.addClass("pm-hidden");
    });
  }
  renderEmptyState(listEl) {
    listEl.createDiv({ cls: "pm-empty-state", text: "Tap + to add, tap a task to edit" });
  }
  // ==================== TASK ACTIONS ====================
  async handleAddTask(quadrant, title, dueDate) {
    const newTask = this.plugin.addTask(title, quadrant, dueDate);
    await this.plugin.savePluginData();
    this.renderMatrix();
    const newTaskEl = this.contentEl.querySelector(`[data-task-id="${newTask.id}"]`);
    if (newTaskEl) {
      newTaskEl.addClass("pm-task-new");
    }
  }
  async handleDeleteTask(taskId) {
    const savedTask = this.plugin.data.tasks.find((t) => t.id === taskId);
    if (!savedTask)
      return;
    const taskCopy = { ...savedTask };
    this.plugin.deleteTask(taskId);
    await this.plugin.savePluginData();
    this.renderMatrix();
    const fragment = document.createDocumentFragment();
    fragment.appendText("Task deleted. ");
    const undoLink = fragment.createEl("a", { text: "Undo", cls: "pm-undo-link" });
    const notice = new import_obsidian.Notice(fragment, 5e3);
    undoLink.addEventListener("click", () => {
      this.plugin.restoreTask(taskCopy);
      void this.plugin.savePluginData();
      this.renderMatrix();
      notice.hide();
    });
  }
  async handleCompleteTask(taskId) {
    const savedTask = this.plugin.data.tasks.find((t) => t.id === taskId);
    if (!savedTask)
      return;
    const taskCopy = { ...savedTask };
    const hadCompletedBefore = this.plugin.getCompletedTasks().length > 0;
    this.plugin.completeTask(taskId);
    if (!hadCompletedBefore) {
      this.completedSectionExpanded = true;
    }
    await this.plugin.savePluginData();
    this.renderMatrix();
    const fragment = document.createDocumentFragment();
    fragment.appendText("Task completed. ");
    const undoLink = fragment.createEl("a", { text: "Undo", cls: "pm-undo-link" });
    const notice = new import_obsidian.Notice(fragment, 5e3);
    undoLink.addEventListener("click", () => {
      this.plugin.uncompleteTask(taskCopy.id);
      void this.plugin.savePluginData();
      this.renderMatrix();
      notice.hide();
    });
  }
  async handleUncompleteTask(taskId) {
    this.plugin.uncompleteTask(taskId);
    await this.plugin.savePluginData();
    this.renderMatrix();
  }
  async handleEditTask(taskId, title, dueDate) {
    this.plugin.editTask(taskId, title, dueDate);
    await this.plugin.savePluginData();
    this.renderMatrix();
  }
  renderEditForm(taskEl, task) {
    taskEl.setAttribute("draggable", "false");
    taskEl.empty();
    taskEl.addClass("pm-task-editing");
    const formEl = taskEl.createDiv({ cls: "pm-edit-form" });
    const titleInput = formEl.createEl("input", {
      cls: "pm-task-input",
      attr: { type: "text", value: task.title }
    });
    const dateRow = formEl.createDiv({ cls: "pm-form-date-row" });
    dateRow.createEl("label", { text: "Due:", cls: "pm-date-label" });
    const dateInput = dateRow.createEl("input", {
      cls: "pm-date-input",
      attr: { type: "date", value: task.dueDate || "" }
    });
    const btnRow = formEl.createDiv({ cls: "pm-form-btn-row" });
    const saveBtn = btnRow.createEl("button", { text: "Save", cls: "pm-form-submit" });
    const cancelBtn = btnRow.createEl("button", { text: "Cancel", cls: "pm-form-cancel" });
    const save = () => {
      const title = titleInput.value.trim();
      if (!title) {
        titleInput.addClass("pm-input-error");
        return;
      }
      const dueDate = dateInput.value || null;
      void this.handleEditTask(task.id, title, dueDate);
    };
    saveBtn.addEventListener("click", save);
    cancelBtn.addEventListener("click", () => this.renderMatrix());
    titleInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        save();
      else if (e.key === "Escape")
        this.renderMatrix();
    });
    titleInput.addEventListener("input", () => {
      titleInput.removeClass("pm-input-error");
    });
    titleInput.addEventListener("focus", () => {
      setTimeout(() => {
        formEl.scrollIntoView({ behavior: "smooth", block: "nearest" });
      }, 300);
    });
    formEl.addEventListener("mousedown", (e) => e.stopPropagation());
    formEl.addEventListener("touchstart", (e) => e.stopPropagation());
    titleInput.focus();
    titleInput.select();
  }
  // ==================== COMPLETED SECTION ====================
  renderCompletedSection(container, tasks) {
    const section = container.createDiv({ cls: "pm-completed-section" });
    const header = section.createDiv({ cls: "pm-completed-header" });
    const chevron = header.createSpan({ cls: "pm-completed-chevron" });
    chevron.textContent = "\u25B6";
    header.createSpan({ text: `Completed (${tasks.length})` });
    const isExpanded = this.completedSectionExpanded;
    const list = section.createDiv({
      cls: isExpanded ? "pm-completed-list" : "pm-completed-list pm-hidden"
    });
    if (isExpanded) {
      chevron.addClass("pm-completed-chevron-open");
    }
    for (const task of tasks) {
      this.renderCompletedTask(list, task);
    }
    header.addEventListener("click", () => {
      const isHidden = list.hasClass("pm-hidden");
      list.toggleClass("pm-hidden", !isHidden);
      chevron.toggleClass("pm-completed-chevron-open", isHidden);
      this.completedSectionExpanded = isHidden;
    });
  }
  renderCompletedTask(listEl, task) {
    const taskEl = listEl.createDiv({ cls: "pm-completed-task" });
    const checkbox = taskEl.createDiv({ cls: "pm-task-checkbox pm-checked" });
    checkbox.addEventListener("click", (e) => {
      e.stopPropagation();
      void this.handleUncompleteTask(task.id);
    });
    taskEl.createDiv({ cls: "pm-completed-task-title", text: task.title });
    const dot = taskEl.createDiv({ cls: "pm-quadrant-dot" });
    dot.setCssStyles({ background: QUADRANT_COLORS[task.quadrant] });
    taskEl.createDiv({
      cls: "pm-completed-task-time",
      text: formatCompletedDate(task.completedAt)
    });
    const deleteBtn = taskEl.createEl("button", {
      cls: "pm-task-delete",
      attr: { "aria-label": "Delete task" }
    });
    deleteBtn.textContent = "\xD7";
    deleteBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      void this.handleDeleteTask(task.id);
    });
  }
  // ==================== DESKTOP DRAG & DROP ====================
  setupDesktopDrag(taskEl, taskId) {
    taskEl.addEventListener("dragstart", (e) => {
      if (e.dataTransfer) {
        e.dataTransfer.setData("text/plain", taskId);
        e.dataTransfer.effectAllowed = "move";
      }
      taskEl.addClass("pm-dragging");
      this.draggedTaskId = taskId;
    });
    taskEl.addEventListener("dragend", () => {
      taskEl.removeClass("pm-dragging");
      this.draggedTaskId = null;
      this.contentEl.querySelectorAll(".pm-drop-target").forEach((el) => {
        el.removeClass("pm-drop-target");
      });
    });
  }
  setupQuadrantDropZone(quadrantEl, quadrant) {
    quadrantEl.addEventListener("dragover", (e) => {
      e.preventDefault();
      if (e.dataTransfer) {
        e.dataTransfer.dropEffect = "move";
      }
      quadrantEl.addClass("pm-drop-target");
    });
    quadrantEl.addEventListener("dragleave", (e) => {
      const relatedTarget = e.relatedTarget;
      if (!quadrantEl.contains(relatedTarget)) {
        quadrantEl.removeClass("pm-drop-target");
      }
    });
    quadrantEl.addEventListener("drop", (e) => {
      var _a;
      e.preventDefault();
      quadrantEl.removeClass("pm-drop-target");
      const taskId = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
      if (!taskId)
        return;
      const task = this.plugin.data.tasks.find((t) => t.id === taskId);
      if (task && task.quadrant !== quadrant) {
        this.plugin.moveTask(taskId, quadrant);
        this.renderMatrix();
        void this.plugin.savePluginData();
      }
    });
  }
  // ==================== MOBILE TOUCH DRAG & DROP ====================
  setupTouchDrag(taskEl, taskId) {
    let startX = 0;
    let startY = 0;
    let isDragging = false;
    const onTouchStart = (e) => {
      if (e.touches.length !== 1)
        return;
      const touch = e.touches[0];
      startX = touch.clientX;
      startY = touch.clientY;
      isDragging = false;
      this.touchTimeout = window.setTimeout(() => {
        isDragging = true;
        this.draggedEl = taskEl;
        this.draggedTaskId = taskId;
        const clone = taskEl.cloneNode(true);
        clone.addClass("pm-touch-clone");
        clone.setCssStyles({
          left: `${startX - 50}px`,
          top: `${startY - 20}px`,
          width: `${taskEl.offsetWidth}px`
        });
        document.body.appendChild(clone);
        this.touchClone = clone;
        taskEl.addClass("pm-dragging");
        if (navigator.vibrate) {
          navigator.vibrate(50);
        }
      }, 250);
    };
    const onTouchMove = (e) => {
      const touch = e.touches[0];
      const dx = Math.abs(touch.clientX - startX);
      const dy = Math.abs(touch.clientY - startY);
      if (!isDragging && (dx > 10 || dy > 10)) {
        if (this.touchTimeout !== null) {
          clearTimeout(this.touchTimeout);
          this.touchTimeout = null;
        }
        return;
      }
      if (!isDragging || !this.touchClone)
        return;
      e.preventDefault();
      this.touchClone.setCssStyles({
        left: `${touch.clientX - 50}px`,
        top: `${touch.clientY - 20}px`
      });
      const targetQuadrant = this.getQuadrantAtPoint(touch.clientX, touch.clientY);
      this.contentEl.querySelectorAll(".pm-quadrant").forEach((el) => {
        el.removeClass("pm-drop-target");
      });
      if (targetQuadrant) {
        const targetEl = this.contentEl.querySelector(`[data-quadrant="${targetQuadrant}"]`);
        if (targetEl) {
          targetEl.addClass("pm-drop-target");
        }
      }
    };
    const onTouchEnd = (e) => {
      if (this.touchTimeout !== null) {
        clearTimeout(this.touchTimeout);
        this.touchTimeout = null;
      }
      if (!isDragging || !this.draggedTaskId) {
        this.cleanupTouchDrag();
        return;
      }
      const touch = e.changedTouches[0];
      const targetQuadrant = this.getQuadrantAtPoint(touch.clientX, touch.clientY);
      if (targetQuadrant && this.draggedTaskId) {
        const task = this.plugin.data.tasks.find((t) => t.id === this.draggedTaskId);
        if (task && task.quadrant !== targetQuadrant) {
          this.plugin.moveTask(this.draggedTaskId, targetQuadrant);
          void this.plugin.savePluginData();
        }
      }
      isDragging = false;
      this.cleanupTouchDrag();
      this.renderMatrix();
    };
    const onTouchCancel = () => {
      if (this.touchTimeout !== null) {
        clearTimeout(this.touchTimeout);
        this.touchTimeout = null;
      }
      isDragging = false;
      this.cleanupTouchDrag();
    };
    taskEl.addEventListener("touchstart", onTouchStart, { passive: true });
    taskEl.addEventListener("touchmove", onTouchMove, { passive: false });
    taskEl.addEventListener("touchend", onTouchEnd);
    taskEl.addEventListener("touchcancel", onTouchCancel);
  }
  cleanupTouchDrag() {
    if (this.touchClone) {
      this.touchClone.remove();
      this.touchClone = null;
    }
    if (this.draggedEl) {
      this.draggedEl.removeClass("pm-dragging");
      this.draggedEl = null;
    }
    this.draggedTaskId = null;
    this.contentEl.querySelectorAll(".pm-drop-target").forEach((el) => {
      el.removeClass("pm-drop-target");
    });
  }
  getQuadrantAtPoint(x, y) {
    const quadrants = this.contentEl.querySelectorAll(".pm-quadrant");
    for (const qEl of Array.from(quadrants)) {
      const rect = qEl.getBoundingClientRect();
      if (x >= rect.left && x <= rect.right && y >= rect.top && y <= rect.bottom) {
        return qEl.getAttribute("data-quadrant");
      }
    }
    return null;
  }
};
function formatDueDate(dateStr) {
  const date = new Date(dateStr + "T00:00:00");
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const diffMs = date.getTime() - today.getTime();
  const diffDays = Math.round(diffMs / (1e3 * 60 * 60 * 24));
  if (diffDays === 0)
    return "Today";
  if (diffDays === 1)
    return "Tomorrow";
  if (diffDays === -1)
    return "Yesterday";
  if (diffDays > 1 && diffDays <= 7)
    return `In ${diffDays} days`;
  if (diffDays < -1)
    return `${Math.abs(diffDays)} days ago`;
  return date.toLocaleDateString(void 0, {
    month: "short",
    day: "numeric",
    year: date.getFullYear() !== today.getFullYear() ? "numeric" : void 0
  });
}
function isDueDatePast(dateStr) {
  const date = new Date(dateStr + "T23:59:59");
  return date < new Date();
}
function formatCompletedDate(isoDateStr) {
  const completed = new Date(isoDateStr);
  const now = new Date();
  const diffMs = now.getTime() - completed.getTime();
  const diffMin = Math.floor(diffMs / 6e4);
  const diffHours = Math.floor(diffMs / 36e5);
  const diffDays = Math.floor(diffMs / 864e5);
  if (diffMin < 1)
    return "Just now";
  if (diffMin < 60)
    return `${diffMin} min ago`;
  if (diffHours < 24)
    return `${diffHours} hours ago`;
  if (diffDays === 1)
    return "Yesterday";
  return `${diffDays} days ago`;
}

// src/main.ts
var PriorityMatrixPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.data = DEFAULT_DATA;
  }
  async onload() {
    await this.loadPluginData();
    this.registerView(
      VIEW_TYPE_PRIORITY,
      (leaf) => new PriorityMatrixView(leaf, this)
    );
    this.addRibbonIcon("layout-grid", "Task priority matrix", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-view",
      name: "Open matrix",
      callback: () => {
        void this.activateView();
      }
    });
  }
  async activateView() {
    const { workspace } = this.app;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_PRIORITY);
    if (leaves.length > 0) {
      await workspace.revealLeaf(leaves[0]);
      return;
    }
    const leaf = workspace.getLeaf(false);
    await leaf.setViewState({
      type: VIEW_TYPE_PRIORITY,
      active: true
    });
    await workspace.revealLeaf(leaf);
  }
  async loadPluginData() {
    const loaded = await this.loadData();
    this.data = Object.assign({}, DEFAULT_DATA, loaded);
    if (!Array.isArray(this.data.tasks)) {
      this.data.tasks = [];
    }
  }
  async savePluginData() {
    await this.saveData(this.data);
  }
  async onExternalSettingsChange() {
    await this.loadPluginData();
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_PRIORITY);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof PriorityMatrixView) {
        view.renderMatrix();
      }
    }
  }
  getTasksForQuadrant(quadrant) {
    return this.data.tasks.filter((t) => t.quadrant === quadrant && !t.completedAt).sort((a, b) => a.order - b.order);
  }
  completeTask(taskId) {
    const task = this.data.tasks.find((t) => t.id === taskId);
    if (!task)
      return false;
    task.completedAt = new Date().toISOString();
    return true;
  }
  uncompleteTask(taskId) {
    const task = this.data.tasks.find((t) => t.id === taskId);
    if (!task || !task.completedAt)
      return false;
    task.completedAt = null;
    return true;
  }
  getCompletedTasks() {
    return this.data.tasks.filter((t) => !!t.completedAt).sort((a, b) => new Date(b.completedAt).getTime() - new Date(a.completedAt).getTime());
  }
  addTask(title, quadrant, dueDate) {
    const tasksInQuadrant = this.getTasksForQuadrant(quadrant);
    const newTask = {
      id: this.generateId(),
      title: title.trim(),
      quadrant,
      dueDate,
      createdAt: new Date().toISOString(),
      order: tasksInQuadrant.length
    };
    this.data.tasks.push(newTask);
    return newTask;
  }
  deleteTask(taskId) {
    this.data.tasks = this.data.tasks.filter((t) => t.id !== taskId);
  }
  restoreTask(task) {
    this.data.tasks.push(task);
  }
  editTask(taskId, title, dueDate) {
    const task = this.data.tasks.find((t) => t.id === taskId);
    if (!task)
      return false;
    task.title = title.trim();
    task.dueDate = dueDate;
    return true;
  }
  moveTask(taskId, targetQuadrant) {
    const task = this.data.tasks.find((t) => t.id === taskId);
    if (task) {
      task.quadrant = targetQuadrant;
      const tasksInTarget = this.data.tasks.filter(
        (t) => t.quadrant === targetQuadrant && t.id !== taskId
      );
      task.order = tasksInTarget.length;
    }
  }
  generateId() {
    if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
      return crypto.randomUUID();
    }
    return Date.now().toString(36) + Math.random().toString(36).substring(2, 11);
  }
};

/* nosourcemap */