/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  MovieModal: () => MovieModal,
  default: () => MoviePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var extractMovieUrl = "https://www.omdbapi.com/?apikey={key}&t=";
var youtubeApiUrl = "https://www.googleapis.com/youtube/v3/search?key={key}&type=video&maxResults=1&videoEmbeddable=true&q=";
var DEFAULT_SETTINGS = {
  omdbapikey: "",
  youtubeapikey: "",
  template: "{{Poster}}\n**Length:** {{Runtime}}\n**Genre:** {{Genre}}\n**Actors:** {{Actors}}\n**Year:** {{Year}}\n**IMDB Score:** {{imdbRating}} ({{imdbVotes}})\n\n{{Plot}}\n\n{{Trailer}}",
  mainPath: "movies",
  assetPath: "assets",
  fileName: "{{Title}}",
  imageSize: 200
};
var MoviePlugin = class extends import_obsidian.Plugin {
  async addImageToAssets(url, fileName) {
    const { vault } = this.app;
    const assetsPath = this.settings.assetPath;
    const response = await (0, import_obsidian.requestUrl)(url);
    const arrayBuffer = response.arrayBuffer;
    await vault.createBinary(assetsPath + "/" + fileName, arrayBuffer);
  }
  async getTrailerOnYoutube(title) {
    const url = this.youtubeApiUrl + title + " trailer";
    let response = await (0, import_obsidian.requestUrl)({
      url,
      method: "GET"
    });
    response = response.json.items[0].id.videoId;
    return response;
  }
  async formatter(data, template) {
    for (const key in data) {
      if (Object.prototype.hasOwnProperty.call(data, key) && key !== "Poster" && key !== "Trailer" && key !== "Runtime") {
        const value = data[key];
        template = template.replace(`{{${key}}}`, value);
      }
    }
    if (data.Runtime && data.Runtime !== "N/A") {
      const minute = parseInt(data.Runtime.split(" ")[0]);
      const hour = Math.floor(minute / 60);
      const minuteLeft = minute % 60;
      template = template.replace("{{Runtime}}", `${hour}h ${minuteLeft}m`);
    } else {
      template = template.replace("{{Runtime}}", "-");
    }
    if (data.Poster && data.Poster !== "N/A") {
      const fileName = this.settings.fileName.replace("{{Title}}", data.Title);
      const imageSize = this.settings.imageSize || 200;
      template = template.replace("{{Poster}}", `![[${this.settings.assetPath}/${fileName}.jpg|movie|${imageSize}]]`);
    } else {
      template = template.replace("{{Poster}}", "-");
    }
    if (this.settings.youtubeapikey) {
      const trailer = await this.getTrailerOnYoutube(data.Title);
      template = template.replace("{{Trailer}}", `<iframe class="movie" width="560" height="315" src="https://www.youtube.com/embed/${trailer}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`);
    } else {
      template = template.replace("{{Trailer}}", "");
    }
    return template;
  }
  async formatMovie(movie) {
    let template = this.settings.template;
    template = await this.formatter(movie, template);
    return template;
  }
  async crawlAndAdd(text) {
    if (!this.settings.omdbapikey) {
      new import_obsidian.Notice("Please enter your OMDB API key in the settings.");
      return;
    }
    if (!this.settings.youtubeapikey) {
      new import_obsidian.Notice("Youtube API key is missing. Trailer will not be added.");
    }
    const movie = await this.crawlMovie(text);
    if (!movie) {
      return;
    }
    const title = movie.Title;
    this.addImageToAssets(movie.Poster, title + ".jpg");
    const movieStr = await this.formatMovie(movie);
    await this.addContentToFile(movieStr, movie);
  }
  getUrl(text) {
    var _a;
    if (/tt\d+$/.test(text))
      return this.omdbApiUrl + "i=" + text;
    else if (/\s\([\d]{4}\)/.test(text))
      return this.omdbApiUrl + "t=" + text.replace(/\s\([\d]{4}\)/, "") + "&y=" + ((_a = text.match(/\(([\d]{4})\)/)) == null ? void 0 : _a[1]);
    else
      return this.omdbApiUrl + "t=" + text;
  }
  async crawlMovie(text) {
    const movieUrl = this.getUrl(text);
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: movieUrl,
        method: "GET"
      });
      console.log(response);
      const movie = response.json;
      movie.Title = movie.Title.replace(/[/\\?%*:|"<>]/g, "-");
      return movie;
    } catch (e) {
      new import_obsidian.Notice("Movie not found.");
      new import_obsidian.Notice(e);
      new import_obsidian.Notice(movieUrl);
      return;
    }
  }
  async addContentToFile(text, movie) {
    const { vault } = this.app;
    const mainPath = this.settings.mainPath;
    const fileName = await this.formatter(movie, this.settings.fileName);
    await vault.create(mainPath + "/" + fileName + ".md", text);
    await this.app.workspace.openLinkText("", mainPath + "/" + fileName + ".md");
    new import_obsidian.Notice("Movie added successfully!");
  }
  updateKeys() {
    this.omdbApiUrl = extractMovieUrl.replace("{key}", this.settings.omdbapikey);
    this.youtubeApiUrl = youtubeApiUrl.replace("{key}", this.settings.youtubeapikey);
  }
  async onload() {
    await this.loadSettings();
    this.updateKeys();
    const ribbonIconEl = this.addRibbonIcon("clapperboard", "Get Movie", (event) => {
      var _a;
      const sel = (_a = window.getSelection()) != null ? _a : "";
      const text = sel.toString();
      if (text) {
        this.crawlAndAdd(text);
      } else {
        new MovieModal(this.app, (result) => {
          this.crawlAndAdd(result);
        }).open();
      }
    });
    this.addCommand({
      id: "crawl-movie",
      name: "Crawl Movie",
      callback: () => {
        new MovieModal(this.app, (result) => {
          this.crawlAndAdd(result);
        }).open();
      }
    });
    this.addSettingTab(new SampleSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var MovieModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h1", { text: "Movie name" });
    new import_obsidian.Setting(contentEl).setName("Name").addText((text) => text.onChange((value) => {
      this.result = value;
    }));
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("Submit").setCta().onClick(() => {
      this.close();
      this.onSubmit(this.result);
    }));
  }
  onClose() {
    let { contentEl } = this;
    contentEl.empty();
  }
};
var SampleSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const variables = ["Title", "Year", "Rated", "Released", "Runtime", "Genre", "Director", "Writer", "Actors", "Plot", "Language", "Country", "Awards", "Poster", "Metascore", "imdbRating", "imdbVotes", "imdbID", "Type", "DVD", "BoxOffice"];
    const variablesStr = variables.map((variable) => {
      return "{{" + variable + "}}";
    }).join(", ");
    new import_obsidian.Setting(containerEl).setName("Info").setDesc("Supported variables: " + variablesStr);
    new import_obsidian.Setting(containerEl).setName("OMDB API Key").setDesc("It's a key for OMDB API").addText((text) => text.setPlaceholder("Enter your key").setValue(this.plugin.settings.omdbapikey).onChange(async (value) => {
      this.plugin.settings.omdbapikey = value;
      await this.plugin.saveSettings();
      this.plugin.updateKeys();
    }));
    new import_obsidian.Setting(containerEl).setName("Youtube API Key").setDesc("It's a key for Youtube API").addText((text) => text.setPlaceholder("Enter your key").setValue(this.plugin.settings.youtubeapikey).onChange(async (value) => {
      this.plugin.settings.youtubeapikey = value;
      await this.plugin.saveSettings();
      this.plugin.updateKeys();
    }));
    containerEl.createEl("h2", { text: "Structure" });
    new import_obsidian.Setting(containerEl).setName("Template").setDesc("It's a template for your movie note.").addTextArea((text) => text.setPlaceholder("Enter your template").setValue(this.plugin.settings.template).onChange(async (value) => {
      this.plugin.settings.template = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Main Path").setDesc("It's a path for your movie note").addText((text) => text.setPlaceholder("Enter your path").setValue(this.plugin.settings.mainPath).onChange(
      async (value) => {
        this.plugin.settings.mainPath = value;
        await this.plugin.saveSettings();
      }
    ));
    new import_obsidian.Setting(containerEl).setName("File name").setDesc("It's a file name for your movie note").addText((text) => text.setPlaceholder("Enter your file name").setValue(this.plugin.settings.fileName).onChange(
      async (value) => {
        this.plugin.settings.fileName = value;
        await this.plugin.saveSettings();
      }
    ));
    new import_obsidian.Setting(containerEl).setName("Image Path").setDesc("It's a path for your movie note").addText((text) => text.setPlaceholder("Enter your path").setValue(this.plugin.settings.assetPath).onChange(
      async (value) => {
        this.plugin.settings.assetPath = value;
        await this.plugin.saveSettings();
      }
    ));
    new import_obsidian.Setting(containerEl).setName("File Name").setDesc("It's a file name for your movie note").addText((text) => text.setPlaceholder("Enter your file name").setValue(this.plugin.settings.fileName).onChange(
      async (value) => {
        this.plugin.settings.fileName = value;
        await this.plugin.saveSettings();
      }
    ));
    containerEl.createEl("h2", { text: "Advanced" });
    new import_obsidian.Setting(containerEl).setName("Image Size").setDesc("It's a size for your movie note").addText((text) => text.setPlaceholder("Enter your size").setValue(this.plugin.settings.imageSize.toString()).onChange(
      async (value) => {
        this.plugin.settings.imageSize = parseInt(value);
        await this.plugin.saveSettings();
      }
    ));
  }
};

/* nosourcemap */