/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WordGoalPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  toggleAllFiles: true,
  allFilesGoal: "100",
  frontmatterKey: "word-goal"
};
var MySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Use default word goal for all files").setDesc("When off, the progress bar shows only on notes that have their own goal property").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.toggleAllFiles).onChange(async (value) => {
        this.plugin.settings.toggleAllFiles = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default word goal").addText(
      (text) => text.setValue(this.plugin.settings.allFilesGoal).onChange(async (value) => {
        const n = parseInt(value);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.allFilesGoal = String(n);
          await this.plugin.saveSettings();
        }
      }).inputEl.addEventListener("input", (e) => {
        const input = e.target;
        input.value = input.value.replace(/\D/g, "");
        input.value = input.value.replace(/^0+/, "");
      })
    );
    new import_obsidian.Setting(containerEl).setName("Frontmatter key for per-file goal").setDesc("If this property exists in a note's frontmatter, its value is used as the word goal for that file").addText(
      (text) => text.setValue(this.plugin.settings.frontmatterKey).onChange(async (value) => {
        if (value.length > 0) {
          this.plugin.settings.frontmatterKey = value;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/pb.ts
var ProgressBar = class {
  constructor(statusBarItem) {
    this.container = statusBarItem;
    this.container.addClass("word-goal-status");
    this.label = this.container.createSpan({ cls: "word-goal-label" });
    this.track = this.container.createDiv({ cls: "word-goal-track" });
    this.fill = this.track.createDiv({ cls: "word-goal-fill" });
  }
  // Обновить состояние: current — текущее кол-во слов, goal — цель
  update(current, goal) {
    const progress = Math.min(current / goal, 1);
    const percent = Math.round(progress * 100);
    const done = progress >= 1;
    this.label.setText(`${current} / ${goal}`);
    this.fill.style.width = `${percent}%`;
    this.fill.toggleClass("word-goal-fill--done", done);
    this.track.toggleClass("word-goal-track--done", done);
  }
  // Скрыть бар (когда нет активного файла или цели)
  hide() {
    this.container.setCssProps({ display: "none" });
  }
  show() {
    this.container.setCssProps({ display: "" });
  }
};

// src/main.ts
var WordGoalPlugin = class extends import_obsidian2.Plugin {
  // Can be not really correct as core plugin
  countWords(text) {
    const withoutFrontmatter = text.replace(/^---[\s\S]*?---\n?/, "");
    const plain = withoutFrontmatter.replace(/```[\s\S]*?```/g, "").replace(/`[^`]*`/g, "").replace(/!\[.*?\]\(.*?\)/g, "").replace(/\[.*?\]\(.*?\)/g, "$1").replace(/[#*_~>|-]+/g, " ").trim();
    if (!plain) return 0;
    return plain.split(/\s+/).filter((w) => w.length > 0).length;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MySettingTab(this.app, this));
    this.pb = new ProgressBar(this.addStatusBarItem());
    this.app.workspace.on("active-leaf-change", () => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
      const file = this.app.workspace.getActiveFile();
      if (!file) {
        this.pb.hide();
        return;
      }
      const goal = this.getGoalForFile(file, this.settings.toggleAllFiles);
      if (goal === null) {
        this.pb.hide();
        return;
      }
      this.pb.show();
      if (view) {
        this.pb.update(
          this.countWords(view.editor.getValue()),
          goal
        );
      }
    });
    this.app.workspace.on("editor-change", (editor) => {
      const file = this.app.workspace.getActiveFile();
      if (!file) {
        this.pb.hide();
        return;
      }
      const goal = this.getGoalForFile(file, this.settings.toggleAllFiles);
      if (goal === null) {
        this.pb.hide();
        return;
      }
      this.pb.show();
      this.pb.update(
        this.countWords(editor.getValue()),
        goal
      );
    });
  }
  getGoalForFile(file, useDefault) {
    var _a;
    const frontmatter = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    const fileGoal = frontmatter == null ? void 0 : frontmatter[this.settings.frontmatterKey];
    if (typeof fileGoal === "number" && fileGoal > 0) {
      return fileGoal;
    }
    if (typeof fileGoal === "string") {
      const n = parseInt(fileGoal);
      if (!isNaN(n) && n > 0) return n;
    }
    if (!useDefault) return null;
    const globalGoal = parseInt(this.settings.allFilesGoal);
    if (!isNaN(globalGoal) && globalGoal > 0) {
      return globalGoal;
    }
    return null;
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};


/* nosourcemap */